var pr2021 = [
{
	date: 'December 23, 2021',
    file: '2021/12/23_Potter.asp',
    title: 'AG Ellison: Conviction of Kimberly Potter provides ‘measure of accountability’ on ‘long road to justice for all’',
    lede: 'Holds law enforcement ‘in high regard and to high standards’; holding Potter accountable ‘doesn’t diminish you’; All of us will miss out on who Daunte could have been…there will be an empty chair at the Wright family dinner table during the holidays’',
},
{
	date: 'December 22, 2021',
    file: '2021/12/22_MadisonEquities.asp',
    title: 'Attorney General Ellison prevails at Supreme Court in effort to investigate wage theft allegations against downtown Saint Paul’s largest landowner',
    lede: 'Madison Equities workers have alleged widespread and purposeful evasion of state and federal overtime laws by company and its subsidiaries. Ruling underscores AG’s broad authority to investigate violations of state law in business, commerce, and trade',
},
{
	date: 'December 15, 2021',
    file: '2021/12/15_Chauvin.asp',
    title: 'AG Ellison: Derek Chauvin’s ‘important and historic’ guilty plea ‘another moment of accountability and another step on the road to justice’',
    lede: 'AG Ellison issues statement upon Chauvin’s admission he deprived George Floyd and a juvenile of their civil rights',
},
{
	date: 'December 6, 2021',
    file: '2021/12/06_OpioidSettlement.asp',
    title: 'State, cities, counties reach historic agreement on allocating opioid settlement funds',
    lede: 'AG Ellison, Gov. Walz, and partners announce historic agreement to allocate settlement dollars from opioid companies: 75 percent to counties and cities, 25 percent to State',
},
{
	date: 'November 19, 2021',
    file: '2021/11/19_DACA.asp',
    title: 'Attorney General Ellison supports preserving, strengthening DACA',
    lede: 'Joins national coalition urging action to protect DACA benefits for 6,500 Minnesotans and extend them to 5,000 more',
},
{
	date: 'November 19, 2021',
    file: '2021/11/19_PandemicRelatedLawsuits.asp',
    title: 'Attorney General Ellison resolves two more pandemic-related lawsuits',
    lede: 'Shady’s to pay $30K for threatening to violate EO 20-56; Boardwalk pays $25K for violating EO 20-99, serves 30-day license suspension',
},
{
	date: 'November 18, 2021',
    file: '2021/11/18_Meta.asp',
    title: 'Attorney General Ellison joins nationwide investigation into Instagram’s impact on young people',
    lede: 'Broad group of attorneys general concerned for safety and well-being of children; examining potential violations of consumer-protection laws',
},
{
	date: 'November 16, 2021',
    file: '2021/11/16_Meldahl.asp',
    title: 'Attorney General Ellison secures victory against Minneapolis landlord’s ‘brazen and deplorable’ illegal practices',
    lede: 'Court orders Steven Meldahl to permanently stop deceiving tenants about lease terms, pay $133K fine and attorneys’ fees',
},
{
	date: 'October 25, 2021',
    file: '2021/10/25_SparboeFarms.asp',
    title: 'Attorney General Ellison reaches settlement in price-gouging lawsuit against Sparboe Farms',
    lede: 'Minnesota company agrees to donate more than 1M eggs to Minnesota nonprofits to feed hungry Minnesotans',
},
{
	date: 'October 19, 2021',
    file: '2021/10/19_AbortionBan.asp',
    title: 'Attorney General Ellison urges Supreme Court to halt unconstitutional Texas abortion ban',
    lede: 'Joins multistate amicus brief asking Court to vacate Fifth Circuit’s stay of order blocking enforcement of S.B. 8',
},
{
	date: 'September 30, 2021',
    file: '2021/09/30_MSBGlobe.asp',
    title: 'Starting today, former MSB/Globe students to finally receive nearly $24M in debt forgiveness, $16M in restitution for fraud, illegal lending',
    lede: 'Restitution checks to be issued starting today; now-final deal brings relief to 920 students hurt by fraud and more than 3,000 harmed by illegal lending at now-shuttered schools. Hotly contested case ends with final approval of bankruptcy court; resolves lawsuit AG’s office first brought in 2014.',
},
{
	date: 'September 23, 2021',
    file: '2021/09/23_NewcombCounseling.asp',
    title: 'Attorney General Ellison obtains guilty plea for over $1 million in Medicaid fraud',
    lede: 'Jonathan Newcomb and one other plead guilty; defrauding Medicaid program over $1 million by overbilling therapy services, aiding and abetting interpreters and transportation providers committing fraud, and billing for illegitimate services',
},
{
	date: 'September 23, 2021',
    file: '2021/09/23_APlaceToCallHome.asp',
    title: 'Attorney General Ellison secures $66,000 to benefit foster children and a permanent charitable-sector ban against directors of Minnesota nonprofit A Place to Call Home',
    lede: 'Settlements require Genevieve LaVoi to repay $66,000 in charitable assets she misused from foster care support charity A Place to Call Home, permanently ban LaVoi and former directors from operating a charity in Minnesota',
},
{
	date: 'September 20, 2021',
    file: '2021/09/20_RoeVWade.asp',
    title: 'Attorney General Ellison fights Mississippi’s attempt to overturn parts of <em>Roe v. Wade</em> at Supreme Court',
    lede: 'Joins coalition of 24 AGs in amicus brief to Court, which will hear oral argument on December 1',
},
{
	date: 'September 16, 2021',
    file: '2021/09/16_StubHub.asp',
    title: 'Attorney General Ellison announces nearly $2M settlement with StubHub',
    lede: 'Stubhub, Inc. agrees to honor its refund policies, will pay $1.87M in refunds to Minnesotans whose events were cancelled as a result of the COVID-19 pandemic',
},
{
	date: 'September 15, 2021',
    file: '2021/09/15_TexasAbortionBan.asp',
    title: 'Attorney General Ellison files support of DOJ’S lawsuit against Texas abortion ban',
    lede: 'Joins coalition of 24 AGs in amicus brief rejecting Texas law banning abortions after six weeks',
},
{
	date: 'September 9, 2021',
    file: '2021/09/09_Contributing2Combatants.asp',
    title: 'Attorney General Ellison wins $954,966 judgment and permanent ban against company Contributing 2 Combatants and its owner for bilking charitable donations intended for the military',
    lede: 'State’s lawsuit alleged that Jacob Choinski used his for-profit company, Contributing 2 Combatants, to solicit donations from Minnesotans door to door while posing as a charity and kept the donations to line his own pockets.',
},
{
	date: 'September 2, 2021',
    file: '2021/09/02_Potter.asp',
    title: 'Attorney General Ellison adds 1st-degree manslaughter charge against Kimberly Potter in death of Daunte Wright',
    lede: 'New charge added to original charge of 2nd-degree manslaughter in April 11 death in Brooklyn Park',
},
{
	date: 'September 2, 2021',
    file: '2021/09/02_PainFreePatriots.asp',
    title: 'Attorney General Ellison restructures charity and replaces its leadership following more than $2 million in self-dealing transactions',
    lede: 'Settlement overhauls the nonprofit’s governance after it funneled contributions to insider-owned businesses and amassed $700k in debts to its founder',
},
{
	date: 'August 27, 2021',
    file: '2021/08/27_Schierholz.asp',
    title: 'Attorney General Ellison sues manufactured home park owner in Marshall for neglecting park and charging illegal fees to residents',
    lede: 'Schierholz’s failure to maintain Broadmoor Valley manufactured home park has led to unsafe, unhealthy, and undignified living conditions for residents',
},
{
	date: 'August 18, 2021',
    file: '2021/08/17_PoshBridal.asp',
    title: 'Attorney General Ellison holds wedding dress shops accountable for breaking promises to Minnesota brides',
    lede: 'Hopkins wedding dress shops delivered wedding gowns late, sometimes within days of a wedding; will pay restitution for brides who suffered damages and change business practices to ensure future deliveries.',
},
{
	date: 'August 16, 2021',
    file: '2021/08/16_VoterDiscrimination.asp',
    title: 'Attorney General Ellison opposes Georgia’s discriminatory voting law in court',
    lede: 'Joins coalition of 22 AGs in pushing back on efforts to dismiss Biden Administration lawsuit against Georgia’s law; calls for lawsuit to move forward',
},
{
	date: 'August 10, 2021',
    file: '2021/08/10_Clement.asp',
    title: 'Attorney General’s office obtains guilty plea for $4M in Medicaid fraud',
    lede: 'Victor Clement, excluded from serving as provider for past fraud, hid behind shell companies to keep defrauding taxpayers; plea resolves case charged by Attorney General’s office in 2018',
},
{
	date: 'August 6, 2021',
    file: '2021/08/06_Bartmann.asp',
    title: 'Attorney General Ellison recovers back pay and overtime owed restaurant workers',
    lede: 'The Bartmann Companies pays employees more than $230K for back wages, overtime wages, and damages',
},
{
	date: 'August 3, 2021',
    file: '2021/08/03_CRU.asp',
    title: 'First-ever Conviction Review Unit begins accepting applications',
    lede: 'AG Ellison also announces hiring of CRU director',
},
{
	date: 'July 21, 2021',
    file: '2021/07/21_OpioidAgreement.asp',
    title: 'Attorney General Ellison, states reach $26B agreement with major opioid manufacturer, distributors',
    lede: 'Agreement to potentially bring more than $300M to Minnesota over 18 years for opioid epidemic treatment and prevention; also requires data transparency, industry changes to ensure crisis never happens again',
},
{
	date: 'July 8, 2021',
    file: '2021/07/08_Purdue.asp',
    title: 'AG Ellison announces resolution with Purdue Pharma and Sackler family for their role in the opioid crisis',
    lede: 'Resolution secures unprecedented public disclosure of more than 30 million documents, $4.3B from Sacklers; Minnesota’s share to exceed $50M over 9 years for prevention, treatment, and recovery',
},
{
	date: 'July 7, 2021',
    file: '2021/07/07_Google.asp',
    title: 'AG Ellison sues Google for antitrust violations over app store',
    lede: 'Joins bipartisan coalition of 37 AGs in alleging Google illegally maintains app store monopoly, unfairly edges out competition',
},
{
	date: 'July 7, 2021',
    file: '2021/07/07_PUC.asp',
    title: 'AG Ellison recommends PUC block gas companies from charging consumers $380M in winter-storm costs',
    lede: 'AG investigation uncovered utilities could have reduced gas purchases during Winter Storm Uri price spike but failed to do so; instead conducted business as usual as if there were no emergency',
},
{
	date: 'July 1, 2021',
    file: '2021/07/01_Budget.asp',
    title: 'Attorney General’s budget ‘a win for Minnesota families and consumers’',
    lede: 'AG Ellison praises 17 percent increase to base budget of Attorney General’s Office, including more resources to fight wage theft and antitrust behavior. Highlights Senate’s failure to fund much-needed criminal prosecutors to help fight violent crime in Greater Minnesota; AG ‘baffled why the Senate refuses to help us help prosecutors in Greater Minnesota make their communities safer’',
},
{
	date: 'July 1, 2021',
    file: '2021/07/01_PCMA.asp',
    title: 'Attorney General Ellison leads bipartisan coalition in support of regulating pharmacy benefit managers',
    lede: 'Leads 34 AGs in amicus brief in support of North Dakota laws, similar to Minnesota’s, regulating abusive behavior of PBMs',
},
{
	date: 'June 30, 2021',
    file: '2021/06/30_LovingCareHomeServices.asp',
    title: 'Attorney General Ellison recovers wages owed to low-wage home health and nanny employees',
    lede: 'Loving Care Home Services will pay 60 employees $39K in back wages and damages to resolve AG investigation',
},
{
	date: 'June 25, 2021',
    file: '2021/06/25_Chauvin.asp',
    title: '‘We must end the cycle of inaction and act for accountability and justice’',
    lede: '‘I hope this moment allows us to rededicate ourselves to change’: AG Ellison statement on sentencing of Derek Chauvin to term of 22.5 years for murder of George Floyd',
},
{
	date: 'June 17, 2021',
    file: '2021/06/17_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office Named a Top Workplace',
    lede: 'For the first time ever, the Minnesota Attorney General’s Office has been named a Top Workplace by the Star Tribune',
},
{
	date: 'June 11, 2021',
    file: '2021/06/11_HutchinsonHospital.asp',
    title: 'Attorney General settlement leads to further relief for Hutchinson Hospital patients',
    lede: 'Following settlement with AG’s Office, Hutchinson Hospital forgives $184K in patient debt, offers 40% discount for certain patients with outstanding bills',
},
{
	date: 'June 11, 2021',
    file: '2021/06/11_EvictionBan.asp',
    title: 'AG Ellison supports CDC pandemic eviction ban at Supreme Court',
    lede: 'Coalition of 23 AGs argue millions of evictions during ongoing pandemic would increase spread of COVID-19, threaten pandemic economic recovery',
},
{
	date: 'June 3, 2021',
    file: '2021/06/03_Fundraiser.asp',
    title: 'Attorney General Ellison files enforcement action against fundraiser who did not properly spend money raised in Philando Castile’s name',
    lede: 'Pamela Fergus raised $200K to relieve student lunch debt in Saint Paul schools, can only account for properly spending $80K AG’s office strongly encourages organizations raising funds by any means for any cause, including social justice, to know and comply with all fundraising rules.',
},
{
	date: 'May 25, 2021',
    file: '2021/05/25_GeorgeFloyd.asp',
    title: '‘We can break this cycle. The moment for making meaningful change is now.’',
    lede: '‘The other side of this mountain is better — not just for African Americans, but for everyone’: AG Ellison statement on one-year anniversary of the death of George Floyd',
},
{
	date: 'May 21, 2021',
    file: '2021/05/21_Potter.asp',
    title: 'Attorney General Ellison’s office to lead prosecution in death of Daunte Wright',
    lede: 'AG Ellison accepts request from Hennepin County Attorney Freeman after Washington County Attorney Orput returns the case',
},
{
	date: 'May 19, 2021',
    file: '2021/05/19_Wentzlaff.asp',
    title: 'Attorney General Ellison wins relief for tenants whose landlord falsely claimed she needed to move in in order to kick the tenants out',
    lede: 'Landlord to pay former tenants $3.5K, comply with executive orders protecting tenant rights in resolution of enforcement action for violating Executive Order 20-79',
},
{
	date: 'May 12, 2021',
    file: '2021/05/12_Brown.asp',
    title: 'Attorney General Ellison’s office wins big conviction for Medicaid fraud',
    lede: 'Remona Brown convicted on 14 counts of aiding and abetting theft by false representation; operated home care nursing agency that defrauded Medicaid of more than $1.8 million',
},
{
	date: 'May 7, 2021',
    file: '2021/05/07_Floyd.asp',
    title: '‘Federal prosecution for the violation of George Floyd’s civil rights is entirely appropriate’',
    lede: 'AG Ellison issues statement upon federal indictment of defendants Chauvin, Kueng, Lane, and Thao for allegedly violating civil rights of George Floyd',
},
{
	date: 'April 20, 2021',
    file: '2021/04/20_ChauvinVerdict.asp',
    title: '"Accountability...is the first step to justice"',
    lede: 'Attorney General Ellison’s remarks after the verdict in <em>State v. Derek Chauvin</em>, as prepared for delivery',
},
{
	date: 'April 20, 2021',
    file: '2021/04/20_StPatricksTavern.asp',
    title: 'Attorney General Ellison resolves lawsuit with bar and restaurant that violated executive orders',
    lede: 'St. Patrick’s Tavern & Restaurant will pay State $15,000, fully comply with executive orders',
},
{
	date: 'April 19, 2021',
    file: '2021/04/19_WalterMondale.asp',
    title: 'Walter Mondale was ‘the original People’s Lawyer’',
    lede: 'AG Ellison statement on the passing of Vice President Walter Mondale',
},
{
	date: 'April 13, 2021',
    file: '2021/04/13_CapitalStudentLoanCenter.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company in Minnesota',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State more than $18K to refund Minnesota customers',
},
{
	date: 'April 2, 2021',
    file: '2021/04/02_Yorkshire.asp',
    title: 'Attorney General Ellison holds assisted-living facility accountable for breaking promise to residents',
    lede: 'Edina assisted-living facility advertised monthly “Wellness Visits” that it didn’t provide; will pay $10K penalty and resumes providing services',
},
{
	date: 'April 1, 2021',
    file: '2021/04/01_FakeVaccinationCards.asp',
    title: 'Attorney General Ellison fights sales of fake vaccination cards',
    lede: 'Joins bipartisan group of 45 AGs in asking Twitter, eBay, Shopify to act immediately to stop sales of fraudulent CDC vaccination cards',
},
{
	date: 'April 1, 2021',
    file: '2021/04/01_ITT.asp',
    title: 'Attorney General Ellison continues defense of student-loan borrowers',
    lede: 'Seeks loan cancellation and payment refunds for defrauded ITT students; calls on U.S. Sec. of Education to address broader student-debt crisis',
},
{
	date: 'March 31, 2021',
    file: '2021/03/31_ExxonKochAPI.asp',
    title: 'Attorney General Ellison: ‘Climate damage and deception lawsuit filed in state court belongs in state court’',
    lede: 'Hails federal court decision to send lawsuit against ExxonMobil and others back to state court; court calls State’s suit a ‘well-pleaded consumer protection action’ and defendants’ attacks ‘a caricature’',
},
{
	date: 'March 25, 2021',
    file: '2021/03/25_Contributing2Combatants.asp',
    title: 'Attorney General Ellison sues company for posing as charity helping servicemembers, funneling donations to owner',
    lede: 'Alleges Jacob Choinski used Contributing 2 Combatants to solicit donations from Minnesotans door to door while posing as a charity — and kept every dollar to line his own pockets',
},
{
	date: 'March 24, 2021',
    file: '2021/03/24_FoodAssistance.asp',
    title: 'AG Ellison applauds end of lawsuit challenging Trump administration’s food-assistance cuts; urges Congress to expand the program',
    lede: 'Biden Administration agrees to dismiss appeal of decision that Trump SNAP rule was arbitrary, poorly reasoned, and contrary to Congress’s intent',
},
{
	date: 'March 23, 2021',
    file: '2021/03/23_BostonScientific.asp',
    title: 'Attorney General Ellison announces nearly $190 million multistate settlement with Boston Scientific',
    lede: 'Holds Boston Scientific accountable for misrepresenting risks of its surgical mesh devices, in second settlement of its kind; company to pay Minnesota more than $3.3 million, agrees to significant reforms',
},
{
	date: 'March 22, 2021',
    file: '2021/03/22_HF844.asp',
    title: 'AG Ellison: ‘Long past time to protect Minnesotans from emergency profiteering’',
    lede: 'Applauds House passage of HF844 banning price-gouging in emergencies, urges passage in Senate; bill gives enforcement authority to Attorney General’s Office',
},
{
	date: 'March 19, 2021',
    file: '2021/03/19_Chauvin.asp',
    title: 'AG Ellison: ‘State has been and is ready to proceed to trial on schedule’',
    lede: 'Twelve jurors selected week ahead of schedule, all screened for impartiality; State looks forward to presenting case ‘to a fair and impartial jury in Hennepin County’',
},
{
	date: 'March 18, 2021',
    file: '2021/03/18_Taskforce.asp',
    title: 'Attorney General Keith Ellison joins nationwide task force on pharmaceutical mergers',
    lede: 'Lowering cost of prescription drugs and ensuring fair marketplace among AG Ellison’s top priorities; new task force meets recommendation of AG’s report on report on drug prices',
},
{
	date: 'March 17, 2021',
    file: '2021/03/17_TobaccoSettlement.asp',
    title: 'Attorney General Ellison enforcement of Tobacco Settlement wins $81 million for State',
    lede: 'R.J. Reynolds Tobacco Company and ITG Brands to pay $81 million in back settlement payments; State to collect $10 million or more annually in future payments',
},
{
	date: 'March 16, 2021',
    file: '2021/03/16_MSBGlobe.asp',
    title: 'Attorney General Ellison wins full financial relief for former MSB/Globe University students as part of tentative deal reached with schools’ owners and Department of Education',
    lede: '$23.1 million in debt to be forgiven for 920 students, $15.6 million in additional compensation to be paid for students defrauded by schools’ ‘criminal justice’ program',
},
{
	date: 'March 16, 2021',
    file: '2021/03/16_Purdue.asp',
    title: 'Attorney General Ellison ‘disappointed’ in Purdue bankruptcy plan',
    lede: '“I am disappointed in this plan. While it contains improvements over the proposal that Purdue announced and we rejected in September 2019, it falls short of the accountability that families and survivors deserve.”',
},
{
	date: 'March 15, 2021',
    file: '2021/03/15_InsulinAffordabilityAct.asp',
    title: '“No one should have to choose between affording their lives and affording to live”: AG Ellison, Governor Walz celebrate dismissal of challenge to Alec Smith Insulin Affordability Act',
    lede: '',
},
{
	date: 'March 12, 2021',
    file: '2021/03/12_EO21-11.asp',
    title: '‘Turn of the dial is good news, but we cannot let our guard down’: AG Ellison on new executive order',
    lede: '',
},
{
	date: 'March 11, 2021',
    file: '2021/03/11_AMCA.asp',
    title: 'Attorney General Keith Ellison announces multistate settlement with American Medical Collection Agency over 2019 data breach',
    lede: '',
},
{
	date: 'March 11, 2021',
    file: '2021/03/11_Chauvin.asp',
    title: 'Court reinstates 3rd-degree murder charge against Derek Chauvin',
    lede: 'Comes in wake of March 5 Court of Appeals ruling and Supreme Court denial yesterday of Chauvin’s petition to review Court of Appeals ruling',
},
{
	date: 'March 10, 2021',
    file: '2021/03/10_HookahHideout.asp',
    title: 'Attorney General Ellison resolves lawsuit with Hookah Bar that violated executive orders',
    lede: 'The Hookah Hideout will pay State $4,000, fully comply with executive orders',
},
{
	date: 'March 8, 2021',
    file: '2021/03/08_PlainviewWellness.asp',
    title: 'Attorney General Ellison settles with gym that violated executive orders',
    lede: 'Plainview Wellness Center will pay State $5,000, fully comply with executive orders',
},
{
	date: 'March 8, 2021',
    file: '2021/03/08_Chauvin.asp',
    title: 'State files motion to ensure district court has jurisdiction to hear Derek Chauvin’s trial',
    lede: 'Comes in wake of district court’s intention to move forward with jury selection despite Chauvin’s decision to appeal ruling from last Friday',
},
{
	date: 'March 5, 2021',
    file: '2021/03/05_Chauvin.asp',
    title: 'AG Ellison: 3rd-degree murder charge ‘reflects the gravity of the allegations’ against Chauvin',
    lede: 'Minnesota Attorney General Keith Ellison issued the following statement in response to today’s Minnesota Court of Appeals ruling that the district court erred in not granting the State’s motion to reinstate the charge of 3rd-degree murder against Derek Chauvin in the death of George Floyd',
},
{
	date: 'February 25, 2021',
    file: '2021/02/25_PohlandFamilyFoundation.asp',
    title: 'Pohlad Family Foundation to fund recommendations for reducing police-involved deadly-force encounters',
    lede: 'One year after release of recommendations, working group co-led by AG and DPS commissioner meets again to review progress, investments',
},
{
	date: 'February 19, 2021',
    file: '2021/02/19_StudentLoanDebt.asp',
    title: 'Attorney General Ellison calls for cancellation of federal student-loan debt',
    lede: 'Joins multistate coalition in support of congressional resolutions calling for the cancellation of up to $50K in debt per student borrower - 775K Minnesotans carrying average $37.5K in student-loan debt; Minnesota graduates’ average debt load 11th-highest in country',
},
{
	date: 'February 17, 2021',
    file: '2021/02/17_Wentzlaff.asp',
    title: 'Attorney General Ellison sues another landlord for illegally forcing tenant to vacate during COVID-19 pandemic',
    lede: 'Files enforcement action against Dakota County landlord who forced her tenants out of their home so that she could sell it, in violation of Executive Order 20-79',
},
{
	date: 'February 4, 2021',
    file: '2021/02/04_McKinsey.asp',
    title: 'Attorney General Ellison joins $573M multistate settlement with McKinsey & Company',
    lede: 'Resolves claims against consulting firm for its role in ‘turbocharging’ opioid epidemic with Purdue Pharma; Minnesota to receive $8M for abatement in first opioid settlement to result in substantial payment; McKinsey also required to make documents public',
},
{
	date: 'January 29, 2021',
    file: '2021/01/29_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of Executive Orders: January 29, 2021 Update',
    lede: '',
},
{
	date: 'January 29, 2021',
    file: '2021/01/29_PHH.asp',
    title: 'Attorney General Ellison co-leads bipartisan coalition fighting for homeowners',
    lede: '33 AGs join to oppose settlement that is clear windfall to mortgage servicer; affects more than 17,000 Minnesota homeowners',
},
{
	date: 'January 28, 2021',
    file: '2021/01/28_Interchange.asp',
    title: 'Court orders issues $9K fine against The Interchange in Albert Lea',
    lede: 'Court also issues temporary injunction that requires The Interchange to fully comply with executive orders for the duration of the State’s lawsuit',
},
{
	date: 'January 27, 2021',
    file: '2021/01/27_MedicaidFraudScheme.asp',
    title: 'Attorney General Ellison charges eight in Medicaid fraud scheme',
    lede: 'Files 46 felony theft charges totaling $860K in fraud',
},
{
	date: 'January 26, 2021',
    file: '2021/01/26_WomensEconomicSecurityTaskForce.asp',
    title: 'Attorney General Ellison selects advocates, researchers, legislators to serve on Women’s Economic Security Task Force',
    lede: 'Names Lt. Gov. Flanagan and others as <em>ad hoc</em> members',
},
{
	date: 'January 22, 2021',
    file: '2021/01/22_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of Executive Orders: January 22, 2021 Update',
    lede: '',
},
{
	date: 'January 22, 2021',
    file: '2021/01/22_RestaurantSettlements.asp',
    title: 'State settles with restaurants that violated executive orders',
    lede: 'Cork in Anoka will fully comply with executive orders, agrees to 15-day liquor license suspension; Neighbors on the Rum in Princeton also to fully comply with executive orders',
},
{
	date: 'January 21, 2021',
    file: '2021/01/21_AdvisoryBoard.asp',
    title: 'Attorney General Ellison announces Conviction Review Unit Advisory Board',
    lede: '16 members include former Minnesota Supreme Court Justice, national criminal-justice experts, Hennepin and Ramsey County Attorneys, community activists',
},
{
	date: 'January 20, 2021',
    file: '2021/01/20_Inauguration.asp',
    title: 'Attorney General Ellison: ‘Competent, compassionate, moral people are now leading our country’ on ‘a new day’',
    lede: 'Country now has ‘opportunities to move forward now in brand-new ways’ on climate change, immigration, healthcare, racial and economic justice. ‘Minnesotans now have partners in the White House who support and protect them’ in affording their lives, living with dignity and respect.',
},
{
	date: 'January 15, 2021',
    file: '2021/01/15_Voyageurs.asp',
    title: 'Attorney General Ellison secures full refunds for Minnesota students and families harmed by canceled trips',
    lede: 'Voyageurs International will pay 344 Minnesota high school students and their families $665,000 to reimburse for questionable “cancellation fees”',
},
{
	date: 'January 14, 2021',
    file: '2021/01/14_DocumentAssistCenter.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company in Minnesota',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State over $11K to refund Minnesota customers',
},
{
	date: 'January 12, 2021',
    file: '2021/01/12_HealingHeroesNetwork.asp',
    title: 'Attorney General Ellison bans alleged sham veterans’ charity from soliciting in Minnesota',
    lede: 'Settlement requires defendants Healing Heroes Network and Hero Giveaways to permanently cease all charitable solicitations; requires individual defendants to pay $95K to be donated to veterans’ charity',
},
{
	date: 'January 12, 2021',
    file: '2021/01/12_Cornerstone.asp',
    title: 'Monticello restaurant to give up profits, fully comply with executive orders in settlement with Attorney General’s office',
    lede: 'Cornerstone Café will pay State $10,000, giving up the profits it earned while operating in violation of executive orders',
},
{
	date: 'January 8, 2021',
    file: '2021/01/08_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of Executive Orders: January 8, 2021 Update',
    lede: '',
},
{
	date: 'January 8, 2021',
    file: '2021/01/08_Interchange.asp',
    title: 'Court finds Albert Lea establishment in contempt, imposes $3K/day fine',
    lede: 'Finds The Interchange violated the Court’s temporary restraining order by offering indoor, on-premises dining to the public; will issue written order later',
},
{
	date: 'January 7, 2021',
    file: '2021/01/07_AlibiDrinkery.asp',
    title: 'Court finds Alibi Drinkery in contempt, imposes $3K/day fine',
    lede: 'Finds Alibi ‘intentionally and purposefully is violating’ temporary injunction, ‘willfully disobeyed’ and ‘is flagrantly in violation’ of court’s orders. Court: ‘Health and welfare of the public are at risk and are being irreparably harmed’ by Alibi’s behavior',
},
{
	date: 'January 5, 2021',
    file: '2021/01/05_PredatoryLenders.asp',
    title: 'Attorney General Ellison sues to block Trump Administration’s attempts to shield predatory lenders from state usury laws',
    lede: 'AG Ellison co-led opposition to new banking rule that would preclude states from holding lenders accountable when they make loans at exorbitant interest rates through “rent-a-bank” schemes; now brings suit to prevent rule’s implementation',
},
];