var pr2023 = [
{
	date: 'December 28, 2023',
    file: '2023/12/28_Progress.asp',
    title: 'Court requires landlord to stop exposing tenants to lead paint in rental homes',
    lede: 'Attorney General Ellison wins motion against landlord Progress Residential in ongoing lawsuit; court orders Progress to comply with state and federal lead-paint hazard laws',
},
{
	date: 'December 27, 2023',
    file: '2023/12/27_Cargill.asp',
    title: 'Attorney General Ellison urges Supreme Court to uphold federal rule banning bump stocks',
    lede: 'Joins coalition of 23 AGs in defending bump stock rule issued after 2017 Las Vegas massacre',
},
{
	date: 'December 21, 2023',
    file: '2023/12/21_StudentLoanDebt.asp',
    title: 'Attorney General Ellison shuts down two more deceptive student-loan debt-relief companies in Minnesota',
    lede: 'The two companies will pay State $56K to refund customers who fell victim to their fraudulent forgiveness schemes',
},
{
	date: 'December 20, 2023',
    file: '2023/12/20_KidsWishNetwork.asp',
    title: 'Attorney General Ellison bans Florida-based charity Kids Wish Network, Inc. from soliciting donations from Minnesotans for five years',
    lede: '',
},
{
	date: 'December 19, 2023',
    file: '2023/12/19_PMC.asp',
    title: 'Attorney General Ellison applauds holding contractor accountable for wage theft',
    lede: 'DLI today filed action against PMC and Advantage to recover $2.4 million in stolen wages and damages',
},
{
	date: 'December 19, 2023',
    file: '2023/12/19_Google.asp',
    title: 'Attorney General Ellison reaches $700M settlement with Google over Play Store misconduct',
    lede: 'Resolves lawsuit first filed in 2021; most of the settlement to go directly into consumers’ pockets',
},
{
	date: 'December 14, 2023',
    file: '2023/12/14_RestoreTheVote.asp',
    title: 'District court rejects “fundamentally flawed” effort to overturn Restore the Vote Act',
    lede: 'Court dismisses challenge to the voting rights of 55,000 Minnesotans',
},
{
	date: 'December 14, 2023',
    file: '2023/12/14_ESG.asp',
    title: 'Attorney General Ellison Calls on Congress to Defend Consideration of ESG Factors',
    lede: 'A coalition of 18 attorneys general ask Congress to not prohibit fiduciaries from considering relevant ESG factors',
},
{
	date: 'December 13, 2023',
    file: '2023/12/13_AbortionBan.asp',
    title: 'Attorney General Ellison joins multistate coalition condemning Texas Supreme Court decision enforcing the state’s dangerous abortion ban',
    lede: '',
},
{
	date: 'December 12, 2023',
    file: '2023/12/12_AcademicFinancialAdvisors.asp',
    title: 'Attorney General Ellison shuts down another deceptive student-loan debt-relief company in Minnesota',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State over $179K to refund Minnesota customers',
},
{
	date: 'December 8, 2023',
    file: '2023/12/08_GatewaySTEMAcademy.asp',
    title: 'Attorney General Ellison reaches settlement with charter school over misuse of funds by three former leaders',
    lede: 'State alleged self-dealing by former Executive Director Abdiaziz Shafii Farah and governance shortcomings by previous boards of directors',
},
{
	date: 'December 7, 2023',
    file: '2023/12/07_MedicaidFraud.asp',
    title: 'Attorney General Ellison charges three in largest-ever Medicaid fraud prosecution by AGO',
    lede: 'Three defendants arrested, charged with 24 counts totaling $11 million in fraud',
},
{
	date: 'December 1, 2023',
    file: '2023/12/01_Minnesota100Club.asp',
    title: 'Attorney General Ellison secures Assurance strengthening governance of first-responder charity',
    lede: 'Charity engaged in conflicted transactions and other governance violations',
},
{
	date: 'December 1, 2023',
    file: '2023/12/01_RoeVCritchfield.asp',
    title: 'Attorney General Ellison joins 21 attorneys general arguing to block Idaho transgender bathroom law',
    lede: 'Law would bar transgender youth from bathrooms, changing rooms at school',
},
{
	date: 'November 20, 2023',
    file: '2023/11/20_Prehired.asp',
    title: 'Attorney General Ellison secures relief for students victimized by predatory for-profit educational provider',
    lede: 'Prehired will void all outstanding income-share agreements, refund harmed borrowers, and permanently cease operations; Settlement secures $31 million in relief nationwide, including debt relief and $80K in refunds for Minnesota consumers',
},
{
	date: 'November 9, 2023',
    file: '2023/11/09_IPG.asp',
    title: 'Attorney General Ellison reaches agreement with landlord to stop evicting tenants for unpaid utility charges',
    lede: 'IPG also agrees to stop charging many tenants for gas and steam heat',
},
{
	date: 'November 8, 2023',
    file: '2023/11/08_Network46.asp',
    title: 'Attorney General Ellison shuts down another fraudulent student-loan debt-relief company in Minnesota',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State over $59K to refund Minnesota customers',
},
{
	date: 'November 6, 2023',
    file: '2023/11/06_AgriStats.asp',
    title: 'Minnesota joins United States’ antitrust lawsuit against Agri Stats for operating extensive information exchanges among meat processors',
    lede: 'Lawsuit alleges that Agri Stats helps big meat processors coordinate to artificially inflate the price of food',
},
{
	date: 'November 6, 2023',
    file: '2023/11/06_SocialMedia.asp',
    title: 'Attorney General Ellison invites Minnesotans to share stories on social media use and addiction among children and teenagers',
    lede: 'Minnesotans can share their stories at <a href="/social-media/">www.ag.state.mn.us/social-media</a>',
},
{
	date: 'November 2, 2023',
    file: '2023/11/02_RestoreTheVoteLaw.asp',
    title: 'Court of Appeals blocks Mille Lacs County judge from undermining Restore the Vote law',
    lede: 'AG Ellison: Decision “is a victory for our democracy and our entire judicial system”',
},
{
	date: 'November 1, 2023',
    file: '2023/11/01_IslandMountain.asp',
    title: 'AG Ellison sues to stop predatory internet lending in Minnesota',
    lede: 'Brings federal lawsuit to shut down illegal lending operation by jointly owned online businesses Bright Lending, Green Trust Cash, and Target Cash Now',
},
{
	date: 'October 24, 2023',
    file: '2023/10/24_Meta.asp',
    title: 'Bipartisan coalition of attorneys general file lawsuits against Meta for harming youth mental health through its social media platforms',
    lede: 'AG Ellison joins 33 bipartisan attorneys general in federal lawsuit; eight more sue in state courts',
},
{
	date: 'October 23, 2023',
    file: '2023/10/23_ACI.asp',
    title: 'Attorney General Ellison reaches settlement over $2.3B in attempted unauthorized withdrawals',
    lede: 'ACI Worldwide will pay $10M total, with Minnesota receiving $119K',
},
{
	date: 'October 23, 2023',
    file: '2023/10/23_Inmediata.asp',
    title: 'Attorney General Ellison reaches settlement in data breach impacting 113K Minnesotans',
    lede: 'In bipartisan national settlement, health care clearinghouse Inmediata to overhaul data security and breach notification after 2019 data breach made sensitive medical information of 1.5 million Americans accessible via online search engines',
},
{
	date: 'October 20, 2023',
    file: '2023/10/20_RightToVote.asp',
    title: 'Attorney General Ellison intervenes to stop Mille Lacs County judge from interfering with legal right to vote, Secretary Simon stands in support',
    lede: 'Ellison, Simon encourage all eligible Minnesotans to exercise their right to vote, including formerly incarcerated people',
},
{
	date: 'October 19, 2023',
    file: '2023/10/19_IPG.asp',
    title: 'Attorney General Ellison files emergency motion, lawsuit to protect tenants from unlawful evictions and illegal utility charges',
    lede: 'Requests court stop Investment Property Group from charging its tenants illegal gas utility fees imposed in the middle of their leases, immediately halt eviction of 21 tenants on the basis of non-payment of the illegal fees',
},
{
	date: 'October 18, 2023',
    file: '2023/10/18_FoodFraud.asp',
    title: 'Attorney General Ellison files 23 lawsuits to shut down fraudulent nonprofits',
    lede: 'Lawsuits allege that sham nonprofits were created or revived to act as fraudulent Federal Child Nutrition Program “sites,” seek dissolution',
},
{
	date: 'October 17, 2023',
    file: '2023/10/17_RightToVote.asp',
    title: 'Joint statement by Secretary Simon and Attorney General Ellison on recent attempt to undermine Restore the Vote Law',
    lede: '',
},
{
	date: 'October 11, 2023',
    file: '2023/10/11_Docupros.asp',
    title: 'Attorney General Ellison shuts down another fraudulent student-loan debt-settlement company',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State over $17K to refund Minnesota customers',
},
{
	date: 'October 5, 2023',
    file: '2023/10/05_Blackbaud.asp',
    title: 'Attorney General Ellison reaches settlement with Blackbaud for data breach',
    lede: 'Blackbaud to overhaul data security and breach-notification practices after 2020 breach that exposed personal information of millions of Americans',
},
{
	date: 'October 4, 2023',
    file: '2023/10/04_KitchenKingz.asp',
    title: 'Attorney General Ellison shuts down fraudulent recycling nonprofit',
    lede: 'Investigation uncovers president used funds for personal benefit; settlement requires him to pay money back, permanently bans him from operating charity',
},
{
	date: 'October 3, 2023',
    file: '2023/10/03_HealthcareMergers.asp',
    title: 'Attorney General Ellison reviewing two proposed healthcare mergers, seeks community input',
    lede: 'Evaluating mergers between Essentia Health and Marshfield Clinic Health System and between St. Luke’s Duluth and Aspirus Health under state and federal law, including Minnesota’s new health care entity transaction Law',
},
{
	date: 'September 27, 2023',
    file: '2023/09/27_Gender-Affirming-Care.asp',
    title: 'Attorney General Ellison once again defends transgender youth in court',
    lede: 'Joins 20 AGs in opposing Indiana law barring lifesaving gender-affirming care for youth; follows prior support for transgender youth in Kentucky and Tennessee',
},
{
	date: 'September 26, 2023',
    file: '2023/09/26_Amazon.asp',
    title: 'Attorney General Ellison joins FTC and bipartisan coalition of state AGs to sue Amazon for illegally maintaining monopolies in online retail',
    lede: 'Lawsuit alleges that Amazon blocks competition in violation of the antitrust laws, allowing it to inflate prices, degrade quality, and stifle innovation for consumers and businesses',
},
{
	date: 'September 22, 2023',
    file: '2023/09/22_SpecialAchievementAward.asp',
    title: 'Attorney General Ellison to accept award from International Association of Prosecutors for prosecution of murder of George Floyd',
    lede: 'IAP bestowing Special Achievement Award on entire prosecution team; award given to prosecutors who show special dedication to their work in the face of significant adversity',
},
{
	date: 'September 20, 2023',
    file: '2023/09/20_UseOfForce.asp',
    title: 'Attorney General Ellison further clarifies law on use of force in schools',
    lede: 'In supplemented opinion to MDE Commissioner, AG Ellison clarifies that new amendments do not affect definition of ‘reasonable force’ that may be used when carrying out arrests and other lawful duties',
},
{
	date: 'September 12, 2023',
    file: '2023/09/12_Johnson.asp',
    title: 'Jacob Johnson sentenced to 40 years for murder of Ricky Balsimo',
    lede: 'Johnson convicted in August of 2nd-degree murder; received statutory maximum sentence based on aggravating factors',
},
{
	date: 'September 12, 2023',
    file: '2023/09/12_Tempoe.asp',
    title: 'Attorney General Ellison reaches $35M settlement with leasing company Tempoe, LLC',
    lede: 'Company ‘operated like a predatory payday lender’: marketing and sales practices misled consumers seeking credit for purchases into entering into complicated lease agreements, often resulting in consumers paying 2-3 times more',
},
{
	date: 'September 7, 2023',
    file: '2023/09/07_WorkerTaskforce.asp',
    title: 'Attorney General Ellison announces members of Worker Misclassification Task Force',
    lede: 'Selects advocates, researchers, policymakers to serve along with legislators and representatives of state agencies; first meeting of Task Force on September 13, Rep. Greenman to co-chair',
},
{
	date: 'September 6, 2023',
    file: '2023/09/06_StudentLoanDebt.asp',
    title: 'Attorney General Ellison opens investigation into 52 student-loan debt-relief companies',
    lede: 'Suspected of violating consumer-protection laws and not registering as required by law. AG also issues new guidance about upcoming return to repayment for federal student-loan borrowers, warns of ‘repayment’ scams.',
},
{
	date: 'September 5, 2023',
    file: '2023/09/05_Amgen.asp',
    title: 'Attorney General Ellison reaches agreement to prevent pharmaceutical giant from abusing market power',
    lede: 'Joins FTC and 5 other states in resolving lawsuit against Amgen—settlement allows Amgen to acquire Horizon Therapeutics as long as Amgen does not use its market power to give Horizon’s drugs an unfair leg-up',
},
{
	date: 'August 31, 2023',
    file: '2023/08/31_E-Cigarettes.asp',
    title: 'Attorney General Ellison pushes FDA to protect kids from e-cigarette addiction',
    lede: 'Joins bipartisan letter of 33 attorneys general in letter urging FDA and Center for Tobacco Products to limit flavors, reduce nicotine levels, restrict marketing to youth',
},
{
	date: 'August 29, 2023',
    file: '2023/08/29_MNProfessional.asp',
    title: 'Attorney General’s Office charges five with $9.5M in Medicaid fraud',
    lede: 'Alleges owners and management of MN Professional PCA agency billed for services not performed, services not supervised by qualified professional',
},
{
	date: 'August 28, 2023',
    file: '2023/08/28_MarchOnWashington.asp',
    title: 'Attorney General Ellison: ‘Those of us who believe in liberty and justice for all can never stop’',
    lede: 'Issues statement on 60th anniversary of historic March on Washington: the ‘victories for progress’ that the March pushed forward are ‘under attack 60 years later’',
},
{
	date: 'August 23, 2023',
    file: '2023/08/23_Hudson.asp',
    title: '‘Natalie Hudson is a phenomenally talented jurist…She will serve the state of Minnesota very well’',
    lede: 'AG Ellison hails selection of Natalie Hudson as Minnesota Supreme Court chief justice, first person of color to lead court and Minnesota’s Judicial Branch',
},
{
	date: 'August 22, 2023',
    file: '2023/08/22_Opinion_SchoolDiscipline.asp',
    title: 'Attorney General Ellison clarifies law on use of force in schools',
    lede: 'Issues opinion to MDE Commissioner: recent amendments to school discipline laws do not preclude use of restraint to prevent death, harm to others, or self-harm',
},
{
	date: 'August 22, 2023',
    file: '2023/08/22_DeputyAG.asp',
    title: 'Attorney General Ellison names Dana Mitchell as Deputy Attorney General',
    lede: 'Current AGO Public Safety division manager is 25-year veteran of legal, public, community service',
},
{
	date: 'August 18, 2023',
    file: '2023/08/18_MedicalBilling.asp',
    title: 'Attorney General Ellison announces new steps in renewed focus on medical billing',
    lede: 'Will hold public listening sessions in Saint Paul on August 23 and Rochester on September 13; web form for consumers to submit stories and experiences now live',
},
{
	date: 'August 16, 2023',
    file: '2023/08/16_KiaHyundai.asp',
    title: 'Federal court tentatively declines to approve agreement in Hyundai/Kia private consumer class-action settlement',
    lede: 'Court’s refusal to approve agreement comes shortly after AG Ellison led letter to court recommending it strengthen settlement to require Hyundai/Kia recall or buy back theft-prone vehicles',
},
{
	date: 'August 16, 2023',
    file: '2023/08/16_Tinklenberg.asp',
    title: 'Attorney General’s Office secures conviction in Kanabec County murder case',
    lede: 'Dustin Tinklenberg pleads guilty to of 2nd-degree intentional murder of his 93-year-old grandmother Stella Anderson in September 2022',
},
{
	date: 'August 14, 2023',
    file: '2023/08/14_KiaHyundai.asp',
    title: 'Attorney General Ellison urges court to strengthen Hyundai/Kia private consumer class-action settlement',
    lede: 'Leads coalition of 7 AGs in advocating that settlement require Hyundai and Kia to recall and install industry-standard, anti-theft technology in their theft-prone vehicles',
},
{
	date: 'August 11, 2023',
    file: '2023/08/11_Healthcare.asp',
    title: 'Attorney General Ellison opposes laws harming transgender youth in Kentucky and Tennessee',
    lede: 'Joins coalition of 20 AGs in supporting lawsuits to block harmful new laws that limit access to lifesaving healthcare for trans youth',
},
{
	date: 'August 2, 2023',
    file: '2023/08/02_Johnson.asp',
    title: 'Attorney General’s Office secures another conviction in Cook County murder case',
    lede: 'Jacob Johnson convicted by jury of two counts of 2nd-degree murder in June 2021 murder of Ricky Balsimo',
},
{
	date: 'July 27, 2023',
    file: '2023/07/27_3MSettlement.asp',
    title: 'Attorney General Ellison files opposition to some terms of national 3M class-action settlement',
    lede: 'Joins bipartisan coalition of 23 attorneys general in objecting to terms of settlement that could place 3M’s liability for PFAS on public water providers, do not disclose how much individual providers would receive, and provide only 60 days for providers to decide whether to join settlement',
},
{
	date: 'July 21, 2023',
    file: '2023/07/21_Silgjord.asp',
    title: 'Attorney General Ellison’s office charges former police officer with financially exploiting vulnerable adult',
    lede: 'Lays two charges of felony and gross misdemeanor financial exploitation of vulnerable adult, one charge of felony attempted theft by swindle; alleges defendant attempted to inherit victim’s entire estate despite victim having surviving family',
},
{
	date: 'July 20, 2023',
    file: '2023/07/20_AgricultureCompetition.asp',
    title: 'Attorney General Ellison joins new partnership with USDA to enhance competition, protect consumers and producers in food and agriculture markets',
    lede: 'New Agriculture Competition Partnership comes in response to bipartisan effort AG Ellison led seeking ways to collaborate with USDA on greater enforcement in agriculture markets to ensure fairness and integrity for Minnesota farmers, ranchers, and consumers',
},
{
	date: 'July 18, 2023',
    file: '2023/07/18_Robocalls.asp',
    title: 'Minnesota joins federal and state law enforcement partners in new crackdown on illegal robocalls',
    lede: 'New enforcement sweep targets those who distributed or facilitated billions of illegal calls',
},
{
	date: 'July 13, 2023',
    file: '2023/07/13_Prehired.asp',
    title: 'Attorney General Ellison sues for-profit educational provider for illegal student lending practices',
    lede: 'Program made false promises about jobs and income and made illegal “income-share” loans',
},
{
	date: 'July 6, 2023',
    file: '2023/07/06_Taskforce.asp',
    title: 'Attorney General Ellison forms Task Force on Worker Misclassification',
    lede: 'Applications accepted until early August through online Open Appointments process',
},
{
	date: 'June 29, 2023',
    file: '2023/06/29_GoogleAndroid.asp',
    title: 'Attorney General Ellison urges Google to resolve issue causing surge of inadvertent 911 calls',
    lede: 'Recent Android software update causes many hundreds of inadvertent 911 calls per day, creates tremendous drain on emergency-response resources across Minnesota',
},
{
	date: 'June 27, 2023',
    file: '2023/06/27_FleetFarm.asp',
    title: 'Court upholds entirety of Attorney General Ellison’s lawsuit against Fleet Farm',
    lede: 'Federal court denies Fleet Farm’s motion to dismiss, finds State’s claims can proceed despite federal law shielding the firearms industry',
},
{
	date: 'June 23, 2023',
    file: '2023/06/23_Amgen.asp',
    title: 'Attorney General Ellison Joins Landmark FTC Lawsuit Challenging ‘Dangerous’ Pharmaceutical Merger',
    lede: 'Lawsuit seeks to block proposed acquisition by Amgen, one of world’s largest drug companies, in FTC’s first ever challenge of a pharmaceutical merger',
},
{
	date: 'June 20, 2023',
    file: '2023/06/20_Target.asp',
    title: 'Attorney General Ellison offers Target help in combatting anti-LGBTQ+ harassment and violence',
    lede: 'Co-leads letter of 15 AGs expressing concern with Target’s decision to pull some Pride merchandise from stores: concerned it sends message that ‘those who engage in hateful and disruptive conduct … have the power to determine when LGBTQIA+ consumers will feel comfortable in Target stores — or anywhere in society’',
},
{
	date: 'June 18, 2023',
    file: '2023/06/18_TicketScams.asp',
    title: 'Attorney General Ellison warns Minnesota ‘Swifties’ of potential scams related to Taylor Swift ‘Eras’ Tour tickets',
    lede: 'Recommends important rules to follow to avoid online ticket scams',
},
{
	date: 'June 16, 2023',
    file: '2023/06/16_MPD.asp',
    title: 'Federal and State investigations of MPD find ‘very serious and systemic problems that we have to fix’',
    lede: 'AG Ellison’s statement on results of DOJ investigation into Minneapolis Police Department',
},
{
	date: 'June 16, 2023',
    file: '2023/06/16_AdoreMe.asp',
    title: 'Clothing retailer ‘Adore Me’ to refund consumers for recurring negative-option membership',
    lede: 'Company to pay refunds to customers, make cancellations easier, cease deceptive practices',
},	
{
	date: 'June 15, 2023',
    file: '2023/06/15_Gildea.asp',
    title: 'Chief Justice Gildea served our state nobly and honorably for many years',
    lede: 'AG Ellison issues statement reacting Minnesota Supreme Court Chief Justice Lorie Gildea’s retirement',
},
{
	date: 'June 14, 2023',
    file: '2023/06/14_OMara.asp',
    title: 'Attorney General Ellison stops physician from deceptively soliciting donations',
    lede: 'Agreement bans Excelsior-based wellness physician Sean O’Mara from soliciting for a nonexistent charity, falsely claiming charitability and tax-deductibility, and engaging in other deceptive tactics',
},
{
	date: 'June 13, 2023',
    file: '2023/06/13_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office named a Top Workplace for third consecutive year',
    lede: 'Ranked #10 among midsize organizations; only government entity among 200 honored',
},
{
	date: 'June 13, 2023',
    file: '2023/06/13_DeputyAG.asp',
    title: 'Deputy Attorney General Luz María Frías to retire after 30-year career in public service',
    lede: 'AG Ellison: ‘Luz Frías is one of a kind … always leading with community’',
},
{
	date: 'June 10, 2023',
    file: '2023/06/10_CivilRightsDivision.asp',
    title: 'Attorney General Ellison expands consumer-protection work with new Civil Rights Division',
    lede: 'Civil Rights Division to protect consumers from discrimination in buying products or services, investigate fraudulent conduct that disproportionately harms consumers on the basis of race, religion, or other protected statuses',
},
{
	date: 'June 9, 2023',
    file: '2023/06/09_OpioidSettlement.asp',
    title: 'Minnesota to receive $208M more in settlements with opioid companies',
    lede: 'Part of $17.3B in agreements with manufacturers Teva and Allergan and pharmacies CVS and Walgreens',
},
{
	date: 'June 6, 2023',
    file: '2023/06/06_RecyclingBags.asp',
    title: 'Attorney General Ellison sues Reynolds, Walmart for defrauding consumers, deceptively marketing ‘recycling’ bags that are not recyclable',
    lede: 'Recyclable materials in ‘recycling’ bags end up in landfills and bags harm recycling facilities and endanger workers, while companies claim they are ‘perfect’ for recycling',
},
{
	date: 'June 5, 2023',
    file: '2023/06/05_MadisonEquities.asp',
    title: 'Attorney General Ellison sues downtown Saint Paul’s largest landowner for scheme to avoid paying overtime to security officers',
    lede: 'Alleges Madison Equities used subsidiaries to deprive security officers of overtime wages owed under Minnesota law; also alleges company illegally retaliated against worker who came forward',
},
{
	date: 'June 2, 2023',
    file: '2023/06/02_XcelEnergy.asp',
    title: 'Attorney General Ellison’s office helps cut Xcel Energy’s rate hike by more than half',
    lede: 'Attorneys and analysts representing residential and small-business ratepayers as well as the Department of Commerce help ratepayers afford their lives',
},
{
	date: 'June 2, 2023',
    file: '2023/06/02_Suboxone.asp',
    title: 'Attorney General Ellison reaches $102.5M national settlement with Suboxone maker for alleged illegal monopoly tactics',
    lede: 'Alleges company illegally delayed generic version of drug that treats opioid addiction, tried to convince patients their more expensive version of the drug was safer in order to keep prices high and preserve monopoly',
},
{
	date: 'May 23, 2023',
    file: '2023/05/23_Avid.asp',
    title: 'Attorney General Ellison sues Avid Telecom over illegal robocalls',
    lede: 'Alleges company initiated and facilitated billions of illegal robocalls, including calls spoofing government agencies — including at least 14K to Minnesotans',
},
{
	date: 'May 19, 2023',
    file: '2023/05/19_Harvey.asp',
    title: 'Attorney General Ellison obtains relief for consumers targeted by unscrupulous door-to-door alarm salesman',
    lede: 'Skyline Security Management, Inc. and Safe Home Security agree to cancel contracts while AGO enforcement action against Gary Harvey continues',
},
{
	date: 'May 19, 2023',
    file: '2023/05/19_Avolta.asp',
    title: 'Attorney General Ellison secures final judgments against solar-sales companies that defrauded consumers',
    lede: 'Settlements with 10 defendants include court-ordered bans on future sales by companies and their owners, prompt completion of existing projects, and consumer restitution of $310K',
},
{
	date: 'May 18, 2023',
    file: '2023/05/18_MerwinWinner.asp',
    title: 'Reports of violence, drug sales down after joint investigation into Winner Gas Station and Merwin Liquors',
    lede: 'Investigation by AG Ellison, City of Minneapolis, and Hennepin County prompted changes to stem illegal activity on Minneapolis corner',
},
{
	date: 'May 18, 2023',
    file: '2023/05/18_CommerceOmnibusBill.asp',
    title: 'Attorney General Ellison hails passage of key recommendations of his pharmaceutical drug price task force',
    lede: 'Provisions of Commerce Omnibus Bill prohibit price-gouging on generic prescription drugs and establish Prescription Drug Affordability Board — ‘These new laws will save Minnesotans’ lives’',
},
{
	date: 'May 17, 2023',
    file: '2023/05/17_JUUL.asp',
    title: 'Minnesota settles lawsuit against Juul and Altria for $60.5 million',
    lede: 'After three-week trial, settlement value is largest per capita in US, exceeds JUUL’s gross revenues from marketing and selling to Minnesotans; State to receive 60% of the funds within one year',
},
{
	date: 'May 10, 2023',
    file: '2023/05/10_Stetson.asp',
    title: 'Justin Stetson admits guilt in assault of Jaleel Stallings',
    lede: 'Stetson can never serve as a law-enforcement officer again, will apologize to Mr. Stallings and acknowledge his participation in a ‘harmful institutional culture of policing within the Minneapolis Police Department’',
},
{
	date: 'May 2, 2023',
    file: '2023/05/02_Thao.asp',
    title: 'Tou Thao convicted of 2nd-degree manslaughter in murder of George Floyd',
    lede: 'Last of four defendants in Floyd’s 2020 death convicted after stipulated bench trial agreed to in October 2022',
},
{
	date: 'April 25, 2023',
    file: '2023/04/25_GreenwayApartments.asp',
    title: 'Attorney General Ellison investigating Minneapolis landlord that may have filed dozens of baseless evictions',
    lede: 'Investigating whether Greenway Apartments and Investment Property Group violated landlord-tenant and civil-rights laws by filing eviction actions for charges tenants did not owe',
},
{
	date: 'April 24, 2023',
    file: '2023/04/24_NonCompeteClause.asp',
    title: 'Attorney General Ellison again supports limiting non-competes in employment',
    lede: 'Joins 18 AGs in comments to FTC in favor of proposed rule he first asked for in 2019; 30M American workers bound by non-compete clauses',
},
{
	date: 'April 20, 2023',
    file: '2023/04/20_HyundaiKia.asp',
    title: 'Attorney General Ellison calls for national recall of theft-prone Hyundai/Kia vehicles',
    lede: 'Joins coalition of 18 AGs in asking NHTSA to recall vehicles while AG continues to investigate whether companies have violated Minnesota law',
},
{
	date: 'April 17, 2023',
    file: '2023/04/17_Chauvin.asp',
    title: 'Court of Appeals upholds Derek Chauvin’s convictions in murder of George Floyd',
    lede: 'Decision shows ‘once again no one is above the law — and no one is beneath it’',
},
{
	date: 'April 17, 2023',
    file: '2023/04/17_JUUL.asp',
    title: 'Minnesota settles historic e-cigarette lawsuit with JUUL and Altria',
    lede: 'Minnesota first state in nation to go to trial to hold JUUL and Altria accountable for deceptive e-cigarette marketing ',
},
{
	date: 'April 6, 2023',
    file: '2023/04/06_McKeever.asp',
    title: 'Attorney General Ellison’s Office to prosecute murder of Zaria McKeever',
    lede: 'Minnesota Attorney General Keith Ellison issued the following statement upon accepting Governor Tim Walz’s referral under Minnesota law of the prosecution of the murder of Zaria McKeever.',
},
{
	date: 'March 31, 2023',
    file: '2023/03/31_ConsentDecree.asp',
    title: 'AG Ellison: State, Minneapolis consent decree on policing is ‘historic’',
    lede: 'Praises court-enforceable agreement ‘centered around transformational changes’ that makes ‘very significant steps to build community trust and make every Minneapolis resident and police officer safer’',
},
{
	date: 'March 28, 2023',
    file: '2023/03/28_JuulAndAltria.asp',
    title: '‘Juul and Altria hooked Minnesota’s children on e-cigarettes — so they could make money’',
    lede: 'Attorney General Ellison delivers first half of State’s opening statement as first trial against Juul and Altria begins in Minnesota',
},
{
	date: 'March 23, 2023',
    file: '2023/03/23_JanelleJohnson.asp',
    title: 'Attorney General’s Office secures conviction in Beltrami County murder case',
    lede: 'Janelle Johnson found guilty of 2nd-degree murder in December 25, 2020 shooting death of brother-in-law Jesse Farris',
},
{
	date: 'March 23, 2023',
    file: '2023/03/23_EnergyCompanies.asp',
    title: 'Federal appeals court rules State’s climate-change deception lawsuit can proceed in state court',
    lede: 'In decision today, 8th Circuit Court of Appeals rules against defendants, upholds U.S. District Court remand of lawsuit to state court where it was originally filed',
},
{
	date: 'March 16, 2023',
    file: '2023/03/16_Juul.asp',
    title: 'Judge rules State’s case against Juul and Altria will proceed to trial on March 27',
    lede: 'In order issued this week, Court rejected defendants’ latest efforts to dismiss State’s claims',
},
{
	date: 'March 13, 2023',
    file: '2023/03/13_HousingHub.asp',
    title: 'Attorney General Ellison wins relief for tenants whose landlord allegedly unlawfully withheld amounts from security deposits ',
    lede: 'Housing Hub to pay $63,000, stop charging tenants for carpet cleaning, replacing batteries, lightbulbs, and filters at move out',
},
{
	date: 'March 7, 2023',
    file: '2023/03/07_KiaHyundai.asp',
    title: 'Attorney General Ellison Launches Civil Investigation of Kia and Hyundai’s Sale of Vehicles that Lack Industry-Standard, Anti-Theft Technology',
    lede: 'Drastic increase in Kia, Hyundai vehicle thefts posing an ongoing threat to public safety',
},
{
	date: 'March 2, 2023',
    file: '2023/03/02_KiaHyundai.asp',
    title: 'Attorney General Ellison, Mayors Frey and Carter press Kia and Hyundai for safety recall',
    lede: 'In a letter to CEOs, underscore need to recall and outfit vehicles with industry-standard anti-theft technology to improve public safety in light of rapidly rising tide of thefts of Kia and Hyundai vehicles',
},
{
	date: 'February 14, 2023',
    file: '2023/02/14_Apmann.asp',
    title: 'Attorney General’s Office secures conviction in Cottonwood County murder case',
    lede: 'Jury finds Ralph Apmann guilty of second-degree unintentional murder in August 2021 death of Juan Morales Rivera in Windom',
},
{
	date: 'February 14, 2023',
    file: '2023/02/14_DirectAccountManagement.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State $20K to refund Minnesota customers; marks 13th time AGO has shut down fraudulent student-loan debt-relief company in Minnesota',
},
{
	date: 'February 14, 2023',
    file: '2023/02/14_DeputyAttorneyGeneral.asp',
    title: 'Attorney General Ellison names Jessica Whitney as Deputy Attorney General',
    lede: 'Veteran of Iowa AG’s office brings proven experience in consumer protection, will start March 1',
},
{
	date: 'February 11, 2023',
    file: '2023/02/11_Sherrell.asp',
    title: 'Attorney General’s Office to assist in review of death of Hardel Sherrell in Beltrami County jail',
    lede: 'AG’s office agrees to assist Beltrami County Attorney in review, possible criminal charging in 2018 death of Mr. Sherrell in Beltrami County jail',
},
{
	date: 'February 9, 2023',
    file: '2023/02/09_West.asp',
    title: 'Attorney General’s Office secures conviction in Cook County murder case',
    lede: 'Thomas West convicted by jury of being accessory after the fact to 2021 murder of Ricky Balsimo, interference with dead body',
},
{
	date: 'February 6, 2023',
    file: '2023/02/06_Funding.asp',
    title: 'Attorney General Ellison’s request for more criminal prosecutors to become law upon House passage',
    lede: 'House passage comes after Senate passage last week — and after four years of requests by AG Ellison. Appropriation will more than triple capacity of AG’s Office to assist county attorneys in prosecuting serious violent crime and bringing justice to victims.',
},
{
	date: 'February 2, 2023',
    file: '2023/02/02_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office named Top Workplace USA for 2nd year in a row',
    lede: 'After being named a Star Tribune Top Workplace for the second time, Attorney General’s Office once again named a Top Workplace USA',
},
{
	date: 'January 27, 2023',
    file: '2023/01/27_MNCretePools.asp',
    title: 'Attorney General Ellison obtains default judgment against pool contractor who defrauded Minnesota consumers',
    lede: 'After AG sues in August 2022, court permanently bans Charles Workman and company from residential construction industry in Minnesota; orders $1.1M in refunds to victims and $1.1M civil penalty to State',
},
{
	date: 'January 17, 2023',
    file: '2023/01/17_Bremer.asp',
    title: 'Attorney General’s Office prevails in Otto Bremer Trust appeal',
    lede: 'Minnesota Court of Appeals upholds district court’s decision to remove former trustee, affirms that he “continually breached his duties” and is “unfit to administer the Trust”',
},
{
	date: 'January 13, 2023',
    file: '2023/01/13_Rhodes.asp',
    title: 'Conviction Review Unit Vacates First and Second-Degree Murder Sentence; Thomas Rhodes Released from Prison after nearly 25 years',
    lede: 'Rhodes’ release marks the first person who will be freed from incarceration because of an investigation and case review by Minnesota’s Conviction Review Unit; Rhodes stands convicted of second-degree manslaughter',
},
{
	date: 'January 10, 2023',
    file: '2023/01/10_ThinkTechAct.asp',
    title: 'Attorney General Ellison sues nonprofit and its leaders for misusing funds and extensive governance violations; seeks to shut down nonprofit',
    lede: 'State files lawsuit against ThinkTechAct Foundation and three of its leaders for running a sham nonprofit, misusing nonprofit funds obtained from the federal child nutrition program, and other charities violations',
},
{
	date: 'January 2, 2023',
    file: '2023/01/02_InauguralRemarks.asp',
    title: '‘I will keep working to help Minnesotans afford their lives and live with dignity, safety, and respect’',
    lede: 'Attorney General Ellison sworn in for 2nd term with ‘renewed vigor and commitment’',
},
	
	
];



	
