var pr2019 = [

{
	date: 'December 20, 2019',
    file: '2019/12/20_PoliceCharityBan.asp',
    title: 'Attorney General Ellison permanently bans two charities that deceived Minnesotans about supporting families of fallen police officers',
    lede: 'Obtains settlement that permanently bans two related charities from soliciting in Minnesota, requires one of them to pay back nearly $300K solicited from Minnesotans',
},
{
	date: 'December 16, 2019',
    file: '2019/12/16_JourneyHomeMinnesota.asp',
    title: 'Attorney General Ellison files suit against president of Journey Home Minnesota',
    lede: 'Lawsuit alleges Blake Huffman mismanaged JHM’s charitable assets, engaged in transactions with clear conflicts of interest, abandoned JHM’s charitable mission',
},
{
	date: 'December 13, 2019',
    file: '2019/12/13_RefugeeResettlement.asp',
    title: 'Attorney General Ellison defends refugees against President’s unlawful executive order',
    lede: 'Joins coalition of 12 AGs in brief in support of refugee-resettlement organizations challenging Trump order; argues order violates federal law, interferes with state sovereignty, and undermines family reunification. Brief filed on same day Gov. Walz announces Minnesota will continue to accept refugees.',
},
{
	date: 'December 12, 2019',
    file: '2019/12/12_AutoAssure.asp',
    title: 'Attorney General Ellison bans Texas company over sale of suspect ‘extended warranties’ for vehicles',
    lede: 'Settlement also requires AutoAssure, LLC to pay $400K toward refunds for around 1,000 Minnesota consumers',
},
{
	date: 'December 4, 2019',
    file: '2019/12/04_JUUL.asp',
    title: 'State sues JUUL for deceptive marketing targeting youth',
    lede: 'AG Ellison announces lawsuit with Gov. Walz as Minnesota loses 10 years of progress in fighting youth tobacco use. JUUL addicts youth by deceiving them about nicotine content, following Big Tobacco marketing playbook.',
},
{
	date: 'November 26, 2019',
    file: '2019/11/26_ACTvTrump.asp',
    title: 'Attorney General Ellison once again leads fight to protect Liberians from deportation ',
    lede: 'Co-leads coalition of 14 states in supporting appeal of dismissal of lawsuit against Trump Administration order to end DED protections.Third time this year that AG Ellison moves to protect Liberians against President’s attempt to terminate status.',
},
{
	date: 'November 19, 2019',
    file: '2019/11/19_DFA.asp',
    title: 'Attorney General Ellison reaches agreement to help school districts afford the price of school milk ',
    lede: 'Will protect more than 40 school districts and programs through 2030',
},
{
	date: 'November 18, 2019',
    file: '2019/11/18_NonCompeteClauses.asp',
    title: 'Attorney General Ellison leads fight to classify non-compete clauses as unfair and illegal',
    lede: 'Abusive non-compete clauses currently prevent 30 million Americans — especially low-income ones — from getting better jobs, pursuing higher ambitions, and leaving hostile or unsafe work environments ',
},
{
	date: 'November 13, 2019',
    file: '2019/11/13_DoeVTrump.asp',
    title: 'Attorney General Ellison fights unlawful attempt to use healthcare coverage to bar immigrants',
    lede: 'Joins coalition of 22 AGs in challenging presidential proclamation that would bar entry to immigrants who do not possess certain health insurance or the ability to pay for medical care',
},
{
	date: 'November 6, 2019',
    file: '2019/11/06_RefusalOfCare.asp',
    title: 'Attorney General Ellison and coalition win fight to stop Trump Administration healthcare discrimination rule',
    lede: 'Federal court issues summary judgment vacating entire HHS rule ‘refusal of care’ rule. Rule would have drastically expanded healthcare providers’ ability to deny necessary healthcare to virtually anyone they chose, solely on the basis of their own ‘religious beliefs or moral convictions’',
},
{
	date: 'November 6, 2019',
    file: '2019/11/06_MSBGlobe.asp',
    title: 'Attorney General Ellison’s office notches big victory for defrauded MSB/Globe students',
    lede: 'Minnesota Supreme Court allows AG’s office to obtain tuition refunds for more than 1,300 low-income students of MSB/Globe criminal-justice program — more than $33 million in restitution now possible. Court also affirms AG’s authority to seek restitution for all Minnesotans harmed by fraud.',
},
{
	date: 'October 30, 2019',
    file: '2019/10/30_StudentLoanCompanies.asp',
    title: 'Attorney General Ellison sues companies and individuals running fraudulent student loan debt “forgiveness” scheme, obtains court order immediately halting conduct ',
    lede: 'Companies illegally charged up-front fees upwards of $1,300 for filling out and submitting forms to the federal government for loan repayment and consolidation programs, which eligible borrowers can apply for on their own for free. In response to lawsuit, federal judge issues temporary restraining order against defendants ',
},
{
	date: 'October 22, 2019',
    file: '2019/10/22_EndageredSpeciesAct.asp',
    title: 'Attorney General Ellison joins lawsuit protecting Endangered Species Act',
    lede: 'Ellison: Trump Administration’s undermining of the Act ‘is not only unlawful, it’s un-Minnesotan’ ESA currently protects the Topeka Shiner, Canada Lynx, and Prairie Fringed Orchid, among other Minnesota species',
},
{
	date: 'October 17, 2019',
    file: '2019/10/17_Meldahl.asp',
    title: 'Attorney General’s Office wins next step in case against landlord Steven Meldahl',
    lede: 'Court issues temporary injunction that expands scope of earlier order to require that Meldahl get properties inspected, inform tenants of rights to inspection, and stop charging more than 8 percent for late fees. Meldahl, who brags about evicting 99 percent of his tenants, has been cited more than 1,300 times in last 10 years for City housing-code violations. ',
},
{
	date: 'October 17, 2019',
    file: '2019/10/17_Helpforstudents.asp',
    title: 'Attorney General Ellison seeks more federal help for students unfairly harmed by closure of Argosy University and Art Institues',
    lede: 'Co-leads letter of 30 AGs to ask Secretary DeVos to expand ‘closed school discharge’ to more students of schools closed after owner’s misconduct and mismanagement',
},
{
	date: 'October 8, 2019',
    file: '2019/10/08_MinneapolisLandlord.asp',
    title: 'Attorney General Ellison files suit to halt North Minneapolis landlord’s ‘eviction for profit’ scheme, obtains court order protecting his tenants who want to contact city housing inspectors',
    lede: 'In response to AG’s lawsuit, Hennepin County Court stops Steven Meldahl from enforcing illegal lease provisions, freezes bank accounts. Meldahl, who evicts 99 percent of tenants, has been cited more than 1,300 times in last 10 years for City housing-code violations',
},
{
	date: 'October 7, 2019',
    file: '2019/10/07_MississippiClinic.asp',
    title: 'Attorney General Ellison defends women’s access to full range of reproductive healthcare',
    lede: 'Joins 19 other AGs in filing amicus brief at 5th Circuit in support of women’s health clinic challenging Mississippi’s near-total ban on abortion',
},
{
	date: 'October 4, 2019',
    file: '2019/10/04_PurduePharma.asp',
    title: 'Attorney General Ellison asks court to deny Purdue’s and Sacklers’ move to avoid accountability for death and destruction',
    lede: 'Joins 24 other AGs in bankruptcy-court filing against Purdue’s motion to halt lawsuit; Ellison’s office plays leading role in drafting oppositions',
},
{
	date: 'October 2, 2019',
    file: '2019/10/02_TelescopeMedia.asp',
    title: 'Attorney General Ellison, Commissioner Lucero choose to fight LGBTQ wedding-video discrimination case in trial court',
    lede: 'Instead of appealing split Eighth Circuit decision, will take case back to federal district court to build record of actual facts to counter plaintiff’s ‘fairy tale’ assertions',
},
{
	date: 'September 27, 2019',
    file: '2019/09/27_MedicaidFraud.asp',
    title: 'Attorney General Ellison charges 11 people with $800K in Medicaid fraud',
    lede: 'Including Chappy’s case, AG’s office charges total 21 people with $3M in Medicaid fraud this week',
},
{
	date: 'September 26, 2019',
    file: '2019/09/26_TobaccoSettlement.asp',
    title: 'Court rules R.J. Reynolds wrongfully failed to pay State millions in tobacco-settlement fees',
    lede: 'Court to determine amount owed State in coming months',
},
{
	date: 'September 25, 2019',
    file: '2019/09/25_CleanCarStandards.asp',
    title: 'Attorney General Ellison applauds Governor Walz’s clean-car standards, already defending them in court ',
    lede: 'Minnesota one of 22 states and 3 cities that filed suit late last week against Trump Administration attempts to preempt clean-car standards',
},
{
	date: 'September 24, 2019',
    file: '2019/09/24_ChappysGoldenShores.asp',
    title: 'Attorney General Ellison’s office files 76 maltreatment, fraud, and obstruction charges against owner, managers, and employees of assisted-living facility',
    lede: 'Manslaughter among charges brought against former owner of Chappy’s Golden Shores in Hill City, who faces 25 charges alone',
},
{
	date: 'September 24, 2019',
    file: '2019/09/24_NOBANact.asp',
    title: 'Attorney General Ellison supports banning discrimination on the basis of religion in immigration decisions',
    lede: 'Led coalition of 19 AGs in supporting NO BAN Act being raised today in Congress in response to Trump Administration Muslim Ban',
},
{
	date: 'September 23, 2019',
    file: '2019/09/23_NorthernMetals.asp',
    title: 'Attorney General Ellison: Northern Metals shutdown and settlement ‘better than what we could have achieved at trial’ and a ‘win for the people of North Minneapolis’',
    lede: 'In addition to shutting down for good at 6:00 p.m. today, Northern Metals admits to wrongdoing and will pay civil penalty in settlement with State',
},
{
	date: 'September 9, 2019',
    file: '2019/09/09_RefusalOfCare.asp',
    title: 'AG Ellison, coalition ask court to block Trump Administration’s healthcare discrimination rule',
    lede: 'Discriminatory ‘refusal of care’ rule would drastically expand healthcare providers’ rights to deny necessary healthcare to anyone they choose, solely on the basis of their own ‘religious beliefs or moral convictions’',
},
{
	date: 'September 9, 2019',
    file: '2019/09/09_Podcast.asp',
    title: 'Attorney General Ellison launches new biweekly podcast: ‘Affording Your Life with Keith Ellison’',
    lede: 'Dedicated to fairness, justice, and consumer information to help people afford their lives; new episode to be released every other Monday',
},
{
	date: 'September 6, 2019',
    file: '2019/09/06_BoyScouts.asp',
    title: 'Attorney General Ellison files amicus brief in support of public release of Boy Scouts’ ‘Perversion Files,’ with safeguards for accused',
    lede: 'Because “substantial public interest in disclosure … must be balanced against fairness and privacy concerns,” recommends appointment of Special Master to review each file',
},
{
	date: 'August 22, 2019',
    file: '2019/08/22_ExpeditedRemoval.asp',
    title: 'Attorney General Ellison fights radical new Trump Administration rule that puts legal residents at risk of deportation',
    lede: 'Joins 17 other AGs in asking court to block rule that was unlawfully implemented, lacks clear legal standards, and will harm their states and communities',
},
{
	date: 'August 22, 2019',
    file: '2019/08/22_Robocalls.asp',
    title: 'Attorney General Ellison joins 51 attorneys general and 12 companies in adopting principles to fight illegal robocalls',
    lede: 'Prevention and enforcement at heart of historic agreement for protecting consumers',
},
{
	date: 'August 21, 2019',
    file: '2019/08/21_PreferredCredit.asp',
    title: 'Minnesotans to get refunds, debt relief, and credit repair from Preferred Credit, Inc.',
    lede: 'Attorney General Ellison’s office announces settlement that affects more than 400 Minnesotans',
},
{
	date: 'August 20, 2019',
    file: '2019/08/20_BoyScouts.asp',
    title: 'Attorney General Ellison supports public release of Boy Scouts’ ‘Perversion Files’ with safeguards for rights of accused',
    lede: 'As state’s chief legal officer, seeks disclosure in the interests of justice, transparency, and protecting children',
},
{
	date: 'August 16, 2019',
    file: '2019/08/16_ACA.asp',
    title: 'Attorney General Ellison condemns Trump Administration effort to allow discrimination in healthcare',
    lede: 'Proposed HHS rule will eliminate ACA’s protections against discrimination for women, people with disabilities, the LGBTQ community, and other vulnerable communities',
},
{
	date: 'August 15, 2019',
    file: '2019/08/15_PublicChargeRule.asp',
    title: 'Attorney General Ellison files lawsuit against ‘public charge’ rule',
    lede: 'New rule ‘bait-and-switch’ means families and children will have less access to food, healthcare, and shelter, meaning more burden for all communities',
},
{
	date: 'August 9, 2019',
    file: '2019/08/09_NewHopeFoundation.asp',
    title: 'Attorney General Ellison permanently bans sham hospice charity, New Hope Foundation, from operating in Minnesota',
    lede: 'Obtains settlement prohibiting sham hospice charity from any further activity in Minnesota due to its misleading solicitation practices and misuse of donations',
},
{
	date: 'August 8, 2019',
    file: '2019/08/08_MSBGlobeLoans.asp',
    title: 'Attorney General Ellison wins expansion of federal-loan discharge for MSB/Globe University students',
    lede: 'Following advocacy by AG Ellison’s office, the US Dept. of Education will now allow students who withdrew any time after court found schools had engaged in fraud to apply to discharge their federal loans',
},
{
	date: 'August 5, 2019',
    file: '2019/08/05_PurdueComplaint.asp',
    title: 'Sackler family knew but denied and downplayed risks of opioids, stigmatized addicted people, then moved to profit from addiction',
    lede: 'AG Ellison’s office files unredacted complaint that shows family that controls Purdue paid themselves $4B in profit from opioids, while calling addicted people ‘criminals,’ ‘scum of the earth’ — then exploiting addiction treatment as an ‘attractive market’ that is ‘naturally linked’ to the crisis they created',
},
{
	date: 'August 2, 2019',
    file: '2019/08/02_DED.asp',
    title: 'Attorney General Ellison moves to defend Liberians from deportation',
    lede: 'Co-leads coalition of 15 states in amicus brief supporting suit to halt Trump’s termination of DED',
},
{
	date: 'July 26, 2019',
    file: '2019/07/26_TMobileSprint.asp',
    title: 'Attorney General Ellison: T-Mobile/Sprint mega-merger would still hurt Minnesotans’ ability to afford their lives',
    lede: 'Speculative deal with DISH Network does not resolve concerns about impacts on consumers, workers, and communities',
},
{
	date: 'July 25, 2019',
    file: '2019/07/25_EndoSettlement.asp',
    title: 'Minnesota reaches settlement with pharmaceutical company over ‘pay-for-delay’ behavior',
    lede: 'Endo settles with 18 states over charges it protected its monopoly on Lidoderm through illegal, anti-competitive conduct',
},
{
	date: 'July 22, 2019',
    file: '2019/07/22_EquifaxSettlement.asp',
    title: 'Attorney General Ellison and 49 other AGs secure settlement from Equifax in largest data-breach in history',
    lede: '$600M settlement includes up to $425 million in consumer restitution — comes after investigation into massive 2017 data breach that affected 147M Americans',
},
{
	date: 'July 17, 2019',
    file: '2019/07/17_Roundtables.asp',
    title: 'THURSDAY–SATURDAY: AG Ellison to listen to Minnesotans in south-central and southwest Minnesota',
    lede: 'Minnesota Attorney General Keith Ellison will co-host a public roundtable discussion on wage theft and two listening sessions with local legislators, as well as meet privately with a variety of community leaders and workers, during three days of travel in south-central and southwest Minnesota, starting this Thursday, July 18 through Saturday, July 20. ',
},
{
	date: 'July 15, 2019',
    file: '2019/07/15_WageTheftUnit.asp',
    title: 'Attorney General Ellison announces new Wage Theft Unit in AGO',
    lede: 'Will investigate and litigate complaints of wage theft and other workplace fraud and abuse perpetrated against Minnesotans of all backgrounds, especially the most vulnerable',
},
{
	date: 'July 12, 2019',
    file: '2019/07/12_ICERaids.asp',
    title: 'Attorney General Ellison: ‘President Trump’s cruelty violates Minnesotans’ sense of decency’',
    lede: 'Ellison tells Minnesotans, ‘Regardless of your immigration status, you have legal and constitutional rights — know them and exercise them. As long as I’m the People’s Lawyer, we’ll keep fighting for everyone’s dignity, no exceptions’',
},
{
	date: 'July 11, 2019',
    file: '2019/07/11_PremeraSettlement.asp',
    title: 'Attorney General Ellison reaches settlement in data breach affecting 38,000 Minnesotans',
    lede: 'Thirty states settle claims related to 2014–15 data breach that exposed sensitive medical information',
},
{
	date: 'July 10, 2019',
    file: '2019/07/10_WorkplaceDiscrimination.asp',
    title: 'Attorney General Ellison files Supreme Court brief to protect LGBTQ+ employees from workplace discrimination',
    lede: 'Joins 21 other AGs in brief on three cases of discrimination based on sexual orientation and gender identity that Court will hear together in October',
},
{
	date: 'July 10, 2019',
    file: '2019/07/10_HumanRights.asp',
    title: 'Attorney General Ellison defends human rights of children in civil immigration detention',
    lede: 'Joins coalition of 21 AGs in filing amicus brief asking for immediate relief from threats to children’s health and welfare',
},
{
	date: 'June 27, 2019',
    file: '2019/06/27_Census2020.asp',
    title: 'AG Ellison: ‘Every Minnesotan, no matter their citizenship or immigration status, must be counted’  ',
    lede: 'Ellison pledges to use ‘every legal recourse’ to keep ‘clearly prejudicial’ citizenship question off 2020 Census',
},
{
	date: 'June 21, 2019',
    file: '2019/06/21_TMobileSprintMerger.asp',
    title: 'Minnesota joins lawsuit to block T-Mobile/Sprint mega-merger ',
    lede: 'AG Ellison joins 13 other AGs in amended complaint that alleges merger is anti-competitive, will drive up prices for consumers, cost jobs, and hurt rural areas',
},
{
	date: 'June 20, 2019',
    file: '2019/06/20_BreastCancerOutreachFoundation.asp',
    title: 'Attorney General Ellison permanently bans deceptive charity, Breast Cancer Outreach Foundation, from operating in Minnesota',
    lede: 'Obtains settlement prohibiting charity from any further activity in Minnesota due to deceptive solicitation practices, encourages Minnesotans to ‘do your homework’ before giving',
},
{
	date: 'June 19, 2019',
    file: '2019/06/19_ITTTech.asp',
    title: 'Attorney General Ellison’s office wins more than $1 million in debt relief for former ITT Tech students',
    lede: 'CUSO agrees to forego collection of outstanding loans and cease doing business',
},
{
	date: 'June 18, 2019',
    file: '2019/06/18_ElectionSystemThreats.asp',
    title: 'Attorney General Ellison leads AGs in asking Congress to protect integrity of America’s elections',
    lede: 'Leads 21 other AGs in asking for grants, security standards, and bipartisan election-security legislation to address “persistent threats to our election systems”',
},
{
	date: 'June 7, 2019',
    file: '2019/06/07_Overdoses.asp',
    title: 'Attorney General Ellison: Rash of overdoses why Minnesota investigating and suing opioid manufacturers',
    lede: 'Minnesota Attorney General Keith Ellison issued the following statement in response to a Minneapolis Police Department report of a record-high 50 overdoses, including one suspected death, during the week of May 28 – June 5, 2019',
},
{
	date: 'June 7, 2019',
    file: '2019/06/07_UnsealDrugPriceComplaint.asp',
    title: 'Attorney General Ellison joins motion to unseal generic drug price-fixing complaint',
    lede: 'Marks latest step in second case against ‘largest cartel in history’',
},
{
	date: 'May 30, 2019',
    file: '2019/05/30_HIPAADataBreachSettlement.asp',
    title: 'Attorney General Ellison announces settlement in data breach affecting 8,000 Minnesotans',
    lede: 'Sixteen states settle claims related to 2015 data breach in first-ever multi-state lawsuit filed under HIPAA',
},
{
	date: 'May 25, 2019',
    file: '2019/05/25_LegislativeSession.asp',
    title: 'Attorney General Ellison: Legislature takes steps toward helping people afford their lives and live with dignity and respect — with more to be done',
    lede: 'Session ends with new tools AG Ellison fought for to fight wage theft and opioid crisis, protect public’s money held in HMOs’ charitable assets, regulate PBMs, protect against elder abuse — and with first increase to AGO budget in 6 years',
},
{
	date: 'May 24, 2019',
    file: '2019/05/24_ConsumerProtections.asp',
    title: 'Attorney General Ellison fights federal efforts to make it harder for Minnesotans to afford their lives',
    lede: 'Opposes new federal rules that would reverse overtime protections for workers and weaken protections against predatory payday lenders Ellison: ‘As the People’s Lawyer, I’ll protect Minnesotans when the federal government won’t’',
},
{
	date: 'May 22, 2019',
    file: '2019/05/22_HealthCareDiscrimination.asp',
    title: 'Attorney General Ellison sues to protect Minnesotans from discrimination in health care',
    lede: 'Joins coalition of 23 states and municipalities in suing to block new Trump Administration rule that would allow businesses and healthcare practitioners to deny care solely on the basis of personal views, not lawful medical need ',
},
{
	date: 'May 17, 2019',
    file: '2019/05/17_PurdueAmendedComplaint.asp',
    title: 'State of Minnesota adds Sackler family as defendants in lawsuit against Purdue Pharma',
    lede: 'Attorney General Ellison announces State asking court to amend complaint against opioid manufacturer to include eight members of Sackler family, which owns company, as individual defendants',
},
{
	date: 'May 15, 2019',
    file: '2019/05/15_GenderIdentityOnPassports.asp',
    title: 'Attorney General Ellison defends rights of gender non-binary people in court ',
    lede: 'Joins amicus brief in support of individual who requested passport with alternative marker for sex',
},
{
	date: 'May 15, 2019',
    file: '2019/05/15_SchoolMealDebtOpinion.asp',
    title: 'Attorney General Ellison: Public school districts may not restrict student participation in graduation ceremonies because of unpaid meal debt',
    lede: 'Binding opinion issued in response to request from Commissioner of Education, following Legal Aid reports of some districts restricting student participation',
},
{
	date: 'May 13, 2019',
    file: '2019/05/13_PharmaceuticalPriceFixing.asp',
    title: 'Decrying ‘illegal behavior rooted in greed,’ Attorney General Ellison announces major lawsuit against manufacturers of generic pharmaceutical drugs, part of ‘largest cartel in history’',
    lede: 'Joins 42 other states and Puerto Rico in alleging 20 companies illegally allocated and fixed prices on 112 generic drugs that treat cancer, diabetes, MS, other conditions<br>Rep. Rod Hamilton denounces ‘greedy corporate cartel that is stealing from the sick, the dying, and the disabled’',
},
{
	date: 'May 1, 2019',
    file: '2019/05/01_DNRappeal.asp',
    title: 'Attorney General Ellison: Minnesota needs ‘reliable mechanism for renaming places that evoke or celebrate racist parts of our past’',
    lede: 'Statement on DNR appeal of Bde Maka Ska: ‘We need a way to reflect our values today and pass along the state we want our children to inherit tomorrow’',
},
{
	date: 'April 19, 2019',
    file: '2019/04/19_EPA.asp',
    title: 'Attorney General Ellison challenges proposal to undermine mercury and air-toxics standards ',
    lede: 'Joins coalition to oppose EPA’s ‘unlawful’ proposed finding that it is no longer ‘appropriate’ to regulate toxic air pollution from power plants — ‘Once again, the Administration is abandoning its duty to protect the American people,’ Ellison says',
},
{
	date: 'April 15, 2019',
    file: '2019/04/15_ReproductiveRights.asp',
    title: 'Attorney General Ellison continues support for women’s reproductive rights',
    lede: 'Joins coalition of 21 attorneys general in amicus brief in asking 5th Circuit to uphold permanent injunction on ‘plainly unconstitutional’ Mississippi law',
},
{
	date: 'April 9, 2019',
    file: '2019/04/09_Argosy.asp',
    title: 'Attorney General Ellison issues a statement on the abrupt closure of Argosy University’s Twin Cities campus',
    lede: '',
},
{
	date: 'April 9, 2019',
    file: '2019/04/09_GlobeMSB.asp',
    title: 'Attorney General Ellison issues a statement regarding the State’s lawsuit against the Minnesota School of Business (“MSB”) and Globe University (“Globe”)',
    lede: '',
},
{
	date: 'April 5, 2019',
    file: '2019/04/05_WomensHealthAmicusBrief.asp',
    title: 'Attorney General Ellison joins multi-state effort to protect women’s access to reproductive health',
    lede: 'In amicus brief, asks 6th Circuit to uphold lower court finding that Kentucky law is unconstitutional',
},
{
	date: 'April 4, 2019',
    file: '2019/04/04_TaskForceMembers.asp',
    title: 'Attorney General Ellison names members of task force on lowering pharmaceutical drug prices',
    lede: '15 members chosen through public process include medical practitioners, labor and industry representatives, legislators, and people affected by high cost of pharmaceutical drugs',
},
{
	date: 'April 3, 2019',
    file: '2019/04/03_SupremeCourtUnion.asp',
    title: 'Attorney General Ellison defends union representation of workers at Supreme Court',
    lede: 'Files two briefs in support of lower-court rulings that upheld exclusive union representation for workers ',
},
{
	date: 'April 3, 2019',
    file: '2019/04/03_NutritionalStandards.asp',
    title: 'Attorney General Ellison joins multistate coalition suing Trump Administration for gutting key nutritional standards for school meals',
    lede: 'At least 600,000 Minnesota schoolchildren affected by “unlawful” revisions to sodium limits, whole-grain content requirements for school breakfasts and lunches ',
},
{
	date: 'April 1, 2019',
    file: '2019/04/01_CensusCitizenQuestion.asp',
    title: 'One year ahead of census, Attorney General Ellison and coalition challenge citizenship question at Supreme Court',
    lede: 'File brief in Trump administration’s appeal of ruling that stripped question from census ',
},
{
	date: 'March 26, 2019',
    file: '2019/03/26_AffordableCareAct.asp',
    title: 'Attorney General Ellison defends Affordable Care Act in court',
    lede: 'Joins coalition of 21 attorneys general in filing opening brief in Texas v. US',
},
{
	date: 'March 26, 2019',
    file: '2019/03/26_LiberianDEDStatus.asp',
    title: 'Attorney General Ellison moves to protect Minnesota’s Liberian community',
    lede: 'Leads multistate coalition of AGs in supporting Liberians who have filed to block termination of DED status',
},
{
	date: 'March 20, 2019',
    file: '2019/03/20_PaydayLenderRule.asp',
    title: 'Attorney General Ellison opposes move to delay protecting people from payday lenders',
    lede: 'Joins letter with 24 other AGs to call on CFPB to enforce rule finalized in 2017',
},
{
	date: 'March 13, 2019',
    file: '2019/03/13_NoPoachingSettlement.asp',
    title: 'Attorney General’s Office wins settlement with four fast-food chains to end no-poach agreements',
    lede: 'Under multi-state agreement, Dunkin’, Arby’s, Five Guys, and Little Caesars will drop franchise provisions that limit recruitment and hiring of workers in fast-food industry',
},
{
	date: 'March 12, 2019',
    file: '2019/03/12_EmissionsCheatingSettlement.asp',
    title: 'Attorney General Ellison announces settlements with Fiat Chrysler and Bosch for unlawful emissions-cheating scheme',
    lede: 'Minnesota to collect $3.5 million from companies for their illegal practices',
},
{
	date: 'March 7, 2019',
    file: '2019/03/07_TechSupportScamTakedown.asp',
    title: 'Attorney General Ellison seeks judgment in lawsuit against tech-support scam as part of nationwide crackdown on scammers',
    lede: 'Files motion for default judgment against Teknicians, Inc., warns Minnesota consumers about tech-support scams as part of Tech Support Takedown',
},
{	date: 'March 6, 2019',
    file: '2019/03/06_OSHALawsuit.asp',
    title: 'Attorney General Ellison sues to protect Minnesota workers',
    lede: 'Joins multi-state lawsuit challenging federal rollback of workplace-injury and -illness reporting rules',
},
{	date: 'March 5, 2019',
    file: '2019/03/05_TitleXGagRule.asp',
    title: 'Attorney General Ellison sues federal government to stop illegal gag rule on women’s reproductive healthcare',
    lede: 'Multistate lawsuit alleges new Trump administration rule is illegal and unconstitutional; Would have disproportionate impact on women in Greater Minnesota',
},
{
	date: 'March 1, 2019',
    file: '2019/03/01_TransgenderAmicusBrief.asp',
    title: 'Attorney General Ellison: ‘Transgender kids, like everyone, deserve to live with dignity and respect’',
    lede: 'Minnesota Attorney General’s office joins multistate amicus brief in favor of transgender student who was wrongly denied use of school bathroom that fits his gender identity',
},
{
	date: 'March 1, 2019',
    file: '2019/03/01_WellsFargoConsumerRedress.asp',
    title: 'Attorney General Ellison Announces Launch of Wells Fargo Consumer Redress Review Program',
    lede: '$575 million nationwide settlement requires Wells Fargo to make any remaining Minnesota victims whole',
},
{	date: 'February 21, 2019',
    file: '2019/02/21_PrescriptionDrugPricingTaskForce.asp',
    title: 'Attorney General Ellison starts task force for lowering the cost of pharmaceutical drugs',
    lede: 'Ellison: Minnesotans are ‘united in one simple idea: they’re entitled to afford their lives — and drug prices are too high’',
},
{
	date: 'February 19, 2019',
    file: '2019/02/19_GovernorWalzBudget.asp',
    title: 'Attorney General Ellison: ‘Governor Walz’s budget delivers on the promise of One Minnesota’',
    lede: 'Governor’s support of Attorney General’s Office will also ‘help people afford their lives and live with dignity and respect’',
},
{
	date: 'February 18, 2019',
    file: '2019/02/18_BorderWallLawsuit.asp',
    title: 'Attorney General Ellison: “The President is harming the people of Minnesota... I cannot allow him to do that.”',
    lede: 'Minnesota joins multistate lawsuit to stop Trump administration from illegally and unconstitutionally diverting federal funds to build border wall',
},
{
	date: 'February 11, 2019',
    file: '2019/02/11_TemporaryProtectedStatus.asp',
    title: 'Attorney General Ellison joins effort to defend immigrant holders of Temporary Protected Status',
    lede: 'Joins coalition of 22 attorneys general in supporting preliminary injunction to block DHS from deporting immigrants to home countries with dangerous or harmful conditions',
},
{
	date: 'February 8, 2019',
    file: '2019/02/08_MedicaidFraudCase.asp',
    title: 'Attorney General Ellison’s office wins largest Medicaid fraud case in Minnesota state court history',
    lede: 'Wins convictions of two people for $7.7 million in fraud against State, including one previously convicted of Medicaid fraud',
},
{
	date: 'January 31, 2019',
    file: '2019/01/31_HiringAnnouncement.asp',
    title: 'Attorney General Ellison names Solicitor General and Government Affairs Director',
    lede: 'Liz Kramer to serve as Solicitor General and former State Rep. Carly Melin as Government Affairs Director on staff team helping Minnesotans afford their lives and live with dignity',
},
{	date: 'January 23, 2019',
    file: '2019/01/23_Settlement.asp',
    title: 'Attorney General Ellison’s office settles three multistate healthcare-related fraud and deceptive-marketing cases, recoups $3.1M for Minnesota',
    lede: 'Settles with Walgreens in two Medicaid fraud cases and with J&amp;J over deceptive marketing of hip implants',
},
{	
	date: 'January 21, 2019',
    file: '2019/01/21_MLKStatement.asp',
    title: 'Attorney General Ellison: ‘The fight against discrimination is the fight for a fair, equal economy’',
    lede: 'On MLK holiday, Ellison recalls Dr. King’s question from Greensboro sit-ins: ‘What good is having the right to sit at a lunch counter if you can’t afford to buy a hamburger?’',
},
{
	date: 'January 15, 2019',
    file: '2019/01/15_BusyStart.asp',
    title: 'Attorney General Ellison’s office off to busy start helping people afford their lives and live with dignity',
    lede: 'In just two days, Ellison promises action to protect Minnesotans during federal government shutdown; AGO prevails in cases blocking federal government from adding citizenship question to 2020 Census and from limiting access to reproductive healthcare; Ellison moves to defend Indian children, culture, and sovereignty',
},
{	date: 'January 7, 2019',
    file: '2019/01/07_Inauguration.asp',
    title: 'Keith Ellison sworn in as Attorney General: “My job as the People’s Lawyer is to help Minnesotans afford their lives and live with dignity and respect”',
    lede: 'In inaugural remarks, AG Ellison adds, “The Minnesota Attorney General’s Office will be a place where everybody counts and everybody matters.”',
},
	
	
];