var pr2020 = [
{
	date: 'December 31, 2020',
    file: '2020/12/31_AlibiDrinkery_ContemptOrder.asp',
    title: 'Attorney General asks court to find Lakeville establishment in contempt',
    lede: 'Alibi Drinkery operating indoor, on-premises dining in defiance of temporary injunction issued earlier today; court sets hearing for January 5',
},
{
	date: 'December 31, 2020',
    file: '2020/12/31_CarlsonEventCenter.asp',
    title: 'Court orders Winnebago Event Center not to hold ‘New Years Eve Bash,’ comply with executive orders',
    lede: 'Attorney General’s office wins temporary restraining order against Carlson Event Center; establishment must now comply with order or risk being found in contempt of court',
},
{
	date: 'December 31, 2020',
    file: '2020/12/31_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of executive orders: December 31, 2020 update',
    lede: '',
},
{
	date: 'December 31, 2020',
    file: '2020/12/31_AlibiDrinkery.asp',
    title: 'Court orders Lakeville establishment to comply with executive order requiring temporary closure for indoor on-premises dining',
    lede: 'Court: Alibi’s actions ‘are both against the law and harmful…directly promoting the spread of Covid-19’; finds Alibi’s arguments ‘without merit and devoid of factual or legal support’',
},
{
	date: 'December 30, 2020',
    file: '2020/12/30_CarlsonEventCenter.asp',
    title: 'Attorney General’s office files new enforcement action against event center set on hosting New Year’s Eve party',
    lede: 'Carlson Event Center in Winnebago threatens to put community at risk by violating ban on indoor events and entertainment intended to slow the spread of COVID-19',
},
{
	date: 'December 29, 2020',
    file: '2020/12/29_YouthSuicide.asp',
    title: 'Attorney General Ellison joins the fight against youth suicide',
    lede: 'Joins 39 attorneys general across the nation working with The Jason Foundation, Inc. to address the public-health issue of youth and young adult suicide',
},
{
	date: 'December 28, 2020',
    file: '2020/12/28_PourHouse.asp',
    title: 'Court orders Clarks Grove restaurant to halt indoor on-premises dining, comply with executive orders',
    lede: 'Attorney General’s office wins temporary restraining order against Pour House; establishment must now comply or risk being found in contempt of court',
},
{
	date: 'December 23, 2020',
    file: '2020/12/23_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of executive orders: December 23, 2020 update',
    lede: '',
},
{
	date: 'December 23, 2020',
    file: '2020/12/23_RestaurantTROs.asp',
    title: 'Courts order Albert Lea, New Prague establishments to halt indoor on-premises dining, comply with executive orders',
    lede: 'Courts grant Attorney General’s motions for temporary restraining orders; The Interchange Wine & Coffee Bistro and St. Patrick’s Tavern and Restaurant must now comply or risk being found in contempt of court',
},
{
	date: 'December 22, 2020',
    file: '2020/12/22_CornerstoneCafe.asp',
    title: 'Court orders Monticello restaurant to halt indoor on-premises dining, comply with executive orders',
    lede: 'Attorney General’s office wins temporary restraining order against Cornerstone Café; establishment must now comply or risk being found in contempt of court',
},
{
	date: 'December 22, 2020',
    file: '2020/12/22_RestaurantTROs.asp',
    title: 'Attorney General’s office files for temporary restraining orders against three restaurants illegally operating on-premises dining',
    lede: 'TRO motions are next step in lawsuits against St. Patrick’s in New Prague, Pour House in Clarks Grove, and The Interchange in Albert Lea filed Monday',
},
{
	date: 'December 22, 2020',
    file: '2020/12/22_BoardwalkBar.asp',
    title: 'Court orders E. Grand Forks establishment to comply with executive order requiring temporary closure for indoor on-premises dining',
    lede: 'Court also orders Boardwalk Bar and Grill to fully comply with all subsequent applicable executive orders for the duration of State’s lawsuit; rules Governor Walz acted within his authority',
},
{
	date: 'December 21, 2020',
    file: '2020/12/21_RestaurantTROs.asp',
    title: 'Attorney General’s office files for temporary restraining orders against Monticello, Anoka restaurants illegally operating on-premises dining',
    lede: 'TRO motion is next step in lawsuits against Cornerstone Cafe in Monticello and Cork in Anoka filed last Friday',
},
{
	date: 'December 21, 2020',
    file: '2020/12/21_EnforcementActions.asp',
    title: 'Attorney General’s office files three new enforcement actions against restaurants operating indoor on-premises dining illegally',
    lede: 'St. Patrick’s Tavern in New Prague, Pour House in Clarks Grove, and The Interchange in Albert Lea put community at risk by violating ban on indoor on-premises dining intended to slow the spread of COVID-19',
},
{
	date: 'December 18, 2020',
    file: '2020/12/18_EO_Enforcement_Update.asp',
    title: 'State of Minnesota enforcement authority and penalties for violations of executive orders: December 18, 2020 update',
    lede: '',
},
{
	date: 'December 18, 2020',
    file: '2020/12/18_AlibiDrinkery.asp',
    title: 'Court orders Lakeville restaurant to close for on-premises dining',
    lede: 'Must close or risk being found in contempt of court; hearing scheduled for December 22',
},
{
	date: 'December 18, 2020',
    file: '2020/12/18_EnforcementActions.asp',
    title: 'Attorney General’s office files new enforcement actions against Monticello and Anoka restaurants illegally operating on-premises dining',
    lede: 'Cork in Anoka and Cornerstone Cafe in Monticello put community at risk by violating ban on on-premises dining intended to slow the spread of COVID-19',
},
{
	date: 'December 17, 2020',
    file: '2020/12/17_RestaurantViolations_Update.asp',
    title: 'Attorney General’s office files for temporary restraining order against Lakeville restaurant illegally operating on-premises dining',
    lede: 'TRO motion is next step in lawsuit against Alibi Drinkery filed earlier today. Neighbors on the Rum in Princeton voluntarily closed for on-premises dining, now complying with executive order after lawsuit filed today',
},
{
	date: 'December 17, 2020',
    file: '2020/12/17_Google.asp',
    title: 'Attorney General Ellison sues to end Google’s illegal monopoly in internet search',
    lede: 'Joins bipartisan coalition of 38 attorneys general alleging Google illegally maintained a monopoly, created insurmountable barriers to entry for competitors',
},
{
	date: 'December 17, 2020',
    file: '2020/12/17_RestaurantViolations.asp',
    title: 'Attorney General’s office files enforcement actions against Lakeville and Princeton restaurants illegally operating on-premises dining',
    lede: 'Alibi Drinkery in Lakeville and Neighbors on the Rum in Princeton put community at risk by violating ban on on-premises dining intended to slow the spread of COVID-19',
},
{
	date: 'December 16, 2020',
    file: '2020/12/16_ExecutiveOrder20-99.asp',
    title: 'Attorney General’s office to hold accountable establishments openly violating Executive Order 20-99',
    lede: '',
},
{
	date: 'December 16, 2020',
    file: '2020/12/16_ExecutiveOrderEnforcement.asp',
    title: 'State of Minnesota Executive Order Enforcement Tools',
    lede: '',
},
{
	date: 'December 11, 2020',
    file: '2020/12/11_BoardwalkBar_Update.asp',
    title: 'Court orders E. Grand Forks establishment operating in violation of Executive Order 20-99 to close',
    lede: '',
},
{
	date: 'December 11, 2020',
    file: '2020/12/11_BoardwalkBar.asp',
    title: 'Attorney General Ellison acts again to enforce Executive Order 20-99',
    lede: 'Files lawsuit and motion for temporary restraining order against non-compliant East Grand Forks bar and restaurant that opened to the public and refused to close, putting community at risk ',
},
{
	date: 'December 10, 2020',
    file: '2020/12/10_Texas.asp',
    title: 'AG Ellison opposes Texas AG’s baseless effort to invalidate clear will of American voters',
    lede: 'Joins coalition of 23 AGs at Supreme Court to defend will of Georgia, Michigan, Pennsylvania and Wisconsin; urges court reject Texas AG’s suit, which lacks legal foundation, offers zero evidence of systemic voter fraud ',
},
{
	date: 'December 10, 2020',
    file: '2020/12/10_JUUL.asp',
    title: 'State adds tobacco giant Altria as defendant in JUUL lawsuit for deceptive marketing targeting youth',
    lede: 'Amends complaint to allege Altria, like JUUL, violated state consumer-protection laws, breached duty of reasonable care, created public nuisance. Minnesota only second state to name Altria as defendant in lawsuit against JUUL. ',
},
{
	date: 'December 9, 2020',
    file: '2020/12/09_Facebook.asp',
    title: 'Attorney General Ellison sues to end Facebook’s illegal monopoly',
    lede: 'Joins bipartisan coalition of 48 AGs in charging anticompetitive conduct — Facebook thwarted competition, reduced consumer privacy in pursuit of profits',
},
{
	date: 'December 4, 2020',
    file: '2020/12/04_PoliceShooting.asp',
    title: 'Attorney General, Washington County Attorney to review police-involved shooting',
    lede: 'Ramsey County Attorney refers November 28 Saint Paul police shooting; review of incident to begin after BCA completes investigation',
},
{
	date: 'December 2, 2020',
    file: '2020/12/02_PlainviewWellnessCenter.asp',
    title: 'Court closes gym that put community at risk by staying open in violation of executive order',
    lede: 'Wabasha County court grants Attorney General Ellison’s motion for temporary injunction; gym to temporarily close as required by Executive Order 20-99',
},
{
	date: 'November 25, 2020',
    file: '2020/11/25_ExecutiveOrder20-99.asp',
    title: 'Attorney General Ellison acts to enforce Executive Order 20-99',
    lede: 'Files lawsuit and restraining order against non-compliant Wabasha County fitness center that has remained open to the public and refused to close, putting community at risk',
},
{
	date: 'November 19, 2020',
    file: '2020/11/19_TaskForce.asp',
    title: 'Attorney General Ellison forms Task Force on Expanding Economic Security of Women',
    lede: 'Solicits applications through Open Appointments process by early January',
},
{
	date: 'November 18, 2020',
    file: '2020/11/18_Apple.asp',
    title: 'Attorney General Ellison reaches settlement with Apple over iPhone throttling',
    lede: 'Apple to pay Minnesota $2M as part of multistate consumer-fraud investigation by more than 30 AGs',
},
{
	date: 'November 13, 2020',
    file: '2020/11/13_Barr.asp',
    title: 'AG Ellison leads call to AG Barr to reverse new policy that ‘will erode the public’s confidence in the election’',
    lede: 'Co-leads letter of 23 AGs in voicing ‘strong objection’ to abrupt policy change that allows U.S. attorneys to pursue allegations of voter fraud without adhering to long-established guardrails',
},
{
	date: 'November 5, 2020',
    file: '2020/11/05_Floyd.asp',
    title: 'Attorney General Ellison: Ruling to keep George Floyd trial in Minneapolis is ‘another significant step forward in the pursuit of justice’',
    lede: 'Court also grants State’s motion to hold one trial for all four defendants, rather than separate trials',
},
{
	date: 'October 29, 2020',
    file: '2020/10/29_HutchinsonHealth.asp',
    title: 'Attorney General Ellison secures relief from unfair bill collection for Hutchinson Hospital patients',
    lede: 'After unilaterally increasing patients’ monthly medical bills, Hutchinson Hospital will restore lowest available monthly payments and refrain from future misconduct, in accordance with law and Hospital Agreement',
},
{
	date: 'October 27, 2020',
    file: '2020/10/27_VoteSafely.asp',
    title: 'Know your rights to vote safely and without intimidation',
    lede: 'One week from November 3 elections, Attorney General Ellison releases guidance for voters about federal and state laws that protect them from interference or intimidation',
},
{
	date: 'October 23, 2020',
    file: '2020/10/23_AtlasAegis.asp',
    title: 'Attorney General Ellison wins assurance Atlas Aegis will not recruit or provide private security for Minnesota elections',
    lede: 'Tennessee-based company admits statements it was recruiting private security for polling places are incorrect; agrees not to provide any security services in Minnesota around November 3 election',
},
{
	date: 'October 22, 2020',
    file: '2020/10/22_FloydRuling.asp',
    title: 'Attorney General Ellison: Ruling in Floyd case ‘important, positive step forward in the path toward justice’',
    lede: 'Court sustains eight of out nine total charges against defendants in murder of George Floyd',
},
{
	date: 'October 20, 2020',
    file: '2020/10/20_ElectionSecurity.asp',
    title: 'Attorney General Ellison investigating company reportedly recruiting private election security',
    lede: 'Ellison: ‘Minnesotans have every reason to expect our elections will be as safe and secure as they have always been’',
},
{
	date: 'October 20, 2020',
    file: '2020/10/20_SNAP.asp',
    title: 'Attorney General Ellison, coalition win halt to Trump Administration cuts to food assistance for 8,000 Minnesotans',
    lede: 'Federal judge ruled USDA’s ‘arbitrary and capricious’ food stamp rule change defied rulemaking procedure and congressional intent',
},
{
	date: 'October 20, 2020',
    file: '2020/10/20_CampaignEvents.asp',
    title: 'With two weeks before Election Day, Governor Walz, Attorney General Ellison encourage Minnesotans to participate in democracy safely',
    lede: 'Highlight efforts to ensure safe campaign events amid COVID-19 pandemic',
},
{
	date: 'October 12, 2020',
    file: '2020/10/12_Mallinckrodt.asp',
    title: 'Attorney General Ellison announces settlement with opioid manufacturer Mallinckrodt',
    lede: 'Settlement with 50 states and territories, local subdivisions to include $1.6B in cash, end to marketing of opioids, and public disclosure of documents',
},
{
	date: 'October 9, 2020',
    file: '2020/10/09_StudentLoanSettlements.asp',
    title: 'Attorney General Ellison secures relief for student-loan borrowers hurt by misconduct',
    lede: 'Former Minnesota ITT students to receive $1.6M in loan relief; California student-debt company to pay to fully refund Minnesota consumers for illegal fees',
},
{
	date: 'October 8, 2020',
    file: '2020/10/08_ConvictionReviewUnit.asp',
    title: 'Minnesota awarded federal grant to review legal cases for people believed to be innocent',
    lede: 'Attorney General’s Office to partner with Innocence Project of Minnesota on state’s first-ever Conviction Review Unit',
},
{
	date: 'October 1, 2020',
    file: '2020/10/01_HelpSealMyRecord.asp',
    title: 'AG Ellison, partners launch HelpSealMyRecord.org to increase access to expungements',
    lede: 'Prosecutors to actively assist Minnesotans statewide in obtaining expungements at no cost — will create more access to good jobs, education, housing',
},
{
	date: 'September 25, 2020',
    file: '2020/09/25_CRBard.asp',
    title: 'Attorney General Ellison announces $60M multistate settlement with C.R. Bard',
    lede: 'Minnesota joins group of 48 states in holding C.R. Bard accountable for misrepresenting the risks of its surgical mesh products; C.R. Bard to pay Minnesota over $1 million',
},
{
	date: 'September 24, 2020',
    file: '2020/09/24_PriceGouging.asp',
    title: 'AG Ellison lends support in court to states’ authority to regulate price-gouging',
    lede: 'Joins bipartisan coalition of 30 AGs in amicus brief arguing states’ price-gouging laws are necessary to protect vulnerable residents during emergencies',
},
{
	date: 'September 21, 2020',
    file: '2020/09/21_JourneyHomeMinnesota.asp',
    title: 'Attorney General Ellison secures repayment, permanent charitable-sector ban against former Journey Home Minnesota president',
    lede: 'Settlement requires Blake Huffman to repay $60K in charitable assets he misused from veterans-housing charity Journey Home Minnesota, permanently bans Huffman from operating a charity in Minnesota',
},
{
	date: 'September 16, 2020',
    file: '2020/09/16_OutreachCalling.asp',
    title: 'Attorney General Ellison shuts down alleged sham charity fundraiser that bilked millions from consumers',
    lede: 'Joins FTC, three other states in settlements that permanently prohibit defendants from charity fundraising business, require them to pay back nearly $900K for use by legitimate charities',
},
{
	date: 'September 1, 2020',
    file: '2020/09/01_Census.asp',
    title: 'Attorney General Ellison joins fight against Trump Administration attempts to cut Census short, undercount Minnesotans',
    lede: 'Reducing time for follow-up will put one of Minnesota’s congressional seats, federal funding at risk',
},
{
	date: 'August 29, 2020',
    file: '2020/08/29_EnvironmentalReview.asp',
    title: 'Attorney General Ellison sues Trump Administration for rule curtailing environmental review of federal actions',
    lede: 'Rule would limit Minnesotans’ participation, hurt vulnerable communities’ pursuit of environmental justice',
},
{
	date: 'August 26, 2020',
    file: '2020/08/26_Honda.asp',
    title: 'Attorney General Ellison announces $85 million multistate settlement with Honda',
    lede: 'Minnesota joins group of 48 states and territories in holding Honda accountable for using defective Takata airbags in its vehicles; Honda to pay Minnesota $1.5 million ',
},
{
	date: 'August 18, 2020',
    file: '2020/08/18_PostalService.asp',
    title: 'Attorney General Ellison sues Postal Service to stop dramatic changes that would undermine election, hurt Minnesotans',
    lede: 'Joins multistate coalition in federal lawsuit filed in Washington state alleging violations of federal law in implementing sudden, unilateral changes; cites Minnesota impacts ',
},
{
	date: 'August 14, 2020',
    file: '2020/08/14_MaskReseller.asp',
    title: 'Attorney General Ellison secures agreement to end illegal price gouging of face masks',
    lede: 'Saint Paul re-seller bought face masks from Minnesota businesses, resold them at unconscionably high prices around the country; will stop engaging in abusive sales during Governor’s peacetime emergency, will compensate customers',
},
{
	date: 'August 12, 2020',
    file: '2020/08/12_Leppink.asp',
    title: 'AG Ellison: Senate has ousted a champion of protecting workers and their families',
    lede: '‘They’ve thrown Nancy Leppink out of a job for protecting Minnesotans’ lives’',
},
{
	date: 'August 12, 2020',
    file: '2020/08/12_OttoBremerTrust.asp',
    title: 'Attorney General Ellison asks court to remove trustees of Otto Bremer Trust',
    lede: 'Petition details reckless attempt to sell Trust’s shares in Bremer Financial Corporation, knowing it would set off a ‘cascade of unfortunate consequences.’ Petition alleges a pattern of serious breaches, including self-dealing, excessive compensation and spending, hostile work environment, and shift in focus of trust from charitable to financial purposes',
},
{
	date: 'August 7, 2020',
    file: '2020/08/07_TaskforceReportAward.asp',
    title: 'Attorney General’s report on Lowering Pharmaceutical Drug Prices wins national award',
    lede: 'National Conference of State Legislatures recognizes report with 2020 Notable Document Award',
},
{
	date: 'July 31, 2020',
    file: '2020/07/31_NorthStarRanch.asp',
    title: 'Attorney General Ellison brings enforcement action against rodeo that defied COVID-19 safety precautions',
    lede: 'Sues to enforce Executive Order 20-74 against company that intentionally drew large crowds to its Itasca County rodeo without taking precautions against the spread of COVID-19. Company owner was counseled to follow State restrictions but refused to do so; at least one rodeo attendee was infectious, has now tested positive.',
},
{
	date: 'July 29, 2020',
    file: '2020/07/29_Landlords.asp',
    title: 'Attorney General Ellison wins relief for tenants without utilities during pandemic',
    lede: 'Resolves enforcement actions against two landlords who failed to provide utilities to tenants, in violation of Executive Order and state law',
},
{
	date: 'July 28, 2020',
    file: '2020/07/28_HHS.asp',
    title: 'AG Ellison calls for immediate withdrawal of directive that strips CDC of control over COVID-19 data',
    lede: 'Joins coalition of 22 AGs expressing serious concerns with new reporting structure that inhibits access to data',
},
{
	date: 'July 24, 2020',
    file: '2020/07/24_Census.asp',
    title: 'Attorney General Ellison Joins Lawsuit Against President Trump for Illegally Seeking to Exclude Undocumented Immigrants from Congressional Apportionment',
    lede: 'Coalition of States, Cities, and Counties Oppose President Trump’s Newest Ploy to Keep Undocumented Immigrants Out of Apportionment',
},
{
	date: 'July 20, 2020',
    file: '2020/07/20_HealthCareDiscrimination.asp',
    title: 'Attorney General Ellison sues Trump Administration to block health care discrimination',
    lede: 'Multistate suit seeks to block new HHS rule that targets LGBTQ+ people, people with limited English, and women',
},
{
	date: 'July 16, 2020',
    file: '2020/07/16_DeputyAttorneyGeneral.asp',
    title: 'AG Ellison names Luz María Frías as Deputy Attorney General',
    lede: '30-year veteran of legal, public, community service',
},
{
	date: 'July 15, 2020',
    file: '2020/07/15_DeVos.asp',
    title: 'AG Ellison sues Secretary DeVos to protect Minnesota students, taxpayers from fraud, deception, and abuse',
    lede: 'Lawsuit today to block DeVos from repealing fraud protections for student-loan borrowers; joins June lawsuit to stop DeVos from repealing prohibition on federal funding for schools that sell worthless degrees',
},
{
	date: 'July 14, 2020',
    file: '2020/07/14_StudentVisas.asp',
    title: 'Trump Administration rescinds proposed visa rules on international students after AG Ellison sues',
    lede: 'Coalition of 18 AGs fought the dramatic rules that would have hurt Minnesota’s schools, community, and economy',
},
{
	date: 'July 13, 2020',
    file: '2020/07/13_StudentVisas.asp',
    title: 'AG Ellison sues Trump Administration to stop new visa rule for international students',
    lede: 'Joins coalition of 18 AGs in fighting dramatic reversal that hurts Minnesota’s schools, community, and economy',
},
{
	date: 'July 13, 2020',
    file: '2020/07/13_Frontier.asp',
    title: 'AG Ellison settles with Frontier, concluding investigations into Minnesota telecoms providers',
    lede: 'Settlement to provide meaningful benefits to Frontier’s customers, many of whom live in Greater Minnesota',
},
{
	date: 'July 13, 2020',
    file: '2020/07/13_FloydCaseAttorneys.asp',
    title: 'Seasoned attorneys join AG Ellison’s team pro bono in George Floyd case',
    lede: 'Includes former acting U.S. Solicitor General Neal Katyal, Minnesota attorneys Lola Velázquez-Aguilu, Jerry Blackwell, and Steve Schleicher',
},
{
	date: 'July 2, 2020',
    file: '2020/07/02_MortgageReliefOptions.asp',
    title: 'AG Ellison, Gov. Walz, Lt. Gov. Flanagan announce financial institutions will provide additional mortgage-relief options to homeowners facing hardship due to COVID-19',
    lede: '31 Minnesota credit unions and banks to extend some CARES Act mortgage-relief options to customers without a federally-backed mortgage',
},
{
	date: 'July 1, 2020',
    file: '2020/07/01_AlecSmithAct.asp',
    title: 'AG Ellison: Big Pharma lawsuit to block Alec Smith Act ‘telling Minnesotans their obscene profits come before our lives’',
    lede: 'Minnesota Attorney General Keith Ellison issued the following statement about the lawsuit Big Pharma filed today to block the Alec Smith Insulin Affordability Act, which takes effect today.',
},
{
	date: 'June 24, 2020',
    file: '2020/06/24_ExxonKochAPI.asp',
    title: 'AG Ellison sues ExxonMobil, Koch Industries & American Petroleum Institute for deceiving, defrauding Minnesotans about climate change',
    lede: 'Claims violations of state and common law regarding consumer fraud, deceptive trade practices, misrepresentation, failure to warn; seeks injunctive relief, restitution, and corrective public education campaign. Minnesota joins growing list of states and local governments holding fossil-fuel industry accountable for decades-long ‘campaign of deception.’',
},
{
	date: 'June 12, 2020',
    file: '2020/06/12_DrugManufacturers.asp',
    title: 'AG Ellison again sues generic-drug manufacturers for conspiracy to fix drug prices and illegally allocate markets',
    lede: 'In Minnesota’s third lawsuit against ‘largest cartel in the history of the United States,’ AG Ellison joins coalition of 51 states and territories in suing 26 corporations for fixing prices and allocating markets on 80 topical dermatological drugs',
},
{
	date: 'June 12, 2020',
    file: '2020/06/12_MaxMason.asp',
    title: '‘One hundred years late, justice has been done’: AG Ellison hails posthumous pardon of Max Mason',
    lede: 'On 100th anniversary of infamous Duluth lynchings, State Board of Pardons grants first-ever posthumous pardon to African American man falsely accused and wrongly convicted; AG Ellison encouraged pardon application',
},
{
	date: 'June 3, 2020',
    file: '2020/06/03_GeorgeFloyd.asp',
    title: 'Attorney General Ellison charges Derek Chauvin with 2nd-degree murder of George Floyd, three former officers with aiding and abetting 2nd-degree murder',
    lede: '',
},
{
	date: 'June 2, 2020',
    file: '2020/06/02_Shadys.asp',
    title: 'Court protects Minnesotans’ lives, blocks bars from operating illegally',
    lede: 'Attorney General Ellison wins temporary injunction in ‘Shady’s’ case in Stearns County',
},
{
	date: 'May 30, 2020',
    file: '2020/05/30_Curfew.asp',
    title: 'Attorney General Ellison’s call for people to stay home tonight (May 30) after 8:00 p.m.',
    lede: '',
},
{
	date: 'May 26, 2020',
    file: '2020/05/26_ExecCouncilStatement.asp',
    title: 'Attorney General Ellison: Houses of worship “are not buildings,” they are “the people who use the buildings”',
    lede: 'Votes to approve Executive Order 20-26 — will continue to defend Governor’s emergency authority, uphold law and executive orders “without fear or favor or special treatment”',
},
{
	date: 'May 26, 2020',
    file: '2020/05/26_GeorgeFloyd.asp',
    title: 'Statement from Attorney General Ellison on death of George Floyd',
    lede: 'George Floyd mattered. Somebody loved him. His life was important. It had value. He lost it yesterday in an encounter with law enforcement that once again raises pain and trauma for so many people.',
},
{
	date: 'May 17, 2020',
    file: '2020/05/17_Shadys.asp',
    title: 'Attorney General Ellison files lawsuit to prevent six bars, restaurants from reopening illegally during COVID-19 emergency',
    lede: 'Seeks emergency relief to protect public from spread of COVID-19, ensure compliance with Stay Safe MN Executive Order',
},
{
	date: 'May 13, 2020',
    file: '2020/05/13_ExecutiveOrders.asp',
    title: 'AG Ellison: ‘Governor carefully turning the dial on reopening Minnesota’',
    lede: 'Attorney General supports new executive orders extending peacetime emergency, protecting workers and vulnerable people, and carefully turning the dial on reopening Minnesota',
},
{
	date: 'May 13, 2020',
    file: '2020/05/13_BdeMakaSka.asp',
    title: '‘Minnesotans no longer celebrate slavery and genocide’: AG Ellison hails Supreme Court decision upholding Bde Maka Ska name',
    lede: '‘We now have a sure way to reflect our values today and to pass along the state we want our children to inherit tomorrow’',
},
{
	date: 'May 12, 2020',
    file: '2020/05/12_EssentialWorkers.asp',
    title: '‘Essential workers are not disposable workers’: Attorney General Ellison urges President to protect meat-packing workers',
    lede: 'Joins coalition of 20 AGs in letter urging meaningful safety measures following President’s Executive Order to keep meat-processing plants open during pandemic',
},
{
	date: 'May 6, 2020',
    file: '2020/05/06_ACA.asp',
    title: 'Attorney General Ellison defends ACA in Supreme Court',
    lede: 'Joins broad coalition in filing opening brief opposite Trump Administration in case that will decide fate of 2.3 million Minnesotans with pre-existing conditions, among others',
},
{
	date: 'May 6, 2020',
    file: '2020/05/06_BeefPackingIndustry.asp',
    title: 'Attorney General Ellison urges federal investigation of beef-packing industry',
    lede: 'Joins bipartisan coalition of 11 AGs urging the Department of Justice pursue a federal investigation into coordinated market manipulation by meat packers in the cattle industry',
},
{
	date: 'May 4, 2020',
    file: '2020/05/04_Garnishment.asp',
    title: 'Attorney General Ellison: Executive order banning garnishment ‘will provide Minnesotans a little more peace of mind that they can afford their lives’ during pandemic',
    lede: 'AG Ellison proposed new executive order banning garnishment of CARES Act and other stimulus payments by debt collectors; AG’s office empowered to enforce order that will help Minnesotans keep roof over heads, food on table',
},
{
	date: 'April 30, 2020',
    file: '2020/04/30_StudentEducationCenter.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company in Minnesota',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State $122K to refund Minnesota customers',
},
{
	date: 'April 29, 2020',
    file: '2020/04/29_Paleti.asp',
    title: 'Attorney General Ellison sues to protect tenant from illegal eviction tomorrow',
    lede: 'Seeks emergency relief to protect Roseville tenant from being forced from his home tomorrow, in violation of Governor’s Executive Order suspending evictions during pandemic',
},
{
	date: 'April 28, 2020',
    file: '2020/04/28_Thao.asp',
    title: 'AG Ellison, SOS Simon reach agreement to expand access to voting',
    lede: 'Consent degree in <em>Thao v. Simon</em> means Minnesota may no longer enforce certain restrictions on assisting voters; will especially aid voters with language barriers and disabilities',
},
{
	date: 'April 28, 2020',
    file: '2020/04/28_ForsmanFarms.asp',
    title: 'Attorney General Ellison reaches price-gouging settlement on egg prices',
    lede: 'Howard Lake company’s egg prices increased 150 percent during pandemic; company agrees to limit prices during emergency',
},
{
	date: 'April 24, 2020',
    file: '2020/04/24_VideoHarassment.asp',
    title: 'Attorney General Ellison defends Minnesotans from video harassment',
    lede: 'Intervenes to defend constitutionality of state anti-harassment law in federal lawsuit filed by plaintiff who has videotaped congregants at Bloomington mosque that was bombed in 2017',
},
{
	date: 'April 23, 2020',
    file: '2020/04/23_RedStarTrader.asp',
    title: 'Attorney General Ellison puts an end to more online pandemic profiteering',
    lede: 'Saint Paul-based online retailer Red Star Trader bought essential goods in bulk, resold them at unconscionably excessive prices during the COVID-19 crisis; will stop engaging in abusive sales during the peacetime emergency',
},
{
	date: 'April 17, 2020',
    file: '2020/04/17_LaPlant.asp',
    title: 'Attorney General Ellison files another lawsuit to protect tenants from forced removal during COVID-19 pandemic',
    lede: 'Landlord who currently lives in Florida refuses to supply propane to Aitkin County tenants who are sheltering in place — AG seeks emergency relief for tenants from landlord’s violations of Governor’s Executive Order and landlord-tenant laws',
},
{
	date: 'April 16, 2020',
    file: '2020/04/16_Frontier.asp',
    title: 'Attorney General Ellison: Investigation into Frontier continues despite bankruptcy',
    lede: 'Will continue to protect Minnesota customers’ rights and fight for reform of Frontier’s business practices, despite chapter 11 bankruptcy filing',
},
{
	date: 'April 13, 2020',
    file: '2020/04/13_PeacetimeEmergency.asp',
    title: 'Attorney General Ellison: Extension of peacetime emergency protects Minnesotans’ lives and ability to afford their lives',
    lede: '',
},
{
	date: 'April 10, 2020',
    file: '2020/04/10_DivineEstates.asp',
    title: 'Attorney General Ellison sues another landlord for illegally forcing tenant to vacate during COVID-19 pandemic',
    lede: 'Files enforcement action against Meeker County landlord who repeatedly disconnected water to manufactured home in violation of Executive Order 20-14 and Minnesota law; seeks emergency injunctive relief to protect tenant',
},
{
	date: 'April 9, 2020',
    file: '2020/04/09_DefectiveProducts.asp',
    title: 'Attorney General Ellison leads fight for Americans’ right to hold companies accountable for defective products',
    lede: 'Co-leads bipartisan coalition of 40 attorneys general in asking U.S. Supreme Court not to limit plaintiffs’ right to hold manufacturers accountable for defective products in their home-state courts, in defense of Minnesota Supreme Court decision',
},
{
	date: 'April 8, 2020',
    file: '2020/04/08_CilekDecision.asp',
    title: 'Attorney General Ellison: Supreme Court <em>Cilek</em> decision ‘big win for Minnesota voters’ privacy’',
    lede: 'Minnesota Supreme Court holds Secretary of State was correct in restricting public access to non-public voter data, in case represented by Attorney General’s Office',
},
{
	date: 'April 8, 2020',
    file: '2020/04/08_StayAtHomeOrderExtension.asp',
    title: 'Attorney General Ellison urges compliance with extended Stay At Home order, will use power of AG’s office to enforce if necessary',
    lede: '‘Continuing to stay home is how we care for ourselves and each other’',
},
{
	date: 'April 7, 2020',
    file: '2020/04/07_Mostad.asp',
    title: 'Attorney General Ellison’s office wins halt to illegal removal of tenants during emergency',
    lede: 'Pine County District Court grants AG Office’s request for temporary restraining order; Landlord required to restore utilities and barred from taking further steps to interfere with tenants’ residency during COVID-19 emergency',
},
{
	date: 'April 6, 2020',
    file: '2020/04/06_MCAT.asp',
    title: 'Attorney General Ellison and U.S. Attorney MacDonald announce coordinated fight against unlawful activity related to COVID-19',
    lede: 'Minnesota COVID-19 Action Team to swiftly investigate, prosecute, and enforce state and federal law; AG Office’s to serve as centralized hub for reports of COVID-19-related unlawful activity; dedicated complaint form now live on AG website ',
},
{
	date: 'April 5, 2020',
    file: '2020/04/05_WalzSpeech.asp',
    title: 'Attorney General Ellison: Governor Walz delivers testament to Minnesota’s spirit and resilience',
    lede: 'Will keep helping all Minnesotans afford their lives and live with dignity and respect through the coming winter to the spring that will come — as spring always does',
},
{
	date: 'April 4, 2020',
    file: '2020/04/04_ACA.asp',
    title: 'Attorney General Ellison urges Trump Administration to follow Minnesota’s lead in opening up special ACA enrollment during COVID-19 pandemic',
    lede: 'While special enrollment for MNsure is open, opening it for Americans in 38 other states is ‘literally a matter of life and death’ for them',
},
{
	date: 'April 3, 2020',
    file: '2020/04/03_Mostad.asp',
    title: 'Attorney General Ellison enforces Executive Order against forcing tenants to vacate during COVID-19 pandemic',
    lede: 'Files enforcement action against Pine County landlord who disconnected utilities to force tenants out of their home while they were sheltering in place, in violation of Executive Order 20-14; seeks emergency injunctive relief to protect tenants',
},
{
	date: 'March 27, 2020',
    file: '2020/03/27_BartmannHospitality.asp',
    title: 'Attorney General Ellison asks Bartmann Hospitality, Inc. to reply to reports of withheld wages and gratuities',
    lede: 'Also offers guidance to workers whose wages have been withheld after a COVID-19 layoff or termination',
},
{
	date: 'March 27, 2020',
    file: '2020/03/27_DragonDoor.asp',
    title: 'Attorney General Ellison puts an end to more pandemic profiteering',
    lede: 'Little Canada business did not sell N95 face masks before start of COVID-19 crisis; will stop selling them for $5 each plus shipping, and will donate all masks to comply with Governor’s Executive Order',
},
{
	date: 'March 27, 2020',
    file: '2020/03/27_OnlineRetailers.asp',
    title: 'Attorney General Ellison warns major online retailers they are not exempt from ban on pandemic profiteering',
    lede: 'Joins bipartisan group of 32 AGs in letters to Amazon, Craigslist, eBay, Facebook, and Walmart urging them to block price-gouging by online sellers',
},
{
	date: 'March 25, 2020',
    file: '2020/03/25_StayAtHomeOrder.asp',
    title: 'Attorney General Ellison: Governor’s order to ‘Stay at Home’ is ‘firmly rooted in Minnesota law,’ ‘reasonable and necessary’',
    lede: 'Will vote to approve Order at Executive Council meeting later today',
},
{
	date: 'March 24, 2020',
    file: '2020/03/24_TenantEvictions.asp',
    title: 'Attorney General Ellison ready to enforce order suspending evictions during emergency',
    lede: 'New online complaint form available for tenants who believe landlords are violating Executive Order ',
},
{
	date: 'March 24, 2020',
    file: '2020/03/24_PandemicProfiteering.asp',
    title: 'Attorney General Ellison begins crackdown on COVID-19 pandemic profiteering',
    lede: 'AG’s office pursuing numerous investigations — files first Assurance of Discontinuance, sends warning letter to Menards',
},
{
	date: 'March 24, 2020',
    file: '2020/03/24_CovidPhishingScams.asp',
    title: 'Attorney General Ellison warns Minnesotans about COVID-19 phishing attacks',
    lede: 'Minnesota Attorney General Keith Ellison today warned Minnesotans about a reported spike in phishing attacks related to COVID-19, and offered advice about how to spot, avoid, and report them.',
},
{
	date: 'March 23, 2020',
    file: '2020/03/23_CovidCharityScams.asp',
    title: 'Attorney General Ellison warns of potential for COVID-19 charity scams',
    lede: 'With the number of confirmed COVID-19 cases rising in Minnesota, there is a risk that scammers will try to prey on the generosity of Minnesota donors by tricking them into donating to causes that claim to help COVID-19 patients or to alleviate the strain on overtaxed resources. ',
},
{
	date: 'March 20, 2020',
    file: '2020/03/20_PriceGouging.asp',
    title: 'Attorney General Ellison: Executive order banning ‘pandemic profiteering’ will ‘help Minnesotans afford their lives’',
    lede: 'AG worked closely with Governor to craft new executive order banning price-gouging on essential items during peacetime emergency',
},
{
	date: 'March 20, 2020',
    file: '2020/03/20_GovernorWalz.asp',
    title: 'AG Ellison: Governor is operating well within his statutory and constitutional authority',
    lede: 'Responds to Senate majority leader’s concern over Governor’s authority during peacetime emergency',
},
{
	date: 'March 13, 2020',
    file: '2020/03/13_CoronavirusScams.asp',
    title: 'AG Ellison: Protect yourself from COVID-19 scams, report price-gouging',
    lede: 'Minnesota Attorney General Keith Ellison today provided warnings, tips, and resources to Minnesota consumers so that they can be on the lookout for and protect themselves from scams related to the Coronavirus Disease 2019 (“COVID-19”).',
},
{
	date: 'March 11, 2020',
    file: '2020/03/11_T-Mobile.asp',
    title: 'AG Ellison wins protections for Minnesota consumers and jobs in T-Mobile settlement',
    lede: 'Protects current rate plans, requires low-cost wireless plans, extends low-income wireless access, protects jobs',
},
{
	date: 'February 24, 2020',
    file: '2020/02/24_WorkingGroup.asp',
    title: 'Working group releases consensus recommendations for reducing police-involved deadly force encounters',
    lede: '28 recommendations and 33 action steps cover community healing and engagement, prevention and training, investigations and accountability, policy and legal implications, and officer wellness. Diverse group convened by Attorney General Ellison and Public Safety Commissioner Harrington — only body of its kind in the country — completes six months of public hearings and listening sessions across Minnesota.',
},
{
	date: 'February 19, 2020',
    file: '2020/02/19_DPTF.asp',
    title: 'AG Task Force: Lower Rx drug prices by making markets work for people, using public power to make drugs more affordable, requiring more transparency and accountability',
    lede: 'Report and recommendations for legislative, legal, administrative, and patient-oriented action of Attorney General Ellison’s Task Force on Lowering Pharmaceutical Drug Prices released after nearly one year of study and deliberation. First-of-its-kind report sheds light on dysfunction of overly complex pharmaceutical-drug market that doesn’t work for people; also outlines main causes of high prices, including abuse of patent and exclusivity laws, anticompetitive practices, and PBMs’ business practices, among others.',
},
{
	date: 'February 6, 2020',
    file: '2020/02/06_FDIC.asp',
    title: 'Attorney General Ellison condemns federal effort to let predatory lenders take advantage of consumers',
    lede: 'FDIC rule would allow payday and other predatory lenders to skirt state usury laws; AG Ellison joins bipartisan coalition urging withdrawal of rule they say violates law, administrative authority',
},
{
	date: 'February 4, 2020',
    file: '2020/02/04_DreamCenterSchools.asp',
    title: 'Attorney General Ellison again requests loan discharge for students of Argosy University and Art Institutes International',
    lede: 'Co-leads bipartisan coalition of 26 AGs in asking Education Secretary to extend federal student loan discharge to all former students of closed Dream Center schools, including Argosy University and Art institutes International',
},
{
	date: 'January 24, 2020',
    file: '2020/01/24_3D-PrintedGuns.asp',
    title: 'Attorney General Ellison sues Trump Administration over effort to allow release of 3D-printed guns',
    lede: 'Federal judge found previous attempt to allow 3D-printed guns unlawful; states claim current attempt is unlawful for same reasons as previous attempt',
},
{
	date: 'January 17, 2020',
    file: '2020/01/17_Insys.asp',
    title: 'Attorney General Ellison and Pharmacy Board announce liquidation of opioid manufacturer Insys ',
    lede: 'Resolves litigation, disciplinary action that Attorney General and Board of Pharmacy filed against Insys, one of two opioid manufacturers AGO has sued. Bipartisan, multistate plan requires public disclosure of Insys’s documents, provides monetary relief to states, local governments, and tribes. ',
},
{
	date: 'January 17, 2020',
    file: '2020/01/17_Immigration.asp',
    title: 'Attorney General Ellison joins fight to halt immigration arrests at state courthouses',
    lede: 'Joins coalition of 14 AGs in amicus brief supporting Washington State lawsuit against DHS, ICE, and CBP ',
},
{ 
	date: 'January 16, 2020',
    file: '2020/01/16_SNAP.asp',
    title: 'Attorney General Ellison sues to stop Trump Administration from ending food assistance for more than 8,000 Minnesotans',
    lede: 'Joins coalition fighting USDA rule change that undermines law and congressional intent and would hurt nearly 700,000 nationwide  ',
},
{
	date: 'January 15, 2020',
    file: '2020/01/15_ComcastXfinity.asp',
    title: 'Attorney General Ellison obtains relief for more than 30,000 Comcast/Xfinity customers',
    lede: 'Comcast to issue refunds to 15,600 customers and provide debt relief to 16,000 more, together worth millions of dollars; must also disclose full amount it will charge customers',
},
{
	date: 'January 13, 2020',
    file: '2020/01/13_OttoBremerTrust.asp',
    title: 'Attorney General Ellison’s office opens investigation into Otto Bremer Trust',
    lede: 'Exercises broad authority to regulate charitable trusts by opening an investigation into the trust’s sale of its Bremer Financial shares',
},
{
	date: 'January 7, 2020',
    file: '2020/01/08_CenturyLinkSettlement.asp',
    title: 'Attorney General Ellison obtains nearly $9 million settlement with CenturyLink for overcharging Minnesota customers',
    lede: 'Settlement also requires CenturyLink to implement significant billing reforms, including disclosing its true prices, honoring all prices and discounts it promised, and banning sham internet fees',
},
{
	date: 'January 3, 2020',
    file: '2020/01/03_ReviewOfACADecision.asp',
    title: 'State of Minnesota joins coalition asking for Supreme Court review of ACA decision',
    lede: 'State and coalition ask for expedited review and resolution this term',
},
	
	];