var pr2025 = [
{
	date: 'April 16, 2025',
    file: '2025/04/16_SocialSecurity.asp',
    title: 'Attorney General Ellison defends Social Security from erratic, unlawful management',
    lede: 'Joins 21 AGs in amicus brief in support of injunction to block layoffs and mismanagement at Social Security Administration',
},
{
	date: 'April 15, 2025',
    file: '2025/04/15_PharmacyBenefitManagers.asp',
    title: 'Attorney General Ellison asks congress to prohibit pharmacy benefit managers from owning or operating pharmacies',
    lede: '',
},
{
	date: 'April 12, 2025',
    file: '2025/04/12_NLRB.asp',
    title: 'Attorney General Ellison again asks court to preserve National Labor Relations Board',
    lede: 'Co-leads coalition of 23 AGs in filing new brief in support of NLRB member Trump unlawfully attempted to remove',
},
{
	date: 'April 11, 2025',
    file: '2025/04/11_EO_LawFirms.asp',
    title: 'Attorney General Ellison challenges unconstitutional executive orders that undermine the rule of law',
    lede: 'Joins coalition of 21 AGs in amicus briefs in support of law firms Trump Administration targeted for retribution',
},
{
	date: 'April 10, 2025',
    file: '2025/04/10_EducationFunds.asp',
    title: 'Attorney General Ellison sues Trump Administration for blocking state education funds',
    lede: 'Joins multistate coalition in fight to restore access to funding that helps schools, teachers, and vulnerable students with long-term effects of COVID-19 ',
},
{
	date: 'April 10, 2025',
    file: '2025/04/10_VetsIndexes.asp',
    title: 'Minnesota Attorney General’s Office named top employer for veterans for 2nd year in a row',
    lede: 'VETS Indexes 4 Star Employer Award highlights AG Ellison’s commitment to hiring, retaining, and supporting veterans',
},
{
	date: 'April 10, 2025',
    file: '2025/04/10_OverdraftFees.asp',
    title: 'Attorney General Ellison seeks to protect consumers from high overdraft fees',
    lede: 'AG Ellison and 22 attorneys general urge House to reject resolution overturning CFPB’s rule limiting overdraft fee charges by big banks',
},
{
	date: 'April 10, 2025',
    file: '2025/04/10_HighLightVapes.asp',
    title: 'Attorney General Ellison wins court order banning sales of vapes disguised as highlighters',
    lede: 'Florida company High Light Vapes to stop doing business in Minnesota or pay $50K penalty in settlement of AG’s January 2025 lawsuit',
},
{
	date: 'April 9, 2025',
    file: '2025/04/09_LGBTQ-InclusiveBooks.asp',
    title: 'In SCOTUS brief, Attorney General Ellison defends use of LGBTQ-inclusive books in public schools',
    lede: 'Joins 19 AGs in filing amicus brief defending local discretion to incorporate LGBTQ-inclusive books into curriculum without opt-outs',
},
{
	date: 'April 8, 2025',
    file: '2025/04/08_CharterSchool.asp',
    title: 'Attorney General Ellison urges Supreme Court to reject creation of taxpayer-funded religious charter school',
    lede: 'Joins coalition of 18 AGs in asking Court to uphold ruling of Oklahoma Supreme Court that found approval of the school unconstitutional; argue charter schools must remain secular under First Amendment',
},
{
	date: 'April 7, 2025',
    file: '2025/04/07_MidwestCarSearch.asp',
    title: 'Court of Appeals unanimously affirms temporary injunction against used-car dealer Midwest Car Search',
    lede: 'Attorney General filed consumer-protection lawsuit against Midwest Car Search in April 2024; Court of Appeals unanimously affirms temporary injunction that requires Midwest Car Search to comply with state law until lawsuit is resolved',
},
{
	date: 'April 7, 2025',
    file: '2025/04/07_AndersonBrothers.asp',
    title: 'Asphalt contractor to pay nearly $1.3 million over falsified quality test results',
    lede: 'In addition to payments to the state and federal government, Anderson Brothers enters compliance agreement with MNDOT',
},
{
	date: 'April 4, 2025',
    file: '2025/04/04_ILMS.asp',
    title: 'Attorney General Ellison sues Trump Administration to protect libraries and museums',
    lede: 'AG Ellison joins coalition suing to stop dismantling of federal agencies that support libraries, museums, minority-owned businesses, and workers',
},
{
	date: 'April 4, 2025',
    file: '2025/04/04_NIH_Grants.asp',
    title: 'Attorney General Ellison sues Trump Administration over illegal NIH funding cuts, delays for medical and public health research',
    lede: 'NIH has awarded tens of millions of dollars to Minnesota in 2025: grant terminations will disrupt valuable research',
},
{
	date: 'April 3, 2025',
    file: '2025/04/03_HHS.asp',
    title: 'Attorney General Ellison secures order restoring $11 billion in critical public health funding',
    lede: '',
},
{
	date: 'April 3, 2025',
    file: '2025/04/03_EO_Elections.asp',
    title: 'Attorney General Ellison files lawsuit against Trump Administration over unlawful executive order seeking to impose sweeping voting restrictions',
    lede: 'Multi-state lawsuit asserts that voting restrictions are not authorized by U.S. Constitution or Congress',
},
{
	date: 'April 2, 2025',
    file: '2025/04/02_AcademicMedicine.asp',
    title: 'New chapter in negotiations on future of academic and clinical medicine, community health in Minnesota to begin as strategic facilitator selected',
    lede: 'AG Ellison invites public input on negotiations between University of Minnesota, Fairview, and Essentia Health; asks parties to ‘maximize this opportunity by exercising discretion and the honoring confidentiality of negotiations’',
},
{
	date: 'April 1, 2025',
    file: '2025/04/01_FederalLayoffs.asp',
    title: 'Attorney General Ellison wins preliminary injunction against Trump Administration for mass firings of federal probationary employees',
    lede: '',
},
{
	date: 'April 1, 2025',
    file: '2025/04/01_HHS.asp',
    title: 'Attorney General Ellison sues HHS, Kennedy to reverse illegal terminations of public health grants',
    lede: 'Co-leads coalition of 23 states and D.C. in lawsuit against illegal termination of $11B in critical public health grants, including $250M to Minnesota',
},
{
	date: 'March 31, 2025',
    file: '2025/03/31_WaterTaskforce.asp',
    title: 'Attorney General Ellison forms Task Force on Future of Minnesota’s Water',
    lede: 'Solicits applications through Open Appointments process; sets April 30 application deadline and June start to work of Task Force',
},
{
	date: 'March 31, 2025',
    file: '2025/03/31_SAVE-Act.asp',
    title: 'Attorney General Ellison leads opposition bill to that would create substantial barriers to voting',
    lede: 'Leads coalition of 18 attorneys general in letter to congressional leadership: so-called SAVE Act would effectively disenfranchise millions of eligible voters across the country',
},
{
	date: 'March 26, 2025',
    file: '2025/03/26_23andMe.asp',
    title: 'Attorney General Ellison issues consumer alert regarding 23andMe bankruptcy',
    lede: '',
},
{
	date: 'March 26, 2025',
    file: '2025/03/26_LegalCommunity.asp',
    title: '‘We stand for the rule of law’; Attorney General Ellison urges lawyers to ‘stand together’ in the face of Trump attacks, political retribution',
    lede: 'Joins 21 attorneys general in issuing open letter to legal community: Trump’s executive orders targeting law firms and the legal community are ‘unconstitutional on their face’',
},
{
	date: 'March 25, 2025',
    file: '2025/03/25_MVRealty.asp',
    title: 'Attorney General Ellison wins relief for Minnesotans deceived by MV Realty',
    lede: 'So-called “Homeowner Benefit Agreements” with hidden oppressive terms declared null and void',
},
{
	date: 'March 25, 2025',
    file: '2025/03/25_FederalFundingFreeze.asp',
    title: 'Attorney General Ellison takes action to stop Trump from withholding critical disaster relief funding',
    lede: 'AG Ellison joins coalition of 22 attorneys general seeking court order to stop freezing of FEMA funds',
},
{
	date: 'March 25, 2025',
    file: '2025/03/25_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office wins Top Workplace USA award for 4th year in a row',
    lede: 'Breaks into national top 100 of similar-sized workplaces for first time; highest-ranked of all similar-sized Minnesota workplaces; only state AG office in country so honored',
},
{
	date: 'March 24, 2025',
    file: '2025/03/24_DeptEducation.asp',
    title: 'Attorney General Ellison continues the fight to stop Trump from shutting down the Department of Education',
    lede: 'AG Ellison joins coalition seeking preliminary injunction to block mass layoffs and the elimination of core services at the Department of Education',
},
{
	date: 'March 19, 2025',
    file: '2025/03/19_Citibank.asp',
    title: 'Attorney General Ellison sues to preserve clean-energy dollars for Minnesota',
    lede: 'Co-leads coalition of four AGs in lawsuit against Trump administration for illegally blocking congressionally approved funds from flowing to state projects to reduce greenhouse gases; also sues Citibank to ensure funds are released as required by law',
},
{
	date: 'March 19, 2025',
    file: '2025/03/19_AcademicMedicine.asp',
    title: 'Attorney General Ellison announces new chapter in negotiations between University of Minnesota, Fairview, and Essentia',
    lede: 'Parties to take a look at all potential solutions for future of academic medicine in Minnesota with help of strategic facilitator',
},
{
	date: 'March 17, 2025',
    file: '2025/03/17_MedicaidFraud.asp',
    title: 'AG Ellison, Rep. Norris, Sen. Johnson Stewart introduce bipartisan bill cracking down on Medicaid fraud',
    lede: 'Bill would increase size of Medicaid Fraud Control Unit to keep up with increases in state Medicaid budget, add subpoena powers, and increase penalties for large theft',
},
{
	date: 'March 14, 2025',
    file: '2025/03/14_FederalLayoffs.asp',
    title: 'Attorney General Ellison wins temporary block on mass firings of federal probationary employees and gets fired employees their jobs back',
    lede: 'Federal judge orders 18 federal agencies to give employees their jobs back by Monday',
},
{
	date: 'March 14, 2025',
    file: '2025/03/14_MayoClinic.asp',
    title: 'Attorney General Ellison reaches settlement with Mayo Clinic over charity care and debt-collection practices',
    lede: 'Settlement requires Mayo Clinic to provide charity care to certain presumptively eligible patients and use a streamlined charity care application, and prohibits Mayo Clinic from suing patients to collect debt other than in exceptional circumstances',
},
{
	date: 'March 13, 2025',
    file: '2025/03/13_DeptEducation.asp',
    title: 'Attorney General Ellison sues to stop dismantling of Department of Education and protect students',
    lede: 'Joins coalition of 21 AGs in claiming dismantling Department violates Constitution and federal law, usurps Congress’s authority; seeks court order to halt shutdown',
},
{
	date: 'March 12, 2025',
    file: '2025/03/12_NLRB.asp',
    title: 'Attorney General Ellison again asks court to preserve National Labor Relations Board',
    lede: 'Co-leads second amicus brief in this case after court last week called President’s purported firing of Gwynne Wilcox ‘blatantly illegal’',
},
{
	date: 'March 12, 2025',
    file: '2025/03/12_PlannedParenthood.asp',
    title: 'Attorney General Ellison urges U.S. Supreme Court to defend Medicaid recipients’ freedom to choose their providers',
    lede: '17 states argue Medicaid Act gives patients the freedom to choose their own providers',
},
{
	date: 'March 7, 2025',
    file: '2025/03/07_Google.asp',
    title: 'Attorney General Ellison submits final proposed fix for ending Google’s illegal search-engine monopoly',
    lede: 'Joins bipartisan coalition of AGs and USDOJ in making final ask to court to prohibit Google from paying to be default search engine, require Google to share unlawfully obtained data with rivals, and divest Chrome browser, among other remedies',
},
{
	date: 'March 7, 2025',
    file: '2025/03/07_Skroch.asp',
    title: 'Attorney General Ellison files criminal complaint in death of Hardel Sherrell at Beltrami County Jail',
    lede: 'Michelle Skroch charged with second-degree manslaughter and two counts of criminal neglect arising from 2018 in-custody death',
},
{
	date: 'March 7, 2025',
    file: '2025/03/07_MCPSC.asp',
    title: 'Attorney General Ellison wins settlement dissolving nonprofits used to deceive Minnesotans',
    lede: 'Settlement also prevents nonprofits’ president from founding or leading nonprofits in the future and repays defrauded consumers',
},
{
	date: 'March 7, 2025',
    file: '2025/03/07_FederalLayoffs.asp',
    title: 'Attorney General Ellison files lawsuit to stop mass firings of federal probationary employees',
    lede: 'Co-leads coalition of 20 attorneys general in alleging Trump administration broke federal laws and rules in summary mass firings at federal agencies',
},
{
	date: 'March 6, 2025',
    file: '2025/03/06_NLRB.asp',
    title: 'Judge holds Trump termination of NLRB member unlawful and void',
    lede: 'Judge calls Wilcox’s firing “blatantly illegal.” Ruling follows an amicus brief AG Ellison filed in support of Wilcox',
},
{
	date: 'March 6, 2025',
    file: '2025/03/06_FederalFundingFreeze_PI.asp',
    title: 'Attorney General Ellison and multistate coalition secure court order blocking Trump Administration from freezing federal funds',
    lede: '',
},
{
	date: 'March 5, 2025',
    file: '2025/03/05_DEIA_Schools_JointGuidance.asp',
    title: 'Attorney General Ellison issues multistate guidance for schools on legal diversity, equity, inclusion and accessibility initiatives',
    lede: 'Joins coalition of 15 AGs in multistate response to executive order and misleading US Dept. of Education letter and FAQ to K-12 schools, colleges, and universities',
},
{
	date: 'March 5, 2025',
    file: '2025/03/05_NIH_PI.asp',
    title: 'Attorney General Ellison secures nationwide preliminary injunction against Trump Administration for defunding medical and public health innovation research',
    lede: '',
},
{
	date: 'March 1, 2025',
    file: '2025/03/01_EO_GenderAffirmingCare.asp',
    title: 'Court blocks Trump’s illegal orders targeting trans youth and gender-affirming care',
    lede: '',
},
{
	date: 'February 28, 2025',
    file: '2025/02/28_FederalFundingFreeze.asp',
    title: 'Attorney General Ellison takes action to enforce court order stopping Trump Administration’s illegal funding freeze',
    lede: '',
},
{
	date: 'February 28, 2025',
    file: '2025/02/28_NLRB.asp',
    title: 'Attorney General Ellison calls on court to keep Labor Board functioning',
    lede: 'Coalition of 20 attorneys general argues the unlawful dismissal of NLRB board member undermines the functioning of the NLRB and the enforcement of labor laws across America',
},
{
	date: 'February 28, 2025',
    file: '2025/02/28_Chop.asp',
    title: 'Jenup Stepen Chop sentenced to over 37 years for drive-by shooting homicide',
    lede: 'Chop convicted of 2nd Degree Murder – Drive-by Shooting, and two counts of Attempted Murder in the 1st Degree – Drive-by Shooting; received a total of 450 months in prison for committing a shooting involving multiple victims',
},
{
	date: 'February 21, 2025',
    file: '2025/02/21_DOGE.asp',
    title: 'Attorney General Ellison stops Elon Musk and DOGE from accessing Americans’ private information and cutting federal funds through the Treasury',
    lede: 'Ellison wins preliminary injunction barring Musk and DOGE from Treasury payment system while lawsuit proceeds',
},
{
	date: 'February 21, 2025',
    file: '2025/02/21_GenderAffirmingCare.asp',
    title: 'Attorney General Ellison calls on court to protect gender-affirming care',
    lede: 'Joins coalition of 18 attorneys general in amicus brief to support plaintiffs in PFLAG v. Trump',
},
{
	date: 'February 21, 2025',
    file: '2025/02/21_NIH.asp',
    title: 'Ahead of hearing, Attorney General Ellison issues joint statement on lawsuit to preserve funding for medical and public health innovation research',
    lede: '',
},
{
	date: 'February 20, 2025',
    file: '2025/02/20_EO_14201.asp',
    title: 'Barring students from participating in extracurricular activities consistent with their gender identity would violate the Minnesota Human Rights Act',
    lede: 'State High School League requests guidance on Trump Administration Executive Order',
},
{
	date: 'February 20, 2025',
    file: '2025/02/20_CFPB.asp',
    title: 'Attorney General Ellison defends CFPB from attempt to dismantle it',
    lede: 'Joins 22 other AGs in warning against efforts to defund and shutter the Consumer Financial Protection Bureau',
},
{
	date: 'February 19, 2025',
    file: '2025/02/19_CRU.asp',
    title: 'External audit praises Attorney General Ellison’s Conviction Review Unit',
    lede: 'Review calls Ellison’s Conviction Review Unit “a model for how statewide conviction integrity work should be done”',
},
{
	date: 'February 18, 2025',
    file: '2025/02/18_ExxonKochAPI.asp',
    title: 'Court upholds Attorney General Ellison’s lawsuit against ExxonMobil and others',
    lede: 'Lawsuit first filed in 2020 to continue in state court after judge largely denies defendants’ motion to dismiss',
},
{
	date: 'February 14, 2025',
    file: '2025/02/14_EO_GenderAffirmingCare_TRO.asp',
    title: 'Attorney General Ellison wins temporary protections for gender-affirming care in Minnesota',
    lede: 'Federal court order two-week halt to unconstitutional Trump order targeting gender-affirming care for youth in lawsuit by three attorneys general',
},
{
	date: 'February 14, 2025',
    file: '2025/02/14_ImmigrationEnforcement.asp',
    title: 'Attorney General’s Office releases guidance on legal responsibilities for Minnesota schools regarding federal immigration policy',
    lede: '',
},
{
	date: 'February 14, 2025',
    file: '2025/02/14_MedicalDebtReset.asp',
    title: 'Attorney General Ellison, Senator Boldon, and Representative Reyer announce Minnesota Medical Debt Reset Act',
    lede: 'Act invests $5 million to relieve an estimated $500 million in medical debt',
},
{
	date: 'February 13, 2025',
    file: '2025/02/13_DEI_Guidance.asp',
    title: 'Attorney General Ellison issues guidance for businesses on diversity, equity, inclusion, and accessibility employment initiatives in the workplace',
    lede: '16 attorneys general emphasize legality and importance of diversity, equity, inclusion and accessibility initiatives in hiring, retention and employee engagement',
},
{
	date: 'February 13, 2025',
    file: '2025/02/13_Musk.asp',
    title: 'Attorney General Ellison files landmark multistate lawsuit to stop Elon Musk’s unconstitutional power grab',
    lede: '',
},
{
	date: 'February 12, 2025',
    file: '2025/02/12_SaavedraOlivar.asp',
    title: 'Fredy Saavedra Olivar sentenced to more than 30 years for home invasion turned homicide',
    lede: 'Olivar convicted of 2nd degree murder and 1st degree burglary with a dangerous weapon; received a 366-month total sentence',
},
{
	date: 'February 11, 2025',
    file: '2025/02/11_CommunityBlacktop.asp',
    title: 'Attorney General Ellison shuts down asphalt fraudster',
    lede: 'Brandon Michael Ferguson and Community Blacktop, LLC agree to dissolve company and pay $100K to State in restitution for victimized consumers',
},
{
	date: 'February 10, 2025',
    file: '2025/02/10_NIH.asp',
    title: 'Attorney General Ellison sues Trump Administration for illegal cuts to medical and public health innovation research',
    lede: 'Joins coalition of 22 AGs in challenging NIH funding for universities and research institutions, alleging cuts violate federal law',
},
{
	date: 'February 7, 2025',
    file: '2025/02/07_DOGE.asp',
    title: 'Attorney General Ellison sues to stop Elon Musk and DOGE’s attacks on Americans',
    lede: '',
},
{
	date: 'February 7, 2025',
    file: '2025/02/07_EO_GenderAffirmingCare.asp',
    title: 'Attorney General Ellison sues to end unconstitutional presidential order criminalizing, ending funding for gender-affirming care',
    lede: '',
},
{
	date: 'February 6, 2025',
    file: '2025/02/06_ImmigrationDetainer.asp',
    title: 'Minnesota law prohibits law enforcement from holding someone on an immigration detainer if the person would otherwise be released from custody',
    lede: 'Attorney General’s Office issues formal opinion as authorized by law',
},
{
	date: 'February 6, 2025',
    file: '2025/02/06_DOGE.asp',
    title: 'Attorney General Ellison and coalition of 12 attorneys general release statement on DOGE access to sensitive personal information',
    lede: '',
},
{
	date: 'February 4, 2025',
    file: '2025/02/04_Schaefer.asp',
    title: 'Attorney General Ellison criminally charges Evergreen Acres Dairy owner with exploiting workers',
    lede: 'Keith Schaefer charged with four counts of wage theft, one count of felony racketeering for systematically depriving workers of wages and subjecting them to abuse',
},
{
	date: 'February 4, 2025',
    file: '2025/02/04_EmergingTechReport.asp',
    title: 'Attorney General Ellison releases report on AI and social media’s effects on young people',
    lede: 'Report describes harms caused, traces those harms to specific design features, and recommends solutions to state legislature',
},
{
	date: 'February 3, 2025',
    file: '2025/02/03_DeferredResignation.asp',
    title: 'Attorney General Ellison and 11 other attorneys general warn federal employees about misleading buyout offer',
    lede: '',
},
{
	date: 'January 31, 2025',
    file: '2025/01/31_FederalFundingFreeze.asp',
    title: 'Attorney General Ellison announces initial victory in lawsuit challenging President Trump’s illegal federal funding freeze',
    lede: 'Federal judge today issued Temporary Restraining Order to restore funding, orders Trump Administration not to withhold federal funding allocated by Congress',
},
{
	date: 'January 31, 2025',
    file: '2025/01/31_Trump-DEIA.asp',
    title: 'Joint statement from 12 state attorneys general: President Trump is misleading the American people on purpose of diversity, equity, inclusion, and accessibility initiatives',
    lede: '“His baseless and offensive claims that these initiatives somehow contributed to the tragic plane crash this week are an insult to those who are grieving and the individuals serving in the military and air traffic control.”',
},
{
	date: 'January 30, 2025',
    file: '2025/01/30_Singleton.asp',
    title: 'Attorney General Ellison sues nonprofits and their president for violations of Minnesota law arising out of a pattern of ongoing disruptive and deceptive conduct',
    lede: 'State files lawsuit against five nonprofits and their president, David Singleton, for using names, verbiage and images to create the false appearance of government affiliation and for failing to meet basic nonprofit charitable requirements',
},
{
	date: 'January 29, 2025',
    file: '2025/01/29_WAFCS.asp',
    title: 'Attorney General Ellison reaches settlement with cultural food bank and its president over misuse of funds, governance failures',
    lede: 'Settlement requires president to pay back charitable funds he spent on personal food, retail purchases, car expenses, monetary withdrawals, and more',
},
{
	date: 'January 28, 2025',
    file: '2025/01/28_FederalLoanFreeze.asp',
    title: 'Attorney General Ellison joins 22 states in suing to stop Trump Administration from withholding essential federal funding',
    lede: 'New Trump Administration policy would block trillions in funding for health, education, law enforcement, disaster relief, and other essential state programs',
},
{
	date: 'January 28, 2025',
    file: '2025/01/28_SJM-Properties.asp',
    title: 'Attorney General Ellison reaches settlement with sham nonprofit and its founder over violations of the Minnesota Nonprofit Corporation Act',
    lede: 'Previously, Attorney General Ellison sued nonprofit founder and landlord Steven Meldahl for living conditions at his properties that a judge compared to a “biblical plague”',
},
{
	date: 'January 27, 2025',
    file: '2025/01/27_NovoNordisk.asp',
    title: 'Attorney General Keith Ellison secures $35 Novo Nordisk insulin for Minnesotans',
    lede: 'For five years, insulin manufacturer Novo Nordisk agrees to cap out-of-pocket cost of its insulin treatments at $35 per month, and provide free insulin to the neediest Minnesotans',
},
{
	date: 'January 23, 2025',
    file: '2025/01/23_ImmigrationEnforcement.asp',
    title: 'AG Ellison: ‘U.S. Constitution prevents the federal government from commandeering states to enforce federal laws’',
    lede: 'Joins coalition of 12 attorneys general in joint statement on DOJ memo about compelling state and local law enforcement to enforce federal immigration law',
},
{
	date: 'January 23, 2025',
    file: '2025/01/23_TimeshareExit.asp',
    title: 'Attorney General Ellison cracks down on “timeshare exit” companies and issues consumer alert to avoid scams',
    lede: 'Investigations lead to settlements with three companies that violated Minnesota law in promising relief from timeshare debts; AG to refund nearly $270K to Minnesotans',
},
{
	date: 'January 21, 2025',
    file: '2025/01/21_BirthrightCitizenship.asp',
    title: 'Attorney General Ellison sues to block unconstitutional executive order on birthright citizenship',
    lede: 'Joins coalition of 22 jurisdictions in suing to defend basic constitutional rights for all Americans',
},
{
	date: 'January 17, 2025',
    file: '2025/01/17_Worth-v-Jacobson.asp',
    title: 'Attorney General Ellison appeals decision striking down Minnesota gun safety law to U.S. Supreme Court',
    lede: 'Ellison defends state ban on 18-to-20-year-olds carrying loaded handguns in public',
},
{
	date: 'January 16, 2025',
    file: '2025/01/16_HighLightVapes.asp',
    title: 'Attorney General Ellison sues e-cigarette manufacturer, launches investigation of another',
    lede: 'High Light Vapes promoted products as ‘stealthy’ way to vape because of ‘striking resemblance to actual highlighters’; AG alleges violations of state laws against marketing tobacco to children, consumer fraud',
},
{
	date: 'January 15, 2025',
    file: '2025/01/15_DACA_ACA.asp',
    title: 'Attorney General Ellison takes action to protect Affordable Care Act access for DACA recipients',
    lede: 'With incoming Trump administration expected to withdraw support, Minnesota and 13 others intervene to defend access to healthcare from court challenge',
},
{
	date: 'January 15, 2025',
    file: '2025/01/15_Deere.asp',
    title: 'Attorney General Ellison sues Deere & Company to protect farmers from high repair costs and unfair corporate tactics',
    lede: 'Deere’s monopoly practices unfairly drive up farming equipment repair costs, restrict farmers’ ability to quickly seek repairs necessary for planting, harvesting',
},
{
	date: 'January 10, 2025',
    file: '2025/01/10_CMCEO.asp',
    title: 'Attorney General Ellison reaches settlement with immigration charity to address governance deficiencies',
    lede: 'The AGO determined that several aspects of CMCEO’s governance required compliance improvements, including its contractor designations, financial controls, board procedures, and registration with the AGO.',
},
{
	date: 'January 8, 2025',
    file: '2025/01/08_Willis.asp',
    title: 'Attorney General Ellison charges one with $7.3M in Medicaid fraud prosecution',
    lede: 'Former felon Chavis Willis charged with racketeering, felony theft by swindle; was not eligible to operate Medicaid-funded business, billed for services not rendered ',
},
	
];



	
