var pr2022 = [
{
	date: 'December 28, 2022',
    file: '2022/12/28_3rdDegreeAssaultCharges.asp',
    title: 'Attorney General’s Office charges Justin Stetson with 3rd-degree assault in beating of Jaleel Stallings',
    lede: 'The office of Minnesota Attorney General Keith Ellison today charged Justin Stetson with one count of assault in the third degree under Minnesota Statutes Sec. 609.223, subd. 1 for the May 30, 2020 beating of Jaleel Stallings in Minneapolis. Stetson was a Minneapolis police officer at the time. A copy of the complaint is attached',
},
	{
	date: 'December 20, 2022',
    file: '2022/12/20_OpioidSettlements.asp',
    title: 'Attorney General Ellison signs onto $20B in new opioid settlements',
    lede: 'New settlements with five major manufacturers and pharmacies may bring more than $235 million to Minnesota over 15 years for opioid epidemic treatment and prevention; also require document disclosure, industry changes to ensure crisis never happens again',
},
{
	date: 'December 19, 2022',
    file: '2022/12/19_SanfordFairview.asp',
    title: 'Attorney General Ellison sets community meetings on proposed Fairview/Sanford merger',
    lede: 'Four community meetings to be held in Saint Paul, Bemidji, Worthington, and Grand Rapids in January 2023; AG Ellison to listen to Minnesotans’ views on the proposed merger',
},
{
	date: 'December 13, 2022',
    file: '2022/12/13_StudentLoanDebtRelief.asp',
    title: 'CFPB to issue $95M in restitution to consumers harmed by fraudulent student-loan debt-relief companies',
    lede: '912 Minnesota consumers to receive more than $1 million in restitution in lawsuit Minnesota filed jointly with CFPB. Companies charged illegal up-front fees for filling out and submitting forms for repayment and consolidation programs, which eligible borrowers can apply for on their own for free.',
},
{
	date: 'December 13, 2022',
    file: '2022/12/13_RightToStrike.asp',
    title: 'Attorney General Ellison defends right to strike at U.S. Supreme Court',
    lede: 'Joins coalition of 16 AGs in amicus brief in case that threatens workers’ rights and effectiveness of NLRB',
},
{
	date: 'December 1, 2022',
    file: '2022/12/01_CarMax.asp',
    title: 'Attorney General Ellison settles with CarMax over disclosure of safety recalls',
    lede: 'Minnesota joins bipartisan coalition of 36 states and territories in resolving claims CarMax falsely advertised the safety of vehicles with open recalls',
},
{
	date: 'November 22, 2022',
    file: '2022/11/22_Sanford-Fairview.asp',
    title: 'Attorney General Ellison announces public input on proposed merger of Fairview Health Services and Sanford Health',
    lede: 'Dedicated web form and phone numbers now available for public input, with public meetings to be held in early 2023; data gathered will form part of AG’s investigation under state and federal law into impact of merger',
},
{
	date: 'November 17, 2022',
    file: '2022/11/17_ExpressEnrollment.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company in Minnesota',
    lede: 'California-based company pocketed exorbitant fees for fraudulent ‘forgiveness’ scheme; will also pay State $50K to refund Minnesota customers',
},
{
	date: 'November 14, 2022',
    file: '2022/11/14_Google.asp',
    title: 'Attorney General Ellison reaches historic settlement with Google over location-tracking practices',
    lede: 'Joins 40 AGs in bipartisan national settlement worth almost $400M; Minnesota’s share $8.25M',
},
{
	date: 'November 7, 2022',
    file: '2022/11/07_Experian.asp',
    title: 'Minnesota joins $16M settlement over 2012 and 2015 Experian data breaches',
    lede: 'Minnesota to receive $280K civil penalty; Experian to provide 5 years of free credit monitoring; Experian and T-Mobile to improve data-protection services',
},
{
	date: 'November 4, 2022',
    file: '2022/11/04_USDA_Grant.asp',
    title: 'Attorney General Ellison applauds $15M grant to increase competition for meat and poultry processors, pledges vigilant antitrust enforcement',
    lede: 'Part of first round of USDA grants and investments designed to increase competition, increase small and mid-size producer income, create economic opportunity, and lower consumers’ costs',
},
{
	date: 'November 4, 2022',
    file: '2022/11/04_Opill.asp',
    title: 'Attorney General Ellison urges FDA approve country’s first over-the-counter birth-control pill',
    lede: 'If approved, pill would be available for purchase without a prescription, removing barriers to accessing safe and timely reproductive care',
},
{
	date: 'October 27, 2022',
    file: '2022/10/27_Shipt.asp',
    title: 'Attorney General Ellison sues Shipt for misclassifying ‘Shoppers’ as independent contractors instead of employees',
    lede: 'Alleges that Shipt ‘Shoppers’ are employees under Minnesota law and entitled to minimum wage, overtime, and other Minnesota employment protections',
},
{
	date: 'October 25, 2022',
    file: '2022/10/25_PMC.asp',
    title: 'Attorney General Ellison sues subcontractor for obstructing wage investigation, intimidating workers',
    lede: 'Alleges subcontractor threatened and discouraged workers from speaking with DLI and refused to provide DLI with the records it needs to determine whether the subcontractor violated Minnesota’s employment protections',
},
{
	date: 'October 24, 2022',
    file: '2022/10/24_Floyd.asp',
    title: 'J. Alexander Kueng pleads guilty to 2nd-degree manslaughter in death of George Floyd',
    lede: 'Co-defendant Tou Thao agrees to bench trial on 2nd-degree manslaughter on stipulated evidence; waives right to jury trial, right to present and confront witnesses, and testify in in his own defense; court to reach verdict in Thao’s case',
},
{
	date: 'October 18, 2022',
    file: '2022/10/18_OpioidSettlements.asp',
    title: 'First payments from landmark opioid settlements start flowing to Minnesota communities',
    lede: '$6.6M sent to Minnesota yesterday as part of $66 million coming this year; State to receive more than $300 million to fight the opioid crisis, with 75 percent going directly to hard-hit communities',
},
{
	date: 'October 18, 2022',
    file: '2022/10/18_PCMA.asp',
    title: 'Attorney General Ellison leads bipartisan coalition to regulate abusive practices of pharmacy benefit managers',
    lede: 'Leads bipartisan coalition of 35 AGs in amicus brief in support of Oklahoma’s laws, similar to Minnesota’s, regulating abusive behavior of PBMs',
},
{
	date: 'October 17, 2022',
    file: '2022/10/17_Enbridge.asp',
    title: 'Enbridge admits it breached aquifer in Line 3 construction, will pay fine and perform environmental restoration',
    lede: 'Attorney General Ellison files criminal charge for aquifer breach against Enbridge, along with diversion agreement contingent on Enbridge not breaking law again and fulfilling all terms of settlement; Clearwater County Attorney referred case to Attorney General for criminal prosecution',
},
{
	date: 'October 11, 2022',
    file: '2022/10/11_PublicNuisances.asp',
    title: 'Attorney General Ellison puts nuisance properties on formal notice they may be sued',
    lede: 'Along with Hennepin County and City of Minneapolis, provides notices to Merwin Liquors and Winner Gas Station in Minneapolis they are permitting or maintaining illegal public nuisances, may be sued in 30 days',
},
{
	date: 'October 7, 2022',
    file: '2022/10/07_StudentAidGroup.asp',
    title: 'Attorney General Ellison shuts down fraudulent student-loan debt-settlement company',
    lede: 'California-based company offering fraudulent ‘forgiveness’ scheme will pay State $15K to refund Minnesota consumers',
},
{
	date: 'October 5, 2022',
    file: '2022/10/05_FleetFarm.asp',
    title: 'Attorney General Ellison sues Fleet Farm for negligently selling firearms to straw purchasers',
    lede: 'Alleges Fleet Farm stores aided and abetted straw purchasers, should not have sold guns given warning signs of gun trafficking',
},
{
	date: 'October 3, 2022',
    file: '2022/10/03_WillisTraxler.asp',
    title: 'Attorney General Ellison secures guilty plea for son’s 2nd-degree murder of father',
    lede: 'Hardy Wills-Traxler pleads guilty in Le Sueur County for 2021 stabbing death of his father — prison sentence of 25 ½ years expected',
},
{
	date: 'September 30, 2022',
    file: '2022/09/30_Reinbold.asp',
    title: 'Attorney General Ellison secures conviction for 2nd-degree murder of mother',
    lede: 'Eric Reinbold convicted in Pennington County for stabbing wife to death after being released from federal prison on weapons charge; Reinhold evaded capture for 3 weeks',
},
{
	date: 'September 30, 2022',
    file: '2022/09/30_SyngentaCorteva.asp',
    title: 'Attorney General Ellison sues pesticides manufacturers for increasing costs for farmers',
    lede: 'Files federal lawsuit with FTC and bipartisan coalition of 10 AGs against Syngenta and Corteva for anticompetitive ‘loyalty programs’ that reduce competition, increase prices',
},
{
	date: 'September 28, 2022',
    file: '2022/09/28_USDA.asp',
    title: 'Attorney General Ellison applauds new federal funds to increase antitrust enforcement in agriculture',
    lede: 'Announcement of $15M available for state AGs to partner with USDA on agriculture competition issues follows bipartisan letter to Sec. Vilsack AG Ellison led recommending funding and increased partnership with AGs',
},
{
	date: 'September 26, 2022',
    file: '2022/09/26_FeedingOurFuture.asp',
    title: 'For two years, Attorney General Ellison’s office has held Feeding Our Future accountable',
    lede: 'Federal investigation and indictments would not have happened without Attorney General’s involvement',
},
{
	date: 'September 23, 2022',
    file: '2022/09/23_FundTexasChoice.asp',
    title: 'Attorney General Ellison moves to protect interstate travel to seek abortion',
    lede: 'Submits amicus brief with 22 AGs arguing Texas’ laws violate individuals’ constitutional right to interstate travel; follows commitment that no one traveling to Minnesota to seek or provide a legal abortion will be prosecuted',
},
{
	date: 'September 21, 2022',
    file: '2022/09/21_SummitManagement.asp',
    title: 'Attorney General Ellison protects more manufactured-housing residents',
    lede: 'AG Ellison conducts another successful law-enforcement effort against management company that threatened mass evictions of residents against Minnesota law; company commits to comply with the law and retract eviction threats',
},
{
	date: 'September 20, 2022',
    file: '2022/09/20_FeedingOurFuture.asp',
    title: 'AG Ellison: Civil investigation into Feeding Our Future continues after federal criminal indictment',
    lede: 'Scope of fraud alleged in federal indictments ‘breathtaking and immoral’; pledges to ‘hold bad actors accountable, no matter who they are’',
},
{
	date: 'September 19, 2022',
    file: '2022/09/19_Weiland.asp',
    title: 'Attorney General Ellison secures conviction in attempted murder of police officer, bystanders',
    lede: 'Devin Weiland convicted in Freeborn County for shooting Albert Lea police officer and two innocent bystanders in a November 2020 standoff during which he shot more than 80 rounds',
},
{
	date: 'September 15, 2022',
    file: '2022/09/15_PublicNuisances.asp',
    title: 'Attorney General Ellison investigating unlawful and dangerous public nuisances',
    lede: 'With assistance of Hennepin County Attorney’s Office, investigating whether Merwin Liquors and Winner Gas Station in Minneapolis are maintaining or permitting unlawful activity on their property',
},
{
	date: 'August 24, 2022',
    file: '2022/08/24_WelchCharities.asp',
    title: 'Attorney General Ellison shuts down mismanaged school-supply charity, secures permanent ban against president',
    lede: 'Charity was victim of insider misuse and governance violations; tens of thousands of dollars misused',
},
{
	date: 'August 23, 2022',
    file: '2022/08/23_CrisisPregnancyCenters.asp',
    title: 'Attorney General Ellison issues consumer alert about crisis pregnancy centers',
    lede: 'CPCs may provide misleading information about abortion and contraception, and often do not provide services they claim to offer; consumers encouraged to contact AG’s Office with concerns or complaints',
},
{
	date: 'August 22, 2022',
    file: '2022/08/22_ICWA.asp',
    title: 'Attorney General Ellison urges Supreme Court to protect Native American children and families',
    lede: 'Joins bipartisan coalition of 24 AGs in effort to prevent displacement of Native American children from tribal communities',
},
{
	date: 'August 17, 2022',
    file: '2022/08/17_FloridaVotingLaw.asp',
    title: 'Attorney General Ellison fights Florida’s discriminatory voting law in court',
    lede: 'Joins coalition supporting mail-in and drop-box voting, opposing Florida’s attempt to defend restrictive law that was already struck down in court',
},
{
	date: 'August 17, 2022',
    file: '2022/08/17_Endo.asp',
    title: 'Attorney General Ellison reaches $450M nationwide agreement with opioid maker Endo',
    lede: 'Settlement joined by 36 AGs comes as part of Endo bankruptcy proceedings; proposal would provide cash to address opioid crisis, ban promotion of Endo’s opioids, and require significant document disclosure',
},
{
	date: 'August 16, 2022',
    file: '2022/08/16_ITT.asp',
    title: '$26M in debt discharged for former ITT students as Biden Administration grants AG Ellison’s request',
    lede: 'U.S. Dept. of Ed. action followed bipartisan application, investigation, years of advocacy by AG Ellison. Nationwide, $39B in debt cancelled for 208K borrowers of now-defunct school.',
},
{
	date: 'August 12, 2022',
    file: '2022/08/12_NaturalGas.asp',
    title: 'Attorney General Ellison helps save utility customers nearly $60M',
    lede: 'After AG and partners intervene, PUC rules to disallow some natural gas costs utilities incurred during February 2021; rare for regulator not to allow utilities to pass entirety of gas costs onto customers',
},
{
	date: 'August 12, 2022',
    file: '2022/08/12_MNCretePools.asp',
    title: 'Attorney General Ellison sues pool contractor for defrauding Minnesota homeowners',
    lede: 'Alleges pool contractor lied about his experience, availability, progress, and refunds in order to take tens of thousands of dollars from victims',
},
{
	date: 'August 8, 2022',
    file: '2022/08/08_PoultryIndustry.asp',
    title: 'Attorney General Ellison leads fight to increase transparency in poultry industry',
    lede: 'Leads bipartisan coalition to support proposed USDA rule for increased transparency in the poultry processing; rule would make it easier for small farmers to compete for fair pricing terms from large processors',
},
{
	date: 'August 4, 2022',
    file: '2022/08/04_DontSayGayLaw.asp',
    title: 'Attorney General Ellison challenges Florida’s ‘Don’t Say Gay’ law in court',
    lede: 'Joins 16 AGs in brief arguing that extreme, discriminatory law lacks legitimate educational purpose, would harm students, parents, and teachers',
},
{
	date: 'August 4, 2022',
    file: '2022/08/03_TransgenderStudentsRights.asp',
    title: 'Attorney General Ellison fights to protect transgender students’ rights',
    lede: 'Joins coalition of 22 AGs in amicus brief to protect Indiana transgender student against discrimination',
},
{
	date: 'August 2, 2022',
    file: '2022/08/02_PSLFWaiver.asp',
    title: 'Attorney General Ellison calls for extension of student loan waiver for public servants, frontline workers',
    lede: 'Joins 20 AGs in urging Biden Administration to provide more time and opportunity for borrowers to achieve loan forgiveness under Public Service Loan Forgiveness program',
},
{
	date: 'August 2, 2022',
    file: '2022/08/02_Robocalls.asp',
    title: 'Attorney General Ellison investigating companies responsible for foreign robocalls',
    lede: 'Multistate investigation is first action of new nationwide, bipartisan Anti-Robocall Litigation Task Force',
},
{
	date: 'August 1, 2022',
    file: '2022/08/01_SafeHaven.asp',
    title: 'Attorney General Ellison halts deception in home security sales',
    lede: 'Safe Haven to pay $125K, comply with the law',
},
{
	date: 'July 29, 2022',
    file: '2022/07/29_Allergan.asp',
    title: 'Attorney General Ellison, states reach tentative $2.37B agreement with major opioid manufacturer Allergan',
    lede: 'Combined with Teva Pharmaceuticals deal announced earlier this week, settlement will bring tens of millions of dollars into Minnesota as opioid epidemic continues to be public-safety and public-health crisis',
},
{
	date: 'July 28, 2022',
    file: '2022/07/28_NAAQS.asp',
    title: 'Attorney General Ellison proposes new path for regulating greenhouse gases after Supreme Court decision',
    lede: 'Co-leads letter urging EPA use existing tool in Clean Air Act that would satisfy Supreme Court concerns in West Virginia v. EPA',
},
{
	date: 'July 28, 2022',
    file: '2022/07/28_Doe.asp',
    title: 'Attorney General Ellison, co-defendants will not appeal <em>Doe v. Minnesota</em>',
    lede: 'Attorney General must consider broad public interest in deciding whether to appeal; decision comes after three years of vigorous defense of laws in court at cost of more than $600K',
},
{
	date: 'July 27, 2022',
    file: '2022/07/27_HospitalAgreement.asp',
    title: 'Attorney General Ellison protects Minnesotans from unfair billing and collections with extension of Hospital Agreement',
    lede: 'Attorney General’s Office secures 5-year extension to ensure valuable protections for Minnesota patients continue through 2027',
},
{
	date: 'July 27, 2022',
    file: '2022/07/27_TEVA.asp',
    title: 'Attorney General Ellison, states reach tentative $4.25B agreement with major opioid manufacturer Teva',
    lede: 'Settlement in principle on financial terms will bring tens of millions of dollars into Minnesota as opioid epidemic continues to be public-safety and public-health crisis',
},
{
	date: 'July 27, 2022',
    file: '2022/07/27_LakeshoreManagement.asp',
    title: 'Attorney General Ellison succeeds in protecting Northfield manufactured-housing residents',
    lede: 'AG Ellison conducts successful law-enforcement effort against management company that imposed new leases and arbitrary, cruel new rules on residents against Minnesota law; company commits to update park rules in compliance with law and respond to residents’ concerns',
},
{
	date: 'July 11, 2022',
    file: '2022/07/11_GhostGuns.asp',
    title: 'Attorney General Ellison intervenes in court to regulate ghost guns',
    lede: 'Joins coalition of 20 AGs to support new, commonsense federal regulation under attack by Texas gun-parts distributor',
},
{
	date: 'July 7, 2022',
    file: '2022/07/07_Alexander.asp',
    title: 'Attorney General Ellison: ‘I support Dr. Alexander’s vision’ for Minneapolis policing, safety, and accountability',
    lede: 'Reacts to nomination of first director of new Minneapolis Department of Public Safety',
},
{
	date: 'July 7, 2022',
    file: '2022/07/07_Chauvin.asp',
    title: 'Attorney General Ellison: Federal prosecution of Derek Chauvin ‘appropriate and right’',
    lede: '‘Thoughts are with the victims’ as Chauvin sentenced to 245 months for depriving George Floyd and Jonathan Pope of their civil rights',
},
{
	date: 'July 6, 2022',
    file: '2022/07/06_JUUL.asp',
    title: 'Attorney General Ellison: FDA ordering all JUUL products off the market ‘does not impede State’s litigation’',
    lede: '‘We continue to prepare for trial’ scheduled for March 2023',
},
{
	date: 'June 28, 2022',
    file: '2022/06/28_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office named a top workplace for second year in a row',
    lede: 'Ranked #9 among midsize organizations, up from #51 in 2021; one of only 4 government entities to receive this honor',
},
{
	date: 'June 27, 2022',
    file: '2022/06/27_AbortionRights.asp',
    title: 'Attorney General Ellison joins AGs nationwide in reaffirming commitment to protecting abortion access',
    lede: 'Despite U.S. Supreme Court Dobbs decision, joins national coalition of 22 attorneys general to emphasize that abortion remains safe and legal in Minnesota and states across the country',
},
{
	date: 'June 21, 2022',
    file: '2022/06/21_AbortionRights.asp',
    title: 'Attorney General Ellison: No one will be prosecuted in Minnesota for a legal abortion',
    lede: 'Regardless of Supreme Court Dobbs decision expected to overturn Roe v. Wade, right to abortion is protected under Minnesota constitution: Ellison pledges to uphold it. AG also issues guidance to providers of abortion in Minnesota about their rights.',
},
{
	date: 'June 15, 2022',
    file: '2022/06/15_UnregulatedNicotine.asp',
    title: 'Attorney General Ellison urges FDA regulate non-tobacco nicotine products',
    lede: 'Joins bipartisan coalition of AGs in highlighting dangers of unregulated nicotine products and appeal to youth; letter comes as JUUL lawsuit scheduled for trial in 2023',
},
{
	date: 'May 25, 2022',
    file: '2022/05/25_ExecutiveOrder.asp',
    title: 'Attorney General Ellison attends ‘historic’ White House signing of executive order on policing and public safety',
    lede: 'Invited to White House event with law enforcement leaders and attorneys general on second anniversary of George Floyd’s death; ‘President Biden is taking historic action… Congress is still failing to do its part’',
},
{
	date: 'May 25, 2022',
    file: '2022/05/25_Floyd.asp',
    title: 'Attorney General Ellison: Two years later, Congress must pass George Floyd Justice in Policing Act',
    lede: 'On second anniversary of Floyd’s death, states, ‘True public safety and true accountability are not mutually exclusive; in fact, they go hand in hand’',
},
{
	date: 'May 24, 2022',
    file: '2022/05/24_Ford.asp',
    title: 'Attorney General Ellison reaches $19.2M multistate settlement with Ford',
    lede: 'Minnesota joins 40 other states and territories in resolving claims that Ford falsely advertised vehicles’ fuel economy and payload capacity; Ford to pay State $320K',
},
{
	date: 'May 18, 2022',
    file: '2022/05/18_MinnesotaCameroonCommunity.asp',
    title: 'Attorney General Ellison secures agreement to strengthen governance of charity serving Cameroonian community',
    lede: 'Poor governance allowed charity’s community center to fall into disrepair',
},
{
	date: 'May 18, 2022',
    file: '2022/05/18_ThomasLane.asp',
    title: '‘Pleased Thomas Lane has accepted responsibility’: Attorney General Ellison statement on guilty plea in death of George Floyd',
    lede: 'Say plea is ‘important step toward healing the wounds of the Floyd family, our community, and the nation’ and ‘a necessary resolution on the continued journey to justice’',
},
{
	date: 'May 6, 2022',
    file: '2022/05/06_OpioidsSettlementFundsBill.asp',
    title: 'Attorney General Ellison hails ‘historic and momentous’ passage of opioids bill in Legislature',
    lede: '‘No amount of money can ever make up for the death and destruction the opioid companies caused,’ but overwhelming bipartisan support for the passage of the bill will allow $300M to begin to flow to Minnesota communities for treatment, remediation, and prevention',
},
{
	date: 'May 5, 2022',
    file: '2022/05/05_Intuit.asp',
    title: 'Attorney General Keith Ellison secures $1.8M for low-income Minnesotans deceived by TurboTax',
    lede: 'Joins all 50 states in agreement with TurboTax owner Intuit for deceiving low-income Americans into paying for free tax services; as many as 60,000 Minnesotans to be refunded',
},
{
	date: 'May 4, 2022',
    file: '2022/05/04_StudentLoanDebt.asp',
    title: 'Attorney General Ellison calls for full cancelation of federal student loan debt',
    lede: 'Joins AG coalition urging President Biden to cancel all publicly held debts for student borrowers',
},
{
	date: 'April 29, 2022',
    file: '2022/04/29_OBT.asp',
    title: 'Attorney General Ellison Hails Court’s Decision to Remove Otto Bremer Trustee as Victory',
    lede: 'Ramsey County District Court orders removal of Otto Bremer Trustee Brian Lipschultz, terminates self-dealing investment fee, and sets process to appoint successor',
},
{
	date: 'April 26, 2022',
    file: '2022/04/26_Brio.asp',
    title: 'Attorney General Ellison sues solar-panel sales companies, lenders for defrauding Minnesota homeowners',
    lede: 'Alleges solar companies lied about their relationship with Minnesota utilities, misrepresented financial benefits of purchasing solar panels, and tricked consumers into signing binding sales contracts and loan agreements',
},
{
	date: 'April 12, 2022',
    file: '2022/04/12_FeedingOurFuture.asp',
    title: 'Court grants Attorney General Ellison’s petition for court supervision of Feeding Our Future’s dissolution',
    lede: 'Grants request for accountability and transparency during dissolution',
},
{
	date: 'April 6, 2022',
    file: '2022/04/06_Locke_Statement.asp',
    title: 'AG Ellison: ‘Amir Locke was not a suspect, he was a victim’',
    lede: 'Names curbing no-knock warrants, passing George Floyd Act, Minneapolis getting serious about ending police-involved deaths as steps to keeping deaths like Amir Locke’s from happening again',
},
{
	date: 'April 6, 2022',
    file: '2022/04/06_Locke.asp',
    title: 'No charges to be filed in death of Amir Locke',
    lede: 'Cite ‘ethical obligation as prosecutors to only bring criminal charges which are supported by sufficient admissible evidence to sustain a conviction.’ Call on policy makers to ‘seriously weigh the benefits of no-knock warrants, which are dangerous for both law enforcement and the public alike’',
},
{
	date: 'March 29, 2022',
    file: '2022/03/29_ParentalControls.asp',
    title: 'Attorney General Ellison joins bipartisan coalition urging TikTok and Snapchat to give parents more control',
    lede: 'AG Ellison among 44 AGs asking platforms to give parents the ability to monitor children’s social media usage',
},
{
	date: 'March 28, 2022',
    file: '2022/03/28_PhilandoFeedsTheChildren.asp',
    title: 'Attorney General Ellison secures $120K repayment from fundraiser who did not properly spend funds raised in Philando Castile’s name',
    lede: 'In settlement of AG’s June 2021 lawsuit, Pamela Fergus ordered to pay back all funds unaccounted for; permanently banned from managing charitable money',
},
{
	date: 'March 23, 2022',
    file: '2022/03/23_Meldhal.asp',
    title: 'Minneapolis landlord ordered to reimburse State $1M in legal fees after violating tenants’ rights',
    lede: 'Hennepin County court makes award after November 2021 ruling that Steven Meldahl engaged in ‘brazen and deplorable illegal business conduct,’ allowed tenants to live in infestations ‘of Biblical plague proportions’',
},
{
	date: 'March 17, 2022',
    file: '2022/03/17_VFW_CharitableAssociation.asp',
    title: 'Attorney General Ellison secures agreement to strengthen governance and oversight practices of Minnesota veterans charity',
    lede: 'Charity was the victim of insider misuse and governance violations',
},
{
	date: 'March 8, 2022',
    file: '2022/03/08_WESTF.asp',
    title: 'On International Women’s Day, Attorney General Ellison’s task force releases report and recommendations for expanding women’s economic security',
    lede: 'First-of-its-kind report builds on gains of 2014 Women’s Economic Security Act, identifies additional barriers to women’s equal participation in the economy, offers 115 short-, medium-, and long-term recommendations to advance women’s economic prosperity in Minnesota',
},
{
	date: 'March 3, 2022',
    file: '2022/03/03_XiaoyanHu.asp',
    title: 'Attorney General Ellison charges doctor with $1.6M in Medicaid fraud',
    lede: 'Charged with 17 felony counts of theft by false representation',
},
{
	date: 'March 3, 2022',
    file: '2022/03/03_FeedingOurFuture.asp',
    title: 'Attorney General Ellison discloses ongoing investigation into Feeding Our Future, seeks court control over nonprofit',
    lede: 'Seeks court supervision over Feeding Our Future and its assets pending dissolution and AGO and federal criminal investigations',
},
{
	date: 'March 2, 2022',
    file: '2022/03/02_TikTok.asp',
    title: 'Attorney General Ellison joins nationwide investigation into TikTok’s impact on young people',
    lede: 'Bipartisan coalition of AGs concerned for safety and well-being of children',
},
{
	date: 'March 2, 2022',
    file: '2022/03/02_TMobileDataBreach.asp',
    title: 'After T-Mobile data found on dark web, Attorney General Ellison urges Minnesotans to protect personal information from identity theft',
    lede: 'Millions of personal records recently found for sale on dark web from August 2021 T-Mobile data breach that affected 670K Minnesotans, 53M Americans',
},
{
	date: 'February 28, 2022',
    file: '2022/02/28_Argosy.asp',
    title: 'Attorney General Ellison leads multistate action that secures $2.1M in private debt relief for former Argosy University students',
    lede: 'Entities controlling Argosy student debt agree to cancel private debt across 12 campuses nationwide; includes $135K in relief for former students of Eagan campus, bars further collection and negative credit reporting. Also resubmits bipartisan request for federal student debt relief for Argosy students',
},
{
	date: 'February 25, 2022',
    file: '2022/02/25_OpioidSettlement.asp',
    title: '$26B settlement with opioid distributors, Johnson & Johnson wins final approval',
    lede: 'Minnesota to receive $303 million over 18 years to fight the opioid crisis; amounts local governments to receive released. Commitment follows historic December agreement between State and cities and counties on allocation and use of funds; money to flow as soon as second quarter if legislative changes made',
},
{
	date: 'February 24, 2022',
    file: '2022/02/24_FloydVerdict.asp',
    title: 'Attorney General Ellison: ‘Verdict honors Floyd’s memory’',
    lede: 'Reacts to verdict in federal civil-rights trial of former officers Kueng, Lane, and Thao in death of George Floyd: verdict vindicates ‘principle that officers have a duty and a responsibility to intervene and render medical care’',
},
{
	date: 'February 24, 2022',
    file: '2022/02/24_UnitedHealthGroup.asp',
    title: 'Attorney General Ellison sues to block UnitedHealth Group proposed acquisition of Change Healthcare',
    lede: 'Joins USDOJ, State of New York to sue UnitedHealth Group and Change Healthcare after investigation found merger would increase healthcare costs',
},
{
	date: 'February 18, 2022',
    file: '2022/02/18_KimberlyPotter.asp',
    title: 'Attorney General Ellison: ‘The work of justice continues’',
    lede: 'Sentencing of Kimberly Potter ‘takes nothing away from the truth of the jury’s verdict.’ Justice is ‘accountability, compassion, mercy, and healing’',
},
{
	date: 'February 10, 2022',
    file: '2022/02/10_HavenBrookHomes.asp',
    title: 'Attorney General Ellison sues HavenBrook Homes, one of the largest landlords in Minnesota, for failing to repair rental homes, violating law',
    lede: 'Lawsuit alleges hedge fund-owned mega-landlord failed to repair and maintain rental homes that lacked heat, had backed-up sewers, doors and windows that would not close, mold, even wild animals — and when it did, violated Minnesota’s lead-paint rules',
},
{
	date: 'February 4, 2022',
    file: '2022/02/04_AmirLocke.asp',
    title: '‘Amir Locke’s life mattered… I promise to conduct a fair and thorough review guided by accountability and transparency’',
    lede: 'Attorney General Keith Ellison statement on death of Amir Locke',
},
{
	date: 'February 3, 2022',
    file: '2022/02/03_SuiteLivn.asp',
    title: 'Attorney General Ellison obtains refunds for Greater Minnesota tenants illegally charged fees',
    lede: 'New unit in AGO reaches settlement that requires landlord Suite Liv’n to refund 877 tenant households in Marshall, Willmar, New London, and Spicer a utility surcharge the company imposed on its tenants in violation of Minnesota’s utility billing law',
},
{
	date: 'February 2, 2022',
    file: '2022/02/02_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office named Top Workplace USA',
    lede: 'After being named a Star Tribune Top Workplace for the first time ever, Attorney General’s Office now named a Top Workplace USA',
},
{
	date: 'January 19 2022',
    file: '2022/01/19_CenterForCovidControl.asp',
    title: 'Attorney General Ellison files lawsuit against COVID-19 testing sites, lab for deceiving consumers',
    lede: 'Attorney General alleges Center for COVID Control never sent test results, sent results far later than advertised, or sent false or inaccurate results to consumers',
},
{
	date: 'January 18 2022',
    file: '2022/01/18_Davis.asp',
    title: 'AG Ellison’s office obtains guilty plea in $860K Medicaid fraud case',
    lede: 'Ringleader Trenea Davis pleads guilty to 5 charges in case AG filed in January 2021',
},
{
	date: 'January 13 2022',
    file: '2022/01/13_Navient.asp',
    title: 'Attorney General Ellison Announces $1.85 Billion Settlement with Student Loan Servicer Navient',
    lede: 'Settlement includes Significant Changes to Servicing and Lending Practices; $1.7 billion in debt cancellation and $95 million in restitution nationwide; and Additional Monetary Payments',
},
{
	date: 'January 6, 2022',
    file: '2022/01/06_ArbitrationCases.asp',
    title: 'Attorney General Ellison urges Supreme Court to protect employees and consumers from corporate gamesmanship in pending arbitration cases',
    lede: 'Leads a bipartisan amicus brief asking the Court to ensure that companies cannot seek two bites at the apple by strategically defending cases in court for months, and then seeking to compel arbitration if their court strategy is unsuccessful',
},
{
	date: 'January 5, 2022',
    file: '2022/01/05_Ellison.asp',
    title: 'Attorney General Ellison tests positive for COVID-19, has mild symptoms thanks to vaccination and booster',
    lede: 'Isolating in place out of the country until safe to travel home, conducting business as usual',
},
{
	date: 'January 3, 2022',
    file: '2022/01/03_MeatProcessingIndustry.asp',
    title: 'Attorney General Ellison welcomes Biden Administration plan to strengthen competition in meatpacking',
    lede: 'Plan today comes in wake of bipartisan letter AG Ellison led to USDA Sec. Vilsack, asking for greater enforcement to ensure fairness and integrity for Minnesota farmers, ranchers, and consumers',
},
];