var pr2024 = [
{
	date: 'December 23, 2024',
    file: '2024/12/23_ImmigrationScams.asp',
    title: 'SCAM STOPPER: Attorney General Ellison shares alert on immigration scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from common scams. ',
},
{
	date: 'December 20, 2024',
    file: '2024/12/20_Evergreen.asp',
    title: 'Attorney General Ellison praises indictment of Evergreen Recovery leaders for Medicaid fraud',
    lede: 'US Attorney’s Office worked closely with AG Ellison’s Medicaid Fraud Control Unit to investigate, secure indictments',
},
{
	date: 'December 19, 2024',
    file: '2024/12/19_AriseVirtualSolutions.asp',
    title: 'Attorney General Ellison wins restitution for workers that gig-work company misclassified',
    lede: 'Arise Virtual Solutions to pay $300K to customer service workers it misclassified as independent contractors, stop doing business in Minnesota',
},
{
	date: 'December 16, 2024',
    file: '2024/12/16_TempleIsrael.asp',
    title: '“Painting swastikas on a synagogue is an appalling act of hate”',
    lede: 'Minnesota Attorney General Keith Ellison released the following statement after two swastikas were found painted outside the entrance to Temple Israel, a synagogue in Minneapolis',
},
{
	date: 'December 12, 2024',
    file: '2024/12/12_Glock.asp',
    title: 'Attorney General Ellison sues Glock for making and selling handguns that can easily be turned into machine guns',
    lede: 'Glock, which dominates the American handgun market, has known since at least 1988 that ‘Glock switches’ quickly and easily convert Glock handguns into illegal machine guns, yet refuses to make design choices to discourage this conversion and promotes ‘fun’ of machine guns',
},
{
	date: 'December 12, 2024',
    file: '2024/12/12_Navarro.asp',
    title: 'Austin Navarro sentenced to 25 years for murder of 2-year-old child',
    lede: 'Navarro convicted of 2nd degree murder; received a 25-year sentence based on aggravating factors',
},
{
	date: 'December 10, 2024',
    file: '2024/12/10_MinnesotaTobaccoSettlement.asp',
    title: 'Attorney General Ellison recovers more than $58M in underpayments from Big Tobacco',
    lede: 'Philip Morris and RJ Reynolds tried to use a 2018 tax cut to justify underpaying Minnesota by roughly $10M per year under historic tobacco settlement',
},
{
	date: 'December 5, 2024',
    file: '2024/12/05_Hang.asp',
    title: 'Attorney General Ellison sues former charter-school superintendent who lost more than $4M in illegal investment with hedge fund',
    lede: 'Civil action seeks return of funds from Christianna Hang. Separately, AG mandates reforms in settlement with Hmong College Prep Academy, alleging board members did not properly oversee Hang.',
},
{
	date: 'December 3, 2024',
    file: '2024/12/03_GarGaar.asp',
    title: 'Attorney General Ellison shuts down charity after investigation finds self-dealing transactions and governance violations',
    lede: 'In the settlement, filed in Hennepin County District Court, the Attorney General alleges that Gar Gaar paid more than $100,000 to a for-profit company owned by two of Gar Gaar’s officers and that an audit found several significant deficiencies in Gar Gaar’s internal controls, among other issues.',
},
{
	date: 'November 26, 2024',
    file: '2024/11/26_LDFHoldings.asp',
    title: 'Attorney General Ellison secures consent order stopping high-cost online lenders and discharging illegal loans',
    lede: 'Consent order is result of settlement with consortium of online lenders, halting further lending at illegal 200-800% interest rates and cancelling existing loan balances likely totaling over $1M ',
},
{
	date: 'November 26, 2024',
    file: '2024/11/26_Humana_Medicare.asp',
    title: 'Attorney General Ellison urges Humana to correct misinformation regarding Medicare Advantage',
    lede: 'Major health care providers no longer accepting certain Medicare Advantage Plans, dramatically changing care options for over 60,000 Minnesotans. Humana reportedly advertised to consumers that certain providers would be in-network when that is not the case.',
},
{
	date: 'November 25, 2024',
    file: '2024/11/25_Medicare.asp',
    title: 'Attorney General Ellison issues alert to seniors with Medicare Advantage',
    lede: 'Major health care providers no longer accepting certain Medicare Advantage Plans, dramatically changing care options for over 60,000 Minnesotans',
},
{
	date: 'November 21, 2024',
    file: '2024/11/21_Conagra.asp',
    title: 'Attorney General Ellison reaches $142K settlement with Conagra over employment statements',
    lede: 'Conagra to provide compliant employment statements, pay restitution to workers for past non-compliance',
},
{
	date: 'November 21, 2024',
    file: '2024/11/21_Google.asp',
    title: 'Attorney General Ellison proposes remedies for ending Google’s illegal search-engine monopoly',
    lede: 'Joins bipartisan coalition of AGs and USDOJ in asking court to prohibit Google from paying to be default search engine, require Google to share unlawfully obtained data with rivals, and divest Chrome browser, among other remedies',
},
{
	date: 'November 19, 2024',
    file: '2024/11/19_EdinaRealty.asp',
    title: 'Attorney General Ellison reaches $3.5 million settlement with Edina Realty',
    lede: 'Settlement resolves investigation into Edina’s alleged breaches of fiduciary duties firm owes its clients; Edina will provide refunds for consumers and reforms to its business practices going forward ',
},
{
	date: 'November 8, 2024',
    file: '2024/11/08_UrbanAdvantageServices.asp',
    title: 'Attorney General Ellison requires charity to dissolve over governance violations',
    lede: 'Urban Advantage Services failed to register and meet basic governance standards, abandoned charitable purpose',
},
{
	date: 'November 8, 2024',
    file: '2024/11/08_ClaimSharks.asp',
    title: 'SCAM STOPPER: Attorney General Ellison warns of claim sharks on Veterans Day',
    lede: 'The warning is part of the Attorney General’s monthly "Scam Stoppers" series, aiming to protect Minnesota consumers from common scams',
},
{
	date: 'November 7, 2024',
    file: '2024/11/07_SaavedraOlivar.asp',
    title: 'Attorney General’s Office and Isanti County Attorney’s Office secure 2nd degree murder, other convictions in Isanti County',
    lede: 'Court convicts Fredy Saavedra Olivar on four counts following December 2023 murder of Jose De Jesus Diaz Fernandes. Attorney General’s Office prosecuted this case upon request of Isanti County Attorney, per state law',
},
{
	date: 'November 7, 2024',
    file: '2024/11/07_Barrientos-Quintana.asp',
    title: 'Edgar Barrientos murder conviction vacated after AGO uncovered evidence of innocence',
    lede: 'AGO’s Conviction Review Unit helps free man wrongfully convicted in 2009; Barrientos released from prison, case against him dismissed ',
},
{
	date: 'November 4, 2024',
    file: '2024/11/04_GenericDrugPrices.asp',
    title: 'Attorney General Ellison announces $49M in settlements in generic drug price-fixing litigation',
    lede: 'Heritage Pharmaceuticals and Apotex to cooperate in ongoing 50-state antitrust litigation against generic-drug companies',
},
{
	date: 'November 1, 2024',
    file: '2024/11/01_BlueCross.asp',
    title: 'Attorney General Ellison secures settlement to improve access to mental healthcare',
    lede: 'Blue Cross will voluntarily contribute $600,000 to Minnesota State University-Mankato for use by the Center for Rural Behavioral Health',
},
{
	date: 'October 29, 2024',
    file: '2024/10/29_DataBreach.asp',
    title: 'SCAM STOPPER: Attorney General Ellison shares steps to take following a data breach',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from common scams.',
},
{
	date: 'October 21, 2024',
    file: '2024/10/21_FinancialSolutionsGroup.asp',
    title: 'Attorney General Ellison shuts down fraudulent debt settlement companies and secures over $1 million in refunds for consumers',
    lede: 'In total, Ellison has returned over $2.8 million to victims of predatory debt settlement companies',
},
{
	date: 'October 18, 2024',
    file: '2024/10/18_iDentidad.asp',
    title: 'Attorney General Ellison issues robocall warning to iDentidad',
    lede: 'Attorney General Ellison is part of the Anti-Robocall Multistate Litigation Task Force of 51 bipartisan attorneys general, which investigates and takes legal action against those responsible for routing illegal robocall traffic into and across the United States.',
},
{
	date: 'October 17, 2024',
    file: '2024/10/17_Xcel.asp',
    title: 'Attorney General Ellison helps secure tens of millions in refunds for Xcel Energy customers',
    lede: 'At a hearing on October 15, 2024, the Public Utilities Commission sided with Attorney General Ellison’s Office and the Minnesota Department of Commerce when it voted to refund Xcel Energy customers tens of millions of dollars, with interest, for replacement power costs resulting from a power plant outage occurring in 2011.',
},
{
	date: 'October 14, 2024',
    file: '2024/10/14_Wall.asp',
    title: 'Attorney General Ellison secures victory against tax debt settlement company after 12-day trial',
    lede: 'Court found company deceived hundreds of Minnesotans knowingly and in bad faith, finding they were ‘essentially tricked into paying millions of dollars in fees to Wall’ and that company ‘inflicted significant injury upon hundreds of Minnesota consumers’',
},
{
	date: 'October 13, 2024',
    file: '2024/10/13_ExpungementClinic.asp',
    title: 'Attorney General Ellison’s Office to hold expungement clinic in Moorhead',
    lede: 'At the clinic, the Minnesota Attorney General’s Office will be available to review Minnesotans’ records, determine if they are eligible for expungement, and if they are, work with them and with the prosecutors to file the necessary paperwork to have their records sealed.',
},
{
	date: 'October 10, 2024',
    file: '2024/10/10_NorthernLakesRescue.asp',
    title: 'Attorney General Ellison reaches settlement with nonprofit over founder’s misuse of charitable assets',
    lede: 'AG’s investigation finds Shannon Steele unlawfully used $156K of Northern Lakes Rescue charitable assets for personal purposes; prohibited from serving nonprofit in any way',
},
{
	date: 'October 9, 2024',
    file: '2024/10/09_Marriott.asp',
    title: 'Attorney General Ellison reaches data-breach settlement with Marriott',
    lede: '4-year breach of Starwood guest reservation database exposed 131.5 million guest records, including passport numbers and payment card information; Marriot to pay $52M nationally, $800K to Minnesota',
},
{
	date: 'October 8, 2024',
    file: '2024/10/08_TikTok.asp',
    title: 'Bipartisan coalition of attorneys general seek court enforcement as TikTok fails to preserve and produce evidence in multistate investigation',
    lede: 'Attorney General Ellison and the bipartisan coalition began an investigation into TikTok in 2022 to determine whether TikTok is violating state consumer protection laws in ways that have fueled the ongoing crisis in the mental health of children and teens.',
},
{
	date: 'October 4, 2024',
    file: '2024/10/04_Odette.asp',
    title: 'Elizabeth Odette to chair national antitrust task force',
    lede: 'Minnesota Assistant AG selected as chair of Multistate Antitrust Task Force of bipartisan National Association of Attorneys General',
},
{
	date: 'October 3, 2024',
    file: '2024/10/03_VotingRights.asp',
    title: 'Attorney General Ellison releases guidance on voting safely and free from intimidation and misinformation, along with new elections report form',
    lede: '“Know Your Rights” webpage and elections report form now public on Attorney General’s sites',
},
{
	date: 'October 3, 2024',
    file: '2024/10/03_Evergreen.asp',
    title: 'Attorney General Ellison wins protections for dairy workers in major wage theft action',
    lede: 'Settlement with Evergreen Dairy to bring employee housing up to code, document pay terms and conditions of employment, pay $250K in back wages',
},
{
	date: 'October 2, 2024',
    file: '2024/10/02_Nolosha.asp',
    title: 'Attorney General Ellison files fraud lawsuit to protect Somali immigrant families',
    lede: 'Ellison sues property development company in response to reports of fraud from the public',
},
{
	date: 'October 2, 2024',
    file: '2024/10/02_DebtFairnessAct.asp',
    title: 'Attorney General Ellison celebrates the start of the Debt Fairness Act',
    lede: 'As of October 1, medical debt will no longer be automatically transferred to one’s spouse, cannot be used to deny medically necessary care, can no longer be reported to credit reporting agencies',
},
{
	date: 'September 27, 2024',
    file: '2024/09/27_GunTrafficking.asp',
    title: 'Attorney General Ellison supports federal regulations on gun trafficking',
    lede: 'Joins 22 AGs in supporting ATF rule to curb gun trafficking',
},
{
	date: 'September 25, 2024',
    file: '2024/09/25_RainbowHealth.asp',
    title: 'Attorney General Ellison seeks court oversight over Rainbow Health dissolution',
    lede: 'Attorney General seeks court supervision over Rainbow Health to ensure orderly disposition of nonprofit assets',
},
{
	date: 'September 25, 2024',
    file: '2024/09/25_MVRealty.asp',
    title: 'Attorney General Ellison sues telemarketing and real estate sales company for deceiving homeowners and suing their heirs',
    lede: 'MV Realty promised quick cash for homeowners in exchange for serving as eventual realtor, unlawfully hid egregious and unfair contract details',
},
{
	date: 'September 20, 2024',
    file: '2024/09/20_Carpenter.asp',
    title: 'Michael Carpenter sentenced to life in prison for murder of Nicole Hammond',
    lede: 'Carpenter convicted of 1st degree premeditated murder; received statutory sentence of life imprisonment without release',
},
{
	date: 'September 19, 2024',
    file: '2024/09/19_MortgageAssistanceScams.asp',
    title: 'Attorney General Ellison warns of growing reports of mortgage assistance scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from common scams',
},
{
	date: 'September 17, 2024',
    file: '2024/09/17_ShamsiaHopes.asp',
    title: 'Attorney General Ellison shuts down nonprofit accused of being a conduit for fraud',
    lede: 'Investigation found misuse by founder and president Mekfira Hussein of Shamsia Hopes’ charitable assets',
},
{
	date: 'September 10, 2024',
    file: '2024/09/10_DPB.asp',
    title: 'Attorney General Ellison secures relief for asylum seekers harmed by immigration attorney’s misrepresentations',
    lede: 'Settlement secures roughly $100,000 in refunds for dozens of immigrants who paid for legal services not properly rendered',
},
{
	date: 'September 6, 2024',
    file: '2024/09/06_WorkingForWorkers.asp',
    title: 'Attorney General Ellison issues inaugural ‘Working for Workers’ report',
    lede: 'Report highlights ways Office helps workers fight wage theft; to be issued annually around Labor Day',
},
{
	date: 'September 4, 2024',
    file: '2024/09/04_Shocinski.asp',
    title: 'Attorney General Ellison sues online retailer for selling $900K in products he didn’t deliver, advertising charitable support he didn’t provide',
    lede: 'Files lawsuit against William Shocinski, Jr. and multiple businesses he has owned for thousands of violations of Minnesota’s consumer protection laws',
},
{
	date: 'August 30, 2024',
    file: '2024/08/30_RTTC.asp',
    title: 'Attorney General Ellison requires fundraiser to pay back charity, bars founders from all future fundraising',
    lede: 'Minnesota Attorney General Keith Ellison announced that he has reached a settlement with professional fundraiser Ride to The Chip, LLC and its founders',
},
{
	date: 'August 30, 2024',
    file: '2024/08/30_LumberLiquidators.asp',
    title: 'Attorney General Ellison issues consumer alert about Lumber Liquidators bankruptcy',
    lede: 'Chanhassen, Rochester, and St. Cloud stores to close as part of company’s bankruptcy restructuring',
},
{
	date: 'August 29, 2024',
    file: '2024/08/29_VapingProducts.asp',
    title: 'Attorney General Keith Ellison warns against continued sales of unauthorized e-cigarettes and nicotine pouches',
    lede: 'Letter to 5,000 distributors and retailers requests they stop selling unauthorized and illegal products; details the harm to youth from marketing and sale of unauthorized flavored tobacco products, consequences under federal and state law',
},
{
	date: 'August 23, 2024',
    file: '2024/08/23_RealPage.asp',
    title: 'Attorney General Ellison sues RealPage for algorithmic pricing scheme that harms renters',
    lede: 'Joins DOJ and seven states alleging RealPage’s pricing algorithm violates antitrust laws',
},
{
	date: 'August 21, 2024',
    file: '2024/08/21_Barrientos.asp',
    title: 'Conviction Review Unit recommends 2009 Hennepin County murder conviction be vacated',
    lede: 'After three-year investigation, CRU issues 293-page report highlighting exculpatory evidence jury never heard, inaccuracies in how evidence was presented to jury ',
},
{
	date: 'August 20, 2024',
    file: '2024/08/20_Award.asp',
    title: 'Attorney General Ellison’s report on social media’s effect on young people wins national award',
    lede: 'National Conference of State Legislatures recognizes report with 2024 Notable Document Award; second time AG’s Office so honored',
},
{
	date: 'August 15, 2024',
    file: '2024/08/15_Insulin.asp',
    title: 'Free insulin now flowing to Minnesota clinics',
    lede: 'Insulin manufacturer Eli Lilly and nonprofit Direct Relief partnering with nine clinics to provide free insulin throughout Minnesota, thanks to settlement AG Ellison negotiated',
},
{
	date: 'August 7, 2024',
    file: '2024/08/07_RestoreTheVote.asp',
    title: 'Attorney General Ellison successfully defends Restore the Vote Act',
    lede: 'Minnesota Supreme Court unanimously rejects attempt to disenfranchise Minnesotans',
},
{
	date: 'August 5, 2024',
    file: '2024/08/05_Carpenter.asp',
    title: 'Attorney General’s Office secures 1st degree and 2nd degree murder convictions in Benton County',
    lede: 'Jury convicts Michael Carpenter of all charges, including premeditated and intentional murder, following October 2022 killing of Nicole Hammond',
},
{
	date: 'August 2, 2024',
    file: '2024/08/02_AllInMinnesota.asp',
    title: 'Attorney General Ellison reaches settlement with youth soccer nonprofit to address violations of charities laws',
    lede: 'All In Minnesota failed to meet board governance requirements, including financial controls and board scrutiny of conflicted transactions',
},
{
	date: 'August 1, 2024',
    file: '2024/08/01_Dwell.asp',
    title: 'Attorney General Ellison obtains compensation for homeowners who lost their equity when in foreclosure',
    lede: 'Dwell Equities, LLC will pay Minnesota almost $240,000 and stop purchasing residential homes and equities in foreclosure proceedings',
},
{
	date: 'August 1, 2024',
    file: '2024/08/01_RecyclingBags.asp',
    title: 'Attorney General Ellison reaches settlement with Reynolds, Walmart over deceptive marketing of ‘recycling’ bags that are not recyclable',
    lede: 'Companies to stop selling products in Minnesota for 2 ½ years, can reenter market only if bags are clearly marked as non-recyclable; will also pay $200K, equivalent of 100% of profits',
},
{
	date: 'July 31, 2024',
    file: '2024/07/31_TelemarketingScams.asp',
    title: 'Attorney General Ellison warns Minnesotans about telemarketing scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from fraud.',
},
{
	date: 'July 31, 2024',
    file: '2024/07/31_Valvoline.asp',
    title: 'Attorney General Ellison ends unfair labor practices at major auto services company',
    lede: 'Valvoline ends non-compete agreements which banned employees from working at another oil change business within 100 miles for one year after leaving company',
},
{
	date: 'July 30, 2024',
    file: '2024/07/30_OpenCarry.asp',
    title: 'Attorney General Ellison asks court to review decision allowing 18-year-olds to obtain open-carry gun permits',
    lede: 'Petitions entire 8th Circuit Court of Appeals to review three-judge panel decision ruling that 18- to 20-year-olds may obtain permits to open-carry pistols in Minnesota, contrary to longstanding Minnesota law and historical tradition',
},
{
	date: 'July 25, 2024',
    file: '2024/07/25_MisclassificationFraud.asp',
    title: 'Attorney General Ellison celebrates signing of employer misclassification fraud bill',
    lede: 'New bill makes it harder for employers to incorrectly classify employees as independent contractors',
},
{
	date: 'July 23, 2024',
    file: '2024/07/23_Sanofi.asp',
    title: 'Attorney General Ellison secures more low-cost insulin for Minnesotans',
    lede: 'Insulin manufacturer Sanofi agrees to cap out-of-pocket cost of its insulin products at $35 per monthly prescription, and provide free insulin to the neediest Minnesotans, for five years, in settlement of 2018 lawsuit',
},
{
	date: 'July 17, 2024',
    file: '2024/07/17_Solar.asp',
    title: 'Attorney General Ellison takes actions to protect consumers from deceptive conduct in the solar industry',
    lede: 'Ellison obtains four new settlements with multiple entities regarding deceptive practices and misleading residential solar panel advertisements',
},
{
	date: 'July 10, 2024',
    file: '2024/07/10_ChangeHealthcare.asp',
    title: 'Attorney General Ellison shares resources available to consumers following the Change Healthcare cyberattack',
    lede: 'Change Healthcare offering Minnesotans two years of credit monitoring and identity theft protections',
},
{
	date: 'July 3, 2024',
    file: '2024/07/03_TobaccoSettlement.asp',
    title: 'Attorney General Ellison moves to recover $58M in Big Tobacco underpayments under Minnesota’s historic tobacco settlement',
    lede: 'Alleges Philip Morris misrepresented settlement requirements to payment administrator; moves to recover underpayments, interest, and civil penalties, and prevent future underpayments',
},
{
	date: 'June 28, 2024',
    file: '2024/06/28_AlliedWasteServices.asp',
    title: 'Attorney General Ellison wins $128K in refunds for waste-disposal company consumers over undisclosed fees',
    lede: 'Investigation found waste disposal company Republic Services failed to properly disclose fees to consumers; settlement will require disclosure moving forward',
},
{
	date: 'June 20, 2024',
    file: '2024/06/20_TopWorkplace.asp',
    title: 'Attorney General’s Office named a top workplace in Minnesota for fourth year in a row',
    lede: 'Office received special recognition for leadership among midsize employers',
},
{
	date: 'June 19, 2024',
    file: '2024/06/19_MedicaidFraud.asp',
    title: 'Attorney General Ellison charges five with stealing more than $10M in two Medicaid fraud prosecutions',
    lede: 'Three charged with more than $9M in fraud as part of Office’s largest-ever prosecution; two others charged with $1.4M in fraud in connection with separate, multi-year prosecution',
},
{
	date: 'June 17, 2024',
    file: '2024/06/17_DebtFairness.asp',
    title: 'Attorney General Ellison celebrates signing of Debt Fairness Act',
    lede: 'New law reforms medical-debt collection, wage garnishment, and bankruptcy, including banning automatic transfer of medical debt to one’s spouse, banning reporting medical debt to credit bureaus, and banning denying necessary medical care over unpaid bills',
},
{
	date: 'June 11, 2024',
    file: '2024/06/11_JohnsonJohnson.asp',
    title: 'Attorney General Ellison reaches $700 million nationwide settlement against Johnson & Johnson',
    lede: 'J&J will pay Minnesota more than $10 million and stop manufacturing and selling talc products',
},
{
	date: 'June 10, 2024',
    file: '2024/06/10_PCMA.asp',
    title: 'Attorney General Ellison leads effort asking Supreme Court to rule on states’ authority to regulate pharmacy benefit managers',
    lede: 'Leads another bipartisan coalition of 32 AGs in requesting high court review Oklahoma’s authority to regulate abusive behavior of PBMs',
},
{
	date: 'June 6, 2024',
    file: '2024/06/06_Pippitt.asp',
    title: 'Conviction Review Unit recommends first-degree murder conviction be vacated after 23 years',
    lede: 'Brian Pippitt files motion in Aitkin County to vacate 2001 conviction',
},
{
	date: 'June 5, 2024',
    file: '2024/06/05_McKeever.asp',
    title: 'Attorney General’s Office completes prosecutions related to murder of Zaria McKeever',
    lede: 'Eriana Haynes and Tavion James sentenced today after guilty pleas to aiding an offender in brutal November 2022 slaying',
},
{
	date: 'June 3, 2024',
    file: '2024/06/03_UprightCane.asp',
    title: 'Online retailer agrees to 10-year ban after scamming seniors, disabled people',
    lede: 'Upright Cane and owner Caelan Nwokeuku sold walkers and scooters to seniors and disabled Minnesotans, largely those living in Greater Minnesota, but failed to deliver a single one; will pay $50K in fines and restitution',
},
{
	date: 'June 3, 2024',
    file: '2024/06/03_FleetFarm.asp',
    title: 'Attorney General Ellison adds claim against Fleet Farm for violating the Minnesota Gun Control Act',
    lede: 'Court also authorizes Attorney General to seek civil penalties, fees, and costs from Fleet Farm; affirms Attorney General’s broad civil powers to protect Minnesotans from unfair and unlawful conduct',
},
{
	date: 'May 30, 2024',
    file: '2024/05/30_NCAA.asp',
    title: 'Attorney General Ellison reaches settlement with NCAA over transfer rule',
    lede: 'NCAA will not require Division I student athletes to wait a year to compete simply for transferring schools',
},
{
	date: 'May 29, 2024',
    file: '2024/05/29_Perry.asp',
    title: 'Attorney General Ellison calls for DOJ investigation into murder of Garrett Foster following Texas pardon',
    lede: 'Garrett Foster was protesting racial injustice when he was shot and killed by Daniel Perry in July 2020; Perry was convicted in April 2023 but pardoned by Texas governor earlier this month',
},
{
	date: 'May 29, 2024',
    file: '2024/05/29_ContractForDeed.asp',
    title: 'Attorney General Ellison warns Minnesotans to avoid contract for deed pitfalls and scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from fraud.',
},
{
	date: 'May 28, 2024',
    file: '2024/05/28_Spectrum.asp',
    title: 'Attorney General Ellison reaches settlement with medical device manufacturer over time-shaving',
    lede: 'Attorney General alleges Spectrum Plastics Group rounded time to the disadvantage of its employees',
},
{
	date: 'May 23, 2024',
    file: '2024/05/23_LiveNation.asp',
    title: 'Attorney General Ellison joins federal antitrust lawsuit against Live Nation',
    lede: 'Joins DOJ and bipartisan coalition of 30 AGs in alleging Live Nation, owner of Ticketmaster, has illegally monopolized the live-entertainment industry',
},
{
	date: 'May 20, 2024',
    file: '2024/05/20_EmployerMisclassification.asp',
    title: 'Attorney General Ellison, lawmakers, and other leaders commend legislature for passing bill to combat employer misclassification fraud',
    lede: 'Employer misclassification fraud happens when an employer incorrectly classifies a full-time employee as an independent contractor, resulting in that employee losing access to important rights, benefits, and protections, like overtime pay, workers compensation, earned sick and safe time, and more.',
},
{
	date: 'May 16, 2024',
    file: '2024/05/16_DolanPrinting.asp',
    title: 'Attorney General Ellison reaches settlement with Dolan Printing over non-compete agreements',
    lede: 'Dolan Printing to release current and former workers from pre-existing non-compete agreements',
},
{
	date: 'May 16, 2024',
    file: '2024/05/16_FederalChildNutritionFraud.asp',
    title: 'Attorney General Ellison shuts down 17 sham nonprofits involved in federal child nutrition fraud',
    lede: 'The court-ordered dissolutions will protect the public from further fraudulent use of the 17 nonprofits, which were used to steal funds intended to feed children during the COVID-19 pandemic',
},
{
	date: 'May 16, 2024',
    file: '2024/05/16_DebtFairnessAct.asp',
    title: 'Attorney General Ellison commends Senate for final passage of the Debt Fairness Act',
    lede: 'Act reforms medical debt collection, wage garnishment, and bankruptcy, including banning automatic transfer of medical debt to one’s spouse and banning denying necessary medical care over unpaid bills',
},
{
	date: 'May 14, 2024',
    file: '2024/05/14_Banken.asp',
    title: 'Attorney General Ellison sues home seller and lender for predatory lending, deceptive practices, and religious discrimination',
    lede: 'Files lawsuit against Chadwick Banken and multiple businesses Banken owns for selling homes via contract for deed using deceptive and predatory practices, illegally discriminating against Muslim purchasers',
},
{
	date: 'May 9, 2024',
    file: '2024/05/09_AvidTelecom.asp',
    title: 'Court rejects Avid Telecom’s attempts to dismiss illegal-robocalls case',
    lede: 'Attorney General Ellison’s lawsuit with bipartisan 49-state coalition to proceed; Avid allegedly sent or attempted more than 24 billion scam calls',
},
{
	date: 'May 9, 2024',
    file: '2024/05/09_WirelessCarriers.asp',
    title: 'Attorney General Ellison reaches settlements with AT&amp;T, T-Mobile, and Verizon over deceptive advertising',
    lede: 'Companies required to change practices and provide enhanced disclosures as well as pay Minnesota over $146,000',
},
{
	date: 'May 3, 2024',
    file: '2024/05/03_MedicaidFraud.asp',
    title: 'Attorney General Ellison charges eight in $2.6M Medicaid fraud scheme',
    lede: 'Alleges defendants stole identities from hundreds in Faribault area to bill Medicaid for services not received or provided, or ineligible for reimbursement',
},
{
	date: 'May 2, 2024',
    file: '2024/05/02_3M.asp',
    title: 'Attorney General Ellison returns $1 million in back wages to 3M employees after unauthorized paycheck deductions',
    lede: 'Settlement with 3M will affect 1,690 employees',
},
{
	date: 'April 30, 2024',
    file: '2024/04/30_HomeImprovementScams.asp',
    title: 'As the weather warms, Attorney General Ellison warns Minnesotans to avoid home improvement scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper series, aiming to help protect Minnesota consumers from fraud.',
},
{
	date: 'April 25, 2024',
    file: '2024/04/25_UnitedHealthGroup.asp',
    title: 'Attorney General Ellison urges UnitedHealth Group to help patients and providers harmed by cyberattack on Change Healthcare',
    lede: 'Leads bipartisan coalition of 22 attorneys general to urge UHG take more meaningful action in wake of catastrophic February 2024 attack that disrupted healthcare nationwide',
},
{
	date: 'April 19, 2024',
    file: '2024/04/19_Mangi.asp',
    title: 'Attorney General Ellison urges confirmation of ‘highly qualified’ Adeel Mangi to federal appeals bench',
    lede: 'Leads coalition of 11 AGs in advocating for Senate confirmation of Mangi, who would be the first Muslim to sit on a federal appeals court',
},
{
	date: 'April 19, 2024',
    file: '2024/04/19_VETSIndexes.asp',
    title: 'Minnesota Attorney General’s Office named top employer for veterans',
    lede: 'VETS Indexes 4 Star Employer Award highlights AG Ellison’s commitment to hiring, retaining, and supporting veterans',
},
{
	date: 'April 17, 2024',
    file: '2024/04/17_DOT.asp',
    title: 'Attorney General Ellison announces airline passenger protection partnership with U.S. Department of Transportation',
    lede: 'Ellison praised the new coordinated effort that will provide better protection to millions of U.S. airline passengers',
},
{
	date: 'April 15, 2024',
    file: '2024/04/15_DFA.asp',
    title: 'Attorney General Ellison hails House passage of key provisions of Debt Fairness Act',
    lede: 'Key provisions of the Act included in Commerce Policy Omnibus bill include banning the automatic transfer of medical debt to a patient’s spouse, protecting Minnesotans’ last $4k from collections, banning reporting medical debt to credit agencies, and more',
},
{
	date: 'April 1, 2024',
    file: '2024/04/01_McKeever.asp',
    title: 'Attorney General’s Office secures final guilty pleas in murder of Zaria McKeever',
    lede: 'Erick Haynes pleads guilty to first-degree murder in brutal November 2022 slaying, to receive life sentence with possibility of parole after 30 years. Eriana Haynes and Tavion James plead guilty to aiding and abetting an offender after the fact. Foday Kevin Kamara previously pleaded guilty to 2nd-degree intentional murder',
},
{
	date: 'March 30, 2024',
    file: '2024/03/30_DebtCollectionScams.asp',
    title: 'Attorney General Ellison warns Minnesotans to avoid debt collection scams',
    lede: 'The warning is part of the Attorney General’s monthly Scam Stopper alerts, aiming to help protect Minnesota consumers from fraud',
},
{
	date: 'March 29, 2024',
    file: '2024/03/29_AFEAP.asp',
    title: 'Attorney General Ellison secures dismissal of nonprofit officials over misuse of funds',
    lede: 'Settlement also requires Action for East African People to rectify multiple governance failures, comply fully with ongoing AGO civil investigation',
},
{
	date: 'March 28, 2024',
    file: '2024/03/28_Glock.asp',
    title: 'Attorney General Ellison tells Glock to preserve evidence related to firearms’ easy conversion into machine guns',
    lede: 'Joins coalition of 13 AGs in letter to weapons manufacturer in wake of City of Chicago lawsuit over switches that turn pistols into machine guns',
},
{
	date: 'March 25, 2024',
    file: '2024/03/25_Evergreen.asp',
    title: 'Attorney General Ellison wins protections for dairy-farm workers while wage theft lawsuit continues',
    lede: 'Evergreen agrees to temporary injunction containing measures to prevent wage theft and improve housing conditions while Attorney General Ellison continues to prosecute civil lawsuit',
},
{
	date: 'March 22, 2024',
    file: '2024/03/22_Kamara.asp',
    title: 'Attorney General’s Office secures guilty plea in murder of Zaria McKeever',
    lede: 'Per plea agreement between AG’s Office and defendant, Foday Kevin Kamara agreed to be certified as an adult, plead guilty to 2nd-degree intentional murder, testify at upcoming trial, and be sentenced to 130 months',
},
{
	date: 'March 21, 2024',
    file: '2024/03/21_Apple.asp',
    title: 'Attorney General Ellison sues Apple for monopolizing smartphone markets, joining DOJ and 15 state AGs',
    lede: 'Complaint alleges Apple’s broad-based, exclusionary conduct makes it harder for Americans to switch smartphones, undermines innovation for apps, products, and services, and imposes extraordinary costs on developers, businesses, and consumers',
},
{
	date: 'March 21, 2024',
    file: '2024/03/21_CleanSlate.asp',
    title: 'Attorney General Ellison announces 2024 ‘Clean Slate’ expungement tour',
    lede: 'Tour kicks off in St. Paul this Saturday in partnership with Ramsey County Attorney John Choi',
},
{
	date: 'March 20, 2024',
    file: '2024/03/20_TopWorkplace.asp',
    title: 'Minnesota Attorney General’s Office named Top Workplace USA for 3rd year in a row',
    lede: 'AGO has been named a Star Tribune Top Workplace for 3 years in a row as well',
},
{
	date: 'March 18, 2024',
    file: '2024/03/18_EHN_Butler.asp',
    title: 'Attorney General Ellison reaches settlement with veterans charity and its founder over misuse funds, governance failures',
    lede: 'Founder spent charitable funds on personal food, coffee, gas, clothing, hair, nails, cigarettes, gambling, and more',
},
{
	date: 'March 15, 2024',
    file: '2024/03/15_Moreno.asp',
    title: 'Attorney General’s Office and Freeborn County Attorney’s Office secures 2nd-degree murder, other convictions in Freeborn County',
    lede: 'Jury convicts Ben Moreno on five counts in August 2022 murder of Juan Vasquez Jr. and attempted murder of Marco Posada',
},
{
	date: 'March 15, 2024',
    file: '2024/03/15_HavenBrookHomes.asp',
    title: 'Attorney General Ellison reaches landmark settlement with single-family rental-home landlords',
    lede: 'Resolution of AG’s 2022 lawsuit against HavenBrook Homes provides $2.2M in restitution and $2M in debt forgiveness for tenants, creates path for sale of rental homes to affordable-housing entities',
},
{
	date: 'March 14, 2024',
    file: '2024/03/14_MisclassReport.asp',
    title: 'New report finds misclassification fraud a growing problem in Minnesota',
    lede: 'OLA report showcases the need for legislative action to combat misclassification fraud',
},
{
	date: 'March 8, 2024',
    file: '2024/03/08_HealthcareImposters.asp',
    title: 'Attorney General Ellison warns consumers of healthcare provider imposter scams',
    lede: 'State hospital associations have received reports from patients who have been targeted by scammers seeking to steal their credit card information.',
},
{
	date: 'March 8, 2024',
    file: '2024/03/08_SolarLending.asp',
    title: 'Attorney General Ellison sues solar lenders over $35M in deceptive hidden fees',
    lede: 'Attorney General’s investigation uncovered four large solar-lending companies charged $35 million in hidden fees on nearly 5,000 loans that financed sales of residential solar panels',
},
{
	date: 'March 1, 2024',
    file: '2024/03/01_Aspirus_SLH.asp',
    title: 'Attorney General Ellison completes review of merger between St. Luke’s and Aspirus, reaches five-year oversight agreement',
    lede: 'Under new Health Care Entity Transactions law, Aspirus and St. Luke’s to report to Attorney General on merger commitments; reports will allow AG to determine whether merger continues to comply with the law and is in public interest',
},
{
	date: 'February 22, 2024',
    file: '2024/02/22_OnlineLenders.asp',
    title: 'Attorney General Ellison secures settlement stopping predatory online lending and collection of illegal interest',
    lede: 'Attorney General brought federal lawsuit in 2023 to stop online lenders targeting vulnerable consumers and charging 400-800% interest; lenders had collected at least $540K from defaulted Minnesota borrowers',
},
{
	date: 'February 15, 2024',
    file: '2024/02/15_SolarGardenRefunds.asp',
    title: 'Attorney General Ellison secures $85K in refunds for solar garden consumers charged unlawful early-termination fees',
    lede: 'Community solar garden operator owners also agree to suspend enforcement of early-termination fees in current contracts and not to enter into new contracts with unlawful fees',
},
{
	date: 'February 14, 2024',
    file: '2024/02/14_RomanceScams.asp',
    title: 'On Valentine’s Day, Attorney General Ellison Warns Minnesotans to Avoid Romance Scams',
    lede: 'The warning is the first in a series of monthly Scam Stopper alerts that Attorney General Ellison will be issuing to help protect Minnesota consumers from fraud.',
},
{
	date: 'February 7, 2024',
    file: '2024/02/07_EliLilly.asp',
    title: 'Attorney General Ellison secures low-cost insulin for Minnesotans',
    lede: 'In resolution of 2018 lawsuit, insulin manufacturer Eli Lilly agrees to cap out-of-pocket cost of its insulin products at $35 per monthly prescription, and provide free insulin to clinics serving the neediest Minnesotans, for five years',
},
{
	date: 'February 7, 2024',
    file: '2024/02/07_Bremer.asp',
    title: 'Attorney General Ellison prevails at Minnesota Supreme Court on Otto Bremer trustee removal case',
    lede: 'Supreme Court upholds district court and court of appeals decisions to remove former trustee, stating he “repeatedly placed his own priorities before those of the Trust”',
},
{
	date: 'February 2, 2024',
    file: '2024/02/02_HonorTheEarth.asp',
    title: 'Attorney General Ellison reaches voluntary settlement requiring environmental charity to improve governance',
    lede: 'Honor the Earth cooperating to correct previous governance issues',
},
{
	date: 'February 2, 2024',
    file: '2024/02/02_Publicis.asp',
    title: 'Attorney General Ellison announces $350 million settlement with multinational marketing firm Publicis over role in opioid epidemic',
    lede: 'Minnesota to receive over $4.4M. Brings Minnesota’s total in opioid settlements to $564M.',
},
{
	date: 'February 1, 2024',
    file: '2024/02/01_EmergingTechReport.asp',
    title: 'Attorney General Ellison releases report on social media and AI’s effect on young people',
    lede: 'Report commissioned by Legislature details how emerging technologies are harming youth and makes recommendations for creating safer online environment for youth',
},
{
	date: 'January 22, 2024',
    file: '2024/01/22_SFS.asp',
    title: 'Attorney General Ellison sues debt-relief company for illegally swindling over $100 million from families struggling with debt',
    lede: 'AG Ellison joins the CFPB and six other attorneys general in filing the lawsuit against Strategic Financial Solutions',
},
{
	date: 'January 19, 2024',
    file: '2024/01/19_NCAA.asp',
    title: 'Attorney General Ellison joins antitrust lawsuit against NCAA over transfer rule',
    lede: 'Alleges rule is illegal restraint on athletes’ ability to sell own image, control own education',
},
{
	date: 'January 12, 2024',
    file: '2024/01/12_ClemencyReviewCommission.asp',
    title: 'Attorney General Ellison makes appointments to new Clemency Review Commission',
    lede: 'Names former Public Safety Commissioner John Harrington, U of M law professor Perry Moriearty, and Carl Crawford',
},
{
	date: 'January 8, 2024',
    file: '2024/01/08_ExxonKochAPI.asp',
    title: 'Minnesota’s climate-deception lawsuit to finally proceed in state court after SCOTUS denies review of lower-court ruling',
    lede: 'U.S. Supreme Court affirms ruling by the US Court of Appeals for the 8th Circuit remanding lawsuit to Minnesota state court, where AG Ellison originally filed it in June 2020',
},
{
	date: 'January 8, 2024',
    file: '2024/01/08_Evergreen.asp',
    title: 'Attorney General Ellison sues large dairy farm for millions in wage theft',
    lede: 'Civil lawsuit alleges Evergreen Acres has failed to pay at least $3M of vulnerable workers’ earned wages, illegally charged rent for substandard housing, and maintained a culture of fear and violence to discourage reporting',
},
	
];



	
